//! Self-healing and self-correction recovery framework.
//!
//! Implements Detect → Diagnose → Plan → Validate → Execute → Verify → Audit
//! without bypassing safety validation, hardware verification, capability
//! verification, kill switch, or human approval requirements.

use crate::diagnosis::DiagnosisReport;
use crate::modes::{extract_operating_modes, validate_modes};
use crate::types::ModeKind;
use serde::{Deserialize, Serialize};
use spanda_ast::assurance_decl::{MitigationDecl, RecoveryPolicyDecl};
use spanda_ast::nodes::Program;
use spanda_capability::infer_robot_capabilities;
use spanda_hardware::{verify_program_compatibility, VerifyOptions};
use spanda_readiness::{
    analyze_failure, default_deploy_target, evaluate_readiness, verify_approvals,
    FailureAnalysisReport, ReadinessOptions,
};

/// Outcome status for a recovery attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum RecoveryStatus {
    Success,
    PartialSuccess,
    Failed,
    Aborted,
    Unsafe,
}

/// Autonomy level for recovery execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RecoveryLevel {
    /// Detection only — no automated recovery.
    Level0DetectionOnly = 0,

    /// Recommend recovery actions to operator.
    Level1Recommend = 1,

    /// Automatic low-risk recovery without approval.
    Level2AutomaticLowRisk = 2,

    /// Automatic recovery after safety validation.
    Level3AutomaticWithValidation = 3,

    /// High-risk recovery requires human approval.
    Level4HumanApproval = 4,
}

/// Failure classification for recovery planning.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum FailureClassification {
    SensorFailure,
    ActuatorFailure,
    ConnectivityFailure,
    ProviderFailure,
    PackageFailure,
    MissionFailure,
    HealthDegradation,
    FleetFailure,
    SwarmFailure,
    SafetyFailure,
    Unknown,
}

/// Recovery strategy kind.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryStrategy {
    Failover,
    DegradedMode,
    SpeedReduction,
    SensorRecalibration,
    ProviderReconnect,
    ConnectivityRestart,
    PackageReload,
    DeviceReinitialize,
    RedundantHardwareSwitch,
    RouteChange,
    MissionPause,
    OperatorAlert,
    FleetReassign,
    SwarmRedistribute,
    Custom(String),
}

/// Self-correction action types.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SelfCorrectionAction {
    RecalibrateSensor { sensor: String },
    ReconnectProvider { provider: String },
    RestartConnectivity { channel: String },
    ReloadPackage { package: String },
    ReinitializeDevice { device: String },
    SwitchRedundantHardware { component: String },
    ChangeRoute { route: String },
    ReduceSpeed { limit: String },
    PauseMission,
    EnterMode { mode: String },
    Custom { action: String },
}

/// Operating mode for safe transitions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum OperationalMode {
    NormalMode,
    DegradedMode,
    SafeMode,
    EmergencyMode,
    RecoveryMode,
}

impl OperationalMode {
    /// Map operational mode to assurance `ModeKind`.
    pub fn to_mode_kind(self) -> ModeKind {
        // Description:
        //     To mode kind.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     result: ModeKind
        //         Return value from `to_mode_kind`.
        //
        // Example:

        //     let result = instance.to_mode_kind();

        match self {
            Self::NormalMode => ModeKind::Normal,
            Self::DegradedMode => ModeKind::Degraded,
            Self::SafeMode => ModeKind::Safe,
            Self::EmergencyMode => ModeKind::Emergency,
            Self::RecoveryMode => ModeKind::Recovery,
        }
    }
}

/// Single planned recovery action.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlannedRecoveryAction {
    pub description: String,
    pub strategy: RecoveryStrategy,
    pub correction: Option<SelfCorrectionAction>,
    pub risk: String,
    pub requires_approval: bool,
    pub order: u32,
}

/// Recovery plan generated by the planner.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryPlan {
    pub name: String,
    pub failure: String,
    pub classification: FailureClassification,
    pub diagnosis: String,
    pub actions: Vec<PlannedRecoveryAction>,
    pub target_mode: Option<OperationalMode>,
    pub level: RecoveryLevel,
    pub risk: String,
}

/// Recovery policy extracted from declarations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryPolicySpec {
    pub name: String,
    pub triggers: Vec<(String, Vec<String>)>,
}

/// Safety-validated recovery action ready for execution.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SafeRecoveryAction {
    pub action: PlannedRecoveryAction,
    pub safety_validation: ValidationGateResult,
    pub hardware_verification: ValidationGateResult,
    pub capability_verification: ValidationGateResult,
    pub readiness_validation: ValidationGateResult,
    pub approved: bool,
}

/// Result of a validation gate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ValidationGateResult {
    pub gate: String,
    pub passed: bool,
    pub message: String,
}

/// Outcome of executing a recovery plan.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryResult {
    pub plan: String,
    pub status: RecoveryStatus,
    pub executed_actions: Vec<String>,
    pub failed_actions: Vec<String>,
    pub verification_outcome: String,
    pub evidence: RecoveryEvidence,
}

/// Evidence collected during recovery.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryEvidence {
    pub failure: String,
    pub diagnosis: String,
    pub plan: String,
    pub safety_validation: String,
    pub recovery_actions: Vec<String>,
    pub outcome: String,
    pub operator_approval: Option<String>,
    pub verification: String,
}

/// Recovery audit record for provenance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryAuditRecord {
    pub detected_failure: String,
    pub diagnosis: String,
    pub chosen_recovery: String,
    pub safety_validation_result: String,
    pub recovery_outcome: String,
    pub operator_approval: Option<String>,
    pub verification_outcome: String,
    pub timestamp_hint: String,
}

/// Traceability chain for recovery workflow.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryTraceChain {
    pub failure: String,
    pub diagnosis: String,
    pub recovery_plan: String,
    pub safety_validation: String,
    pub recovery_action: String,
    pub outcome: String,
    pub evidence: String,
}

/// Recovery readiness assessment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryReadiness {
    pub recovery_ready: bool,
    pub risk: String,
    pub readiness_score: u32,
    pub blockers: Vec<String>,
}

/// Fleet-level recovery plan.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FleetRecoveryPlan {
    pub fleet: String,
    pub failed_robot: Option<String>,
    pub actions: Vec<String>,
    pub risk: String,
}

/// Knowledge base entry for recovery patterns (no auto-modification).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryKnowledgeEntry {
    pub failure_pattern: String,
    pub recovery_pattern: String,
    pub success_rate: f64,
    pub recommendation: String,
}

/// Recovery knowledge base for self-improvement recommendations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Default)]
pub struct RecoveryKnowledgeBase {
    pub entries: Vec<RecoveryKnowledgeEntry>,
}

/// Recovery assurance metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryAssuranceMetrics {
    pub recovery_evidence: Vec<RecoveryEvidence>,
    pub recovery_readiness: RecoveryReadiness,
    pub success_rate: f64,
    pub traceability: Vec<RecoveryTraceChain>,
}

/// Composite recovery framework report.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryReport {
    pub policies: Vec<RecoveryPolicySpec>,
    pub plans: Vec<RecoveryPlan>,
    pub safe_actions: Vec<SafeRecoveryAction>,
    pub results: Vec<RecoveryResult>,
    pub audit: Vec<RecoveryAuditRecord>,
    pub readiness: RecoveryReadiness,
    pub assurance: RecoveryAssuranceMetrics,
    pub fleet_plans: Vec<FleetRecoveryPlan>,
    pub knowledge: RecoveryKnowledgeBase,
    pub passed: bool,
}

/// Input context for recovery planning.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryContext {
    pub issue: String,
    pub diagnosis: Option<String>,
    pub classification: Option<FailureClassification>,
    pub level: RecoveryLevel,
}

/// Planner that generates recovery plans from failures and diagnoses.
pub struct RecoveryPlanner;

impl RecoveryPlanner {
    /// Generate a recovery plan for the given context and program.
    pub fn plan(program: &Program, context: &RecoveryContext) -> RecoveryPlan {
        // Description:
        //     Plan.
        //
        // Inputs:
        //     progra: &Program
        //         Caller-supplied progra.
        //     contex: &RecoveryContext
        //         Caller-supplied contex.
        //
        // Outputs:
        //     result: RecoveryPlan
        //         Return value from `plan`.
        //
        // Example:

        //     let result = spanda_assurance::recovery::plan(progra, contex);

        let classification = context
            .classification
            .unwrap_or_else(|| classify_failure(&context.issue));
        let diagnosis = context
            .diagnosis
            .clone()
            .unwrap_or_else(|| infer_diagnosis(&context.issue, classification));
        let policies = extract_recovery_policies(program);
        let mut actions = actions_from_policies(&policies, &context.issue);
        if actions.is_empty() {
            let knowledge = load_merged_recovery_knowledge(program);
            if let Some(entry) = best_knowledge_entry(&knowledge, &context.issue) {
                actions.push(parse_action_text(&entry.recovery_pattern, 1));
            }
        }
        if actions.is_empty() {
            actions = default_actions_for_classification(classification, &context.issue);
        }
        let target_mode = infer_target_mode(&actions);
        let risk = assess_plan_risk(&actions);
        let level = context.level;
        RecoveryPlan {
            name: format!("recovery_{}", sanitize_name(&context.issue)),
            failure: context.issue.clone(),
            classification,
            diagnosis,
            actions,
            target_mode,
            level,
            risk,
        }
    }
}

/// Classify a failure description into a failure category.
pub fn classify_failure(issue: &str) -> FailureClassification {
    // Description:
    //     Classify failure.
    //
    // Inputs:
    //     issue: &str
    //         Caller-supplied issue.
    //
    // Outputs:
    //     result: FailureClassification
    //         Return value from `classify_failure`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::classify_failure(issue);

    let lower = issue.to_lowercase();
    if lower.contains("gps")
        || lower.contains("camera")
        || lower.contains("lidar")
        || lower.contains("sensor")
        || lower.contains("imu")
    {
        FailureClassification::SensorFailure
    } else if lower.contains("actuator") || lower.contains("motor") || lower.contains("drive") {
        FailureClassification::ActuatorFailure
    } else if lower.contains("lte")
        || lower.contains("wifi")
        || lower.contains("connect")
        || lower.contains("network")
    {
        FailureClassification::ConnectivityFailure
    } else if lower.contains("provider") {
        FailureClassification::ProviderFailure
    } else if lower.contains("package") {
        FailureClassification::PackageFailure
    } else if lower.contains("mission") {
        FailureClassification::MissionFailure
    } else if lower.contains("health") || lower.contains("degrad") {
        FailureClassification::HealthDegradation
    } else if lower.contains("fleet") {
        FailureClassification::FleetFailure
    } else if lower.contains("swarm") {
        FailureClassification::SwarmFailure
    } else if lower.contains("safety") || lower.contains("kill") {
        FailureClassification::SafetyFailure
    } else {
        FailureClassification::Unknown
    }
}

/// Extract recovery policies from program declarations.
pub fn extract_recovery_policies(program: &Program) -> Vec<RecoveryPolicySpec> {
    // Description:
    //     Extract recovery policies.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //
    // Outputs:
    //     result: Vec<RecoveryPolicySpec>
    //         Return value from `extract_recovery_policies`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::extract_recovery_policies(progra);

    let Program::Program {
        recovery_policies,
        mitigations,
        ..
    } = program;

    let mut specs: Vec<RecoveryPolicySpec> = recovery_policies
        .iter()
        .map(|decl| {
            let RecoveryPolicyDecl::RecoveryPolicyDecl { name, branches, .. } = decl;
            RecoveryPolicySpec {
                name: name.clone(),
                triggers: branches
                    .iter()
                    .map(|b| (b.condition.clone(), b.actions.clone()))
                    .collect(),
            }
        })
        .collect();

    for mit in mitigations {
        let MitigationDecl::MitigationDecl { name, branches, .. } = mit;
        specs.push(RecoveryPolicySpec {
            name: name.clone(),
            triggers: branches
                .iter()
                .map(|b| (b.condition.clone(), b.actions.clone()))
                .collect(),
        });
    }

    specs
}

/// Map a runtime fault or health event to a recovery policy issue key.
pub fn issue_to_recovery_issue(event: &str) -> Option<String> {
    // Normalize hardware and health events into recovery policy condition keys.
    //
    // Parameters:
    // - `event` — runtime fault, health label, or hardware event name
    //
    // Returns:
    // Issue key such as `gps.failed`, or None when unmappable.
    //
    // Options:
    // None.
    //
    // Example:
    // assert_eq!(issue_to_recovery_issue("GPSFailure").as_deref(), Some("gps.failed"));

    let lower = event.to_ascii_lowercase();
    if lower.contains("gps") {
        return Some("gps.failed".into());
    }
    if lower.contains("lidar") {
        return Some("lidar.failed".into());
    }
    if lower.contains("camera") {
        return Some("camera.failed".into());
    }
    if lower.contains("connectivity") || lower.contains("comm") || lower.contains("network") {
        return Some("connectivity.lost".into());
    }
    if lower.contains("battery") {
        return Some("battery.critical".into());
    }
    if lower.contains("robothealthcritical") || lower.contains("robot.failed") {
        return Some("robot.failed".into());
    }
    if lower.contains("degraded") {
        return Some("robot.degraded".into());
    }
    if lower.ends_with("failure") {
        let stem = lower.trim_end_matches("failure");
        if !stem.is_empty() {
            return Some(format!("{}.failed", stem));
        }
    }
    if lower.contains("failed") || lower.contains("fault") {
        return Some(lower.replace('_', "."));
    }
    None
}

/// Return true when the program declares `recovery_policy` for the issue.
pub fn program_has_recovery_for_issue(program: &Program, issue: &str) -> bool {
    // Check recovery policy branches against a normalized issue key.
    //
    // Parameters:
    // - `program` — parsed `.sd` program
    // - `issue` — recovery issue key (for example `gps.failed`)
    //
    // Returns:
    // True when a policy branch matches the issue.
    //
    // Options:
    // None.
    //
    // Example:
    // let covered = program_has_recovery_for_issue(&program, "gps.failed");

    let lower = issue.to_ascii_lowercase();
    extract_recovery_policies(program).iter().any(|policy| {
        policy
            .triggers
            .iter()
            .any(|(condition, _)| condition_matches(&lower, &condition.to_ascii_lowercase()))
    })
}

/// Validate recovery actions through safety, hardware, capability, and readiness gates.
pub fn validate_recovery_plan(program: &Program, plan: &RecoveryPlan) -> Vec<SafeRecoveryAction> {
    // Description:
    //     Validate recovery plan.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     plan: &RecoveryPlan
    //         Caller-supplied plan.
    //
    // Outputs:
    //     result: Vec<SafeRecoveryAction>
    //         Return value from `validate_recovery_plan`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::validate_recovery_plan(progra, plan);

    let options = ReadinessOptions {
        target: default_deploy_target(program),
        ..Default::default()
    };
    let readiness = evaluate_readiness(program, &options);
    let hw_options = VerifyOptions {
        target: default_deploy_target(program),
        ..Default::default()
    };
    let hw = verify_program_compatibility(program, &hw_options);
    let caps = infer_robot_capabilities(program);
    let approvals = verify_approvals(program);

    plan.actions
        .iter()
        .map(|action| {
            let safety = ValidationGateResult {
                gate: "Safety Validation".into(),
                passed: !action.description.to_lowercase().contains("unsafe")
                    && !plan
                        .classification
                        .eq(&FailureClassification::SafetyFailure),
                message: if action.description.to_lowercase().contains("unsafe") {
                    "Unsafe action blocked".into()
                } else {
                    "PASS".into()
                },
            };
            let hardware = ValidationGateResult {
                gate: "Hardware Verification".into(),
                passed: hw.compatible,
                message: if hw.compatible {
                    "PASS".into()
                } else {
                    "Hardware incompatible".into()
                },
            };
            let capability = ValidationGateResult {
                gate: "Capability Verification".into(),
                passed: !caps.is_empty()
                    || plan.classification == FailureClassification::ConnectivityFailure,
                message: if caps.is_empty() {
                    "No capabilities inferred".into()
                } else {
                    "PASS".into()
                },
            };
            let readiness_gate = ValidationGateResult {
                gate: "Readiness Validation".into(),
                passed: readiness.mission_ready
                    || (action.risk.eq_ignore_ascii_case("low") && readiness.score.total > 0)
                    || plan.level <= RecoveryLevel::Level1Recommend,
                message: if readiness.mission_ready {
                    "PASS".into()
                } else if action.risk.eq_ignore_ascii_case("low") && readiness.score.total > 0 {
                    format!("PASS (low-risk, score {}/100)", readiness.score.total)
                } else {
                    format!("Readiness score {}/100", readiness.score.total)
                },
            };
            let requires_approval = action.requires_approval
                || plan.level == RecoveryLevel::Level4HumanApproval
                || action.risk.eq_ignore_ascii_case("high")
                || action.risk.eq_ignore_ascii_case("critical");
            let approved = if requires_approval {
                approvals.compatible
                    && approvals.rows.iter().any(|r| {
                        r.approval_path_exists
                            && (r.actor == "Operator" || r.actor.contains("Operator"))
                    })
            } else {
                true
            };
            SafeRecoveryAction {
                action: action.clone(),
                safety_validation: safety,
                hardware_verification: hardware,
                capability_verification: capability,
                readiness_validation: readiness_gate,
                approved,
            }
        })
        .collect()
}

/// Evaluate whether recovery can be attempted.
pub fn evaluate_recovery_readiness(program: &Program, plan: &RecoveryPlan) -> RecoveryReadiness {
    // Description:
    //     Evaluate recovery readiness.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     plan: &RecoveryPlan
    //         Caller-supplied plan.
    //
    // Outputs:
    //     result: RecoveryReadiness
    //         Return value from `evaluate_recovery_readiness`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::evaluate_recovery_readiness(progra, plan);

    let options = ReadinessOptions {
        target: default_deploy_target(program),
        ..Default::default()
    };
    let readiness = evaluate_readiness(program, &options);
    let safe_actions = validate_recovery_plan(program, plan);
    let all_gates_pass = safe_actions.iter().all(|a| {
        a.safety_validation.passed
            && a.hardware_verification.passed
            && a.capability_verification.passed
            && a.readiness_validation.passed
    });
    let mut blockers = Vec::new();
    if !all_gates_pass {
        blockers.push("One or more validation gates failed".into());
    }
    for action in &safe_actions {
        if action.action.requires_approval && !action.approved {
            blockers.push(format!(
                "Operator approval required for: {}",
                action.action.description
            ));
        }
    }
    let risk = plan.risk.clone();
    RecoveryReadiness {
        recovery_ready: all_gates_pass && blockers.is_empty(),
        risk,
        readiness_score: readiness.score.total,
        blockers,
    }
}

/// Execute recovery plan (static simulation — no uncontrolled autonomous behavior).
pub fn execute_recovery_plan(program: &Program, plan: &RecoveryPlan) -> RecoveryResult {
    // Description:
    //     Execute recovery plan.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     plan: &RecoveryPlan
    //         Caller-supplied plan.
    //
    // Outputs:
    //     result: RecoveryResult
    //         Return value from `execute_recovery_plan`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::execute_recovery_plan(progra, plan);

    let safe_actions = validate_recovery_plan(program, plan);
    let mut executed = Vec::new();
    let mut failed = Vec::new();

    for safe in &safe_actions {
        let gates_ok = safe.safety_validation.passed
            && safe.hardware_verification.passed
            && safe.capability_verification.passed
            && safe.readiness_validation.passed;
        if !gates_ok {
            failed.push(safe.action.description.clone());
            continue;
        }
        if safe.action.requires_approval && !safe.approved {
            failed.push(format!("{} (approval required)", safe.action.description));
            continue;
        }
        executed.push(safe.action.description.clone());
    }

    let status = if failed.is_empty() && !executed.is_empty() {
        RecoveryStatus::Success
    } else if !executed.is_empty() {
        RecoveryStatus::PartialSuccess
    } else if safe_actions.iter().any(|a| !a.safety_validation.passed) {
        RecoveryStatus::Unsafe
    } else {
        RecoveryStatus::Failed
    };

    let evidence = RecoveryEvidence {
        failure: plan.failure.clone(),
        diagnosis: plan.diagnosis.clone(),
        plan: plan.name.clone(),
        safety_validation: if safe_actions.iter().all(|a| a.safety_validation.passed) {
            "PASS".into()
        } else {
            "FAIL".into()
        },
        recovery_actions: executed.clone(),
        outcome: format!("{status:?}"),
        operator_approval: if plan.level == RecoveryLevel::Level4HumanApproval {
            Some("Operator".into())
        } else {
            None
        },
        verification: if status == RecoveryStatus::Success {
            "Recovery verified".into()
        } else {
            "Recovery incomplete".into()
        },
    };

    RecoveryResult {
        plan: plan.name.clone(),
        status,
        executed_actions: executed,
        failed_actions: failed,
        verification_outcome: evidence.verification.clone(),
        evidence,
    }
}

/// Build recovery audit records from results.
pub fn build_recovery_audit(results: &[RecoveryResult]) -> Vec<RecoveryAuditRecord> {
    // Description:
    //     Build recovery audit.
    //
    // Inputs:
    //     results: &[RecoveryResult]
    //         Caller-supplied results.
    //
    // Outputs:
    //     result: Vec<RecoveryAuditRecord>
    //         Return value from `build_recovery_audit`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::build_recovery_audit(results);

    results
        .iter()
        .map(|r| RecoveryAuditRecord {
            detected_failure: r.evidence.failure.clone(),
            diagnosis: r.evidence.diagnosis.clone(),
            chosen_recovery: r.evidence.plan.clone(),
            safety_validation_result: r.evidence.safety_validation.clone(),
            recovery_outcome: format!("{:?}", r.status),
            operator_approval: r.evidence.operator_approval.clone(),
            verification_outcome: r.verification_outcome.clone(),
            timestamp_hint: "static-analysis".into(),
        })
        .collect()
}

/// Build traceability chain from recovery results.
pub fn build_recovery_traceability(results: &[RecoveryResult]) -> Vec<RecoveryTraceChain> {
    // Description:
    //     Build recovery traceability.
    //
    // Inputs:
    //     results: &[RecoveryResult]
    //         Caller-supplied results.
    //
    // Outputs:
    //     result: Vec<RecoveryTraceChain>
    //         Return value from `build_recovery_traceability`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::build_recovery_traceability(results);

    results
        .iter()
        .map(|r| RecoveryTraceChain {
            failure: r.evidence.failure.clone(),
            diagnosis: r.evidence.diagnosis.clone(),
            recovery_plan: r.evidence.plan.clone(),
            safety_validation: r.evidence.safety_validation.clone(),
            recovery_action: r.executed_actions.join("; "),
            outcome: format!("{:?}", r.status),
            evidence: r.evidence.verification.clone(),
        })
        .collect()
}

/// Plan fleet recovery actions.
pub fn plan_fleet_recovery(program: &Program, failed_robot: &str) -> Vec<FleetRecoveryPlan> {
    // Description:
    //     Plan fleet recovery.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     failed_robo: &str
    //         Caller-supplied failed robo.
    //
    // Outputs:
    //     result: Vec<FleetRecoveryPlan>
    //         Return value from `plan_fleet_recovery`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::plan_fleet_recovery(progra, failed_robo);

    let Program::Program { fleets, .. } = program;
    fleets
        .iter()
        .map(|f| {
            let spanda_ast::robotics_decl::FleetDecl::FleetDecl { name, .. } = f;
            FleetRecoveryPlan {
                fleet: name.clone(),
                failed_robot: Some(failed_robot.into()),
                actions: vec![
                    format!("Replace failed robot {failed_robot}"),
                    "Reassign mission to backup robot".into(),
                    "Redistribute tasks across fleet".into(),
                    "Promote backup coordinator".into(),
                ],
                risk: "Medium".into(),
            }
        })
        .collect()
}

/// Build recovery knowledge base from historical patterns.
pub fn build_recovery_knowledge(program: &Program) -> RecoveryKnowledgeBase {
    // Description:
    //     Build recovery knowledge.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //
    // Outputs:
    //     result: RecoveryKnowledgeBase
    //         Return value from `build_recovery_knowledge`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::build_recovery_knowledge(progra);

    let failure_report = analyze_failure(program);
    let entries: Vec<RecoveryKnowledgeEntry> = failure_report
        .impacts
        .iter()
        .map(|impact| RecoveryKnowledgeEntry {
            failure_pattern: impact.component.clone(),
            recovery_pattern: impact.mitigation.clone(),
            success_rate: match impact.severity.as_str() {
                "Critical" => 0.6,
                "High" => 0.75,
                "Medium" => 0.85,
                _ => 0.9,
            },
            recommendation: format!("On {} failure: {}", impact.component, impact.mitigation),
        })
        .collect();
    RecoveryKnowledgeBase { entries }
}

/// Default on-disk path for the recovery knowledge store.
pub fn default_knowledge_store_path() -> std::path::PathBuf {
    // Description:
    //     Default knowledge store path.
    //
    // Inputs:
    //     None.
    //
    // Outputs:
    //     result: std::path::PathBuf
    //         Return value from `default_knowledge_store_path`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::default_knowledge_store_path();

    std::path::PathBuf::from(".spanda/recovery_knowledge.json")
}

/// Load persisted recovery knowledge from disk.
pub fn load_recovery_knowledge_store(path: &std::path::Path) -> RecoveryKnowledgeBase {
    // Description:
    //     Load recovery knowledge store.
    //
    // Inputs:
    //     path: &std::path::Path
    //         Caller-supplied path.
    //
    // Outputs:
    //     result: RecoveryKnowledgeBase
    //         Return value from `load_recovery_knowledge_store`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::load_recovery_knowledge_store(path);

    std::fs::read_to_string(path)
        .ok()
        .and_then(|content| serde_json::from_str(&content).ok())
        .unwrap_or_default()
}

/// Persist recovery knowledge to disk.
pub fn save_recovery_knowledge_store(
    path: &std::path::Path,
    kb: &RecoveryKnowledgeBase,
) -> std::io::Result<()> {
    // Description:
    //     Save recovery knowledge store.
    //
    // Inputs:
    //     path: &std::path::Path
    //         Caller-supplied path.
    //     kb: &RecoveryKnowledgeBase
    //         Caller-supplied kb.
    //
    // Outputs:
    //     result: std::io::Result<()>
    //         Return value from `save_recovery_knowledge_store`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::save_recovery_knowledge_store(path, kb);

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, serde_json::to_string_pretty(kb).unwrap_or_default())
}

/// Update knowledge base from a recovery outcome (recommendations only).
pub fn record_recovery_outcome(kb: &mut RecoveryKnowledgeBase, result: &RecoveryResult) {
    // Description:
    //     Record recovery outcome.
    //
    // Inputs:
    //     kb: &mut RecoveryKnowledgeBase
    //         Caller-supplied kb.
    //     resul: &RecoveryResult
    //         Caller-supplied resul.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_assurance::recovery::record_recovery_outcome(kb, resul);

    let success = matches!(
        result.status,
        RecoveryStatus::Success | RecoveryStatus::PartialSuccess
    );
    let pattern = result.evidence.failure.clone();
    for action in &result.executed_actions {
        if let Some(entry) = kb.entries.iter_mut().find(|e| e.failure_pattern == pattern) {
            entry.success_rate = if success {
                (entry.success_rate * 0.85) + 0.15
            } else {
                entry.success_rate * 0.85
            };
            entry.recovery_pattern.clone_from(action);
            entry.recommendation = format!("On {pattern} failure: {action}");
        } else {
            kb.entries.push(RecoveryKnowledgeEntry {
                failure_pattern: pattern.clone(),
                recovery_pattern: action.clone(),
                success_rate: if success { 1.0 } else { 0.0 },
                recommendation: format!("On {pattern} failure: {action}"),
            });
        }
    }
}

/// Merge static and persisted recovery knowledge.
pub fn merge_recovery_knowledge(
    program: &Program,
    persisted: &RecoveryKnowledgeBase,
) -> RecoveryKnowledgeBase {
    // Description:
    //     Merge recovery knowledge.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     persisted: &RecoveryKnowledgeBase
    //         Caller-supplied persisted.
    //
    // Outputs:
    //     result: RecoveryKnowledgeBase
    //         Return value from `merge_recovery_knowledge`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::merge_recovery_knowledge(progra, persisted);

    let mut kb = build_recovery_knowledge(program);
    for entry in &persisted.entries {
        if let Some(existing) = kb
            .entries
            .iter_mut()
            .find(|e| e.failure_pattern == entry.failure_pattern)
        {
            existing.success_rate = (existing.success_rate + entry.success_rate) / 2.0;
            if entry.success_rate > existing.success_rate {
                existing
                    .recovery_pattern
                    .clone_from(&entry.recovery_pattern);
                existing.recommendation.clone_from(&entry.recommendation);
            }
        } else {
            kb.entries.push(entry.clone());
        }
    }
    kb
}

/// Best knowledge entry for a failure issue by success rate.
pub fn best_knowledge_entry<'a>(
    kb: &'a RecoveryKnowledgeBase,
    issue: &str,
) -> Option<&'a RecoveryKnowledgeEntry> {
    let lower = issue.to_lowercase();
    kb.entries
        .iter()
        .filter(|e| {
            lower.contains(&e.failure_pattern.to_lowercase())
                || e.failure_pattern.to_lowercase().contains(&lower)
        })
        .max_by(|a, b| {
            a.success_rate
                .partial_cmp(&b.success_rate)
                .unwrap_or(std::cmp::Ordering::Equal)
        })
}

/// Load merged recovery knowledge for a program (static + persisted store).
pub fn load_merged_recovery_knowledge(program: &Program) -> RecoveryKnowledgeBase {
    // Description:
    //     Load merged recovery knowledge.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //
    // Outputs:
    //     result: RecoveryKnowledgeBase
    //         Return value from `load_merged_recovery_knowledge`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::load_merged_recovery_knowledge(progra);

    let persisted = load_recovery_knowledge_store(&default_knowledge_store_path());
    merge_recovery_knowledge(program, &persisted)
}

/// Simulate failure injection for recovery testing.
pub fn simulate_failure_recovery(
    program: &Program,
    failure_kind: &str,
    device_registry: Option<&spanda_config::DeviceRegistry>,
) -> RecoveryReport {
    // Description:
    //     Simulate failure recovery.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     failure_kind: &str
    //         Caller-supplied failure kind.
    //
    // Outputs:
    //     result: RecoveryReport
    //         Return value from `simulate_failure_recovery`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::simulate_failure_recovery(progra, failure_kind);

    let issue = issue_to_recovery_issue(failure_kind)
        .unwrap_or_else(|| format!("{failure_kind}.failed"));
    let classification = classify_failure(failure_kind);
    let context = RecoveryContext {
        issue: issue.clone(),
        diagnosis: Some(infer_diagnosis(&issue, classification)),
        classification: Some(classification),
        level: RecoveryLevel::Level3AutomaticWithValidation,
    };
    evaluate_recovery(program, Some(&context), device_registry)
}

/// Resolve a failed device id from a recovery issue string and registry.
fn resolve_failed_device_id(
    registry: &spanda_config::DeviceRegistry,
    issue: &str,
) -> Option<String> {
    let issue_lower = issue.to_lowercase();
    for device in &registry.devices {
        if issue_lower.contains(&device.id.to_lowercase()) {
            return Some(device.id.clone());
        }
    }
    for device in &registry.devices {
        if let Some(ref logical) = device.logical_name {
            if issue_lower.contains(&logical.to_lowercase()) {
                return Some(device.id.clone());
            }
        }
    }
    None
}

/// Run full recovery framework analysis on a program.
pub fn evaluate_recovery(
    program: &Program,
    context: Option<&RecoveryContext>,
    device_registry: Option<&spanda_config::DeviceRegistry>,
) -> RecoveryReport {
    // Description:
    //     Evaluate recovery.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     contex: Option<&RecoveryContext>
    //         Caller-supplied contex.
    //
    // Outputs:
    //     result: RecoveryReport
    //         Return value from `evaluate_recovery`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::evaluate_recovery(progra, contex);

    let policies = extract_recovery_policies(program);
    let contexts: Vec<RecoveryContext> = if let Some(ctx) = context {
        vec![ctx.clone()]
    } else {
        default_recovery_contexts(program)
    };

    let plans: Vec<RecoveryPlan> = contexts
        .iter()
        .map(|ctx| {
            let mut plan = RecoveryPlanner::plan(program, ctx);
            if let Some(registry) = device_registry {
                if let Some(device_id) = resolve_failed_device_id(registry, &ctx.issue) {
                    enrich_recovery_plan_with_failover(&mut plan, registry, &device_id);
                }
            }
            plan
        })
        .collect();

    let safe_actions: Vec<SafeRecoveryAction> = plans
        .iter()
        .flat_map(|plan| validate_recovery_plan(program, plan))
        .collect();

    let results: Vec<RecoveryResult> = plans
        .iter()
        .map(|plan| execute_recovery_plan(program, plan))
        .collect();

    let audit = build_recovery_audit(&results);
    let traceability = build_recovery_traceability(&results);
    let readiness = plans
        .first()
        .map(|p| evaluate_recovery_readiness(program, p))
        .unwrap_or(RecoveryReadiness {
            recovery_ready: false,
            risk: "Unknown".into(),
            readiness_score: 0,
            blockers: vec!["No recovery plan".into()],
        });

    let success_count = results
        .iter()
        .filter(|r| r.status == RecoveryStatus::Success)
        .count();
    let success_rate = if results.is_empty() {
        0.0
    } else {
        success_count as f64 / results.len() as f64
    };

    let assurance = RecoveryAssuranceMetrics {
        recovery_evidence: results.iter().map(|r| r.evidence.clone()).collect(),
        recovery_readiness: readiness.clone(),
        success_rate,
        traceability,
    };

    let fleet_plans = plan_fleet_recovery(program, "Rover");
    let knowledge = load_merged_recovery_knowledge(program);
    let mode_issues = validate_modes(program);

    let passed = !plans.is_empty()
        && results
            .iter()
            .all(|r| r.status != RecoveryStatus::Unsafe && r.status != RecoveryStatus::Failed)
        && mode_issues.is_empty();

    RecoveryReport {
        policies,
        plans,
        safe_actions,
        results,
        audit,
        readiness,
        assurance,
        fleet_plans,
        knowledge,
        passed,
    }
}

/// Integrate recovery with diagnosis report.
pub fn recovery_from_diagnosis(program: &Program, diagnosis: &DiagnosisReport) -> RecoveryReport {
    // Description:
    //     Recovery from diagnosis.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //     diagnosis: &DiagnosisReport
    //         Caller-supplied diagnosis.
    //
    // Outputs:
    //     result: RecoveryReport
    //         Return value from `recovery_from_diagnosis`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::recovery_from_diagnosis(progra, diagnosis);

    let mut contexts = Vec::new();
    for d in &diagnosis.static_diagnoses {
        for rc in &d.root_causes {
            contexts.push(RecoveryContext {
                issue: rc.description.clone(),
                diagnosis: Some(d.subject.clone()),
                classification: Some(classify_failure(&rc.description)),
                level: RecoveryLevel::Level2AutomaticLowRisk,
            });
        }
    }
    if let Some(trace) = &diagnosis.trace_diagnosis {
        contexts.push(RecoveryContext {
            issue: trace.root_cause.clone(),
            diagnosis: Some(trace.root_cause.clone()),
            classification: Some(classify_failure(&trace.root_cause)),
            level: RecoveryLevel::Level2AutomaticLowRisk,
        });
    }
    if contexts.is_empty() {
        return evaluate_recovery(program, None, None);
    }
    let policies = extract_recovery_policies(program);
    let plans: Vec<RecoveryPlan> = contexts
        .iter()
        .map(|ctx| RecoveryPlanner::plan(program, ctx))
        .collect();
    let results: Vec<RecoveryResult> = plans
        .iter()
        .map(|plan| execute_recovery_plan(program, plan))
        .collect();
    let safe_actions: Vec<SafeRecoveryAction> = plans
        .iter()
        .flat_map(|plan| validate_recovery_plan(program, plan))
        .collect();
    let audit = build_recovery_audit(&results);
    let traceability = build_recovery_traceability(&results);
    let readiness = plans
        .first()
        .map(|p| evaluate_recovery_readiness(program, p))
        .unwrap_or(RecoveryReadiness {
            recovery_ready: false,
            risk: "Unknown".into(),
            readiness_score: 0,
            blockers: vec!["No recovery plan".into()],
        });
    let success_count = results
        .iter()
        .filter(|r| r.status == RecoveryStatus::Success)
        .count();
    let success_rate = if results.is_empty() {
        0.0
    } else {
        success_count as f64 / results.len() as f64
    };
    let recovery_evidence: Vec<RecoveryEvidence> =
        results.iter().map(|r| r.evidence.clone()).collect();
    let passed = !results.is_empty() && results.iter().all(|r| r.status != RecoveryStatus::Unsafe);
    RecoveryReport {
        policies,
        plans,
        safe_actions,
        results,
        audit,
        readiness: readiness.clone(),
        assurance: RecoveryAssuranceMetrics {
            recovery_evidence,
            recovery_readiness: readiness,
            success_rate,
            traceability,
        },
        fleet_plans: plan_fleet_recovery(program, "Rover"),
        knowledge: load_merged_recovery_knowledge(program),
        passed,
    }
}

/// Extend failure analysis with recovery plan details.
pub fn analyze_failure_with_recovery(program: &Program) -> FailureAnalysisWithRecovery {
    // Description:
    //     Analyze failure with recovery.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //
    // Outputs:
    //     result: FailureAnalysisWithRecovery
    //         Return value from `analyze_failure_with_recovery`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::analyze_failure_with_recovery(progra);

    let failure = analyze_failure(program);
    let recovery = evaluate_recovery(program, None, None);
    FailureAnalysisWithRecovery {
        failure,
        recovery_plans: recovery.plans,
        risk: recovery.readiness.risk.clone(),
    }
}

/// Failure analysis enriched with recovery planning.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FailureAnalysisWithRecovery {
    pub failure: FailureAnalysisReport,
    pub recovery_plans: Vec<RecoveryPlan>,
    pub risk: String,
}

fn default_recovery_contexts(program: &Program) -> Vec<RecoveryContext> {
    // Description:
    //     Default recovery contexts.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //
    // Outputs:
    //     result: Vec<RecoveryContext>
    //         Return value from `default_recovery_contexts`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::default_recovery_contexts(progra);

    let policies = extract_recovery_policies(program);
    if policies.is_empty() {
        return vec![RecoveryContext {
            issue: "gps.failed".into(),
            diagnosis: Some("Satellite lock lost".into()),
            classification: Some(FailureClassification::SensorFailure),
            level: RecoveryLevel::Level2AutomaticLowRisk,
        }];
    }
    policies
        .iter()
        .flat_map(|p| {
            p.triggers.iter().map(|(cond, _)| RecoveryContext {
                issue: cond.clone(),
                diagnosis: None,
                classification: None,
                level: RecoveryLevel::Level2AutomaticLowRisk,
            })
        })
        .collect()
}

fn infer_diagnosis(issue: &str, classification: FailureClassification) -> String {
    // Description:
    //     Infer diagnosis.
    //
    // Inputs:
    //     issue: &str
    //         Caller-supplied issue.
    //     classification: FailureClassification
    //         Caller-supplied classification.
    //
    // Outputs:
    //     result: String
    //         Return value from `infer_diagnosis`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::infer_diagnosis(issue, classification);

    let lower = issue.to_lowercase();
    if lower.contains("gps") {
        "Satellite lock lost".into()
    } else if lower.contains("lidar") {
        "Lidar point cloud unavailable".into()
    } else if lower.contains("lte") || lower.contains("wifi") {
        "Connectivity link down".into()
    } else {
        match classification {
            FailureClassification::SensorFailure => "Sensor reading unavailable".into(),
            FailureClassification::ActuatorFailure => "Actuator response timeout".into(),
            FailureClassification::ConnectivityFailure => "Network unreachable".into(),
            FailureClassification::ProviderFailure => "Provider backend unavailable".into(),
            FailureClassification::PackageFailure => "Package load failure".into(),
            FailureClassification::MissionFailure => "Mission constraint violated".into(),
            FailureClassification::HealthDegradation => "Health check threshold exceeded".into(),
            FailureClassification::FleetFailure => "Fleet member unresponsive".into(),
            FailureClassification::SwarmFailure => "Swarm coordination lost".into(),
            FailureClassification::SafetyFailure => "Safety rule violation detected".into(),
            FailureClassification::Unknown => "Root cause under investigation".into(),
        }
    }
}

fn actions_from_policies(
    policies: &[RecoveryPolicySpec],
    issue: &str,
) -> Vec<PlannedRecoveryAction> {
    // Description:
    //     Actions from policies.
    //
    // Inputs:
    //     policies: &[RecoveryPolicySpec]
    //         Caller-supplied policies.
    //     issue: &str
    //         Caller-supplied issue.
    //
    // Outputs:
    //     result: Vec<PlannedRecoveryAction>
    //         Return value from `actions_from_policies`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::actions_from_policies(policies, issue);

    let lower = issue.to_lowercase();
    let mut actions = Vec::new();
    let mut order = 0u32;
    for policy in policies {
        for (condition, policy_actions) in &policy.triggers {
            if lower.contains(&condition.to_lowercase())
                || condition_matches(&lower, &condition.to_lowercase())
            {
                for action_text in policy_actions {
                    order += 1;
                    actions.push(parse_action_text(action_text, order));
                }
            }
        }
    }
    actions
}

fn condition_matches(issue: &str, condition: &str) -> bool {
    // Description:
    //     Condition matches.
    //
    // Inputs:
    //     issue: &str
    //         Caller-supplied issue.
    //     condition: &str
    //         Caller-supplied condition.
    //
    // Outputs:
    //     result: bool
    //         Return value from `condition_matches`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::condition_matches(issue, condition);

    let parts: Vec<&str> = condition.split('.').collect();
    parts.iter().all(|p| issue.contains(p))
}

fn parse_action_text(text: &str, order: u32) -> PlannedRecoveryAction {
    // Description:
    //     Parse action text.
    //
    // Inputs:
    //     ex: &str
    //         Caller-supplied ex.
    //     order: u32
    //         Caller-supplied order.
    //
    // Outputs:
    //     result: PlannedRecoveryAction
    //         Return value from `parse_action_text`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::parse_action_text(ex, order);

    let lower = text.to_lowercase();
    let (strategy, correction) = if lower.contains("visual_odometry") || lower.contains("switch_to")
    {
        (
            RecoveryStrategy::Failover,
            Some(SelfCorrectionAction::Custom {
                action: text.into(),
            }),
        )
    } else if lower.contains("reduce_speed") {
        (
            RecoveryStrategy::SpeedReduction,
            Some(SelfCorrectionAction::ReduceSpeed {
                limit: text.replace("reduce_speed", "").trim().into(),
            }),
        )
    } else if lower.contains("degraded") {
        (
            RecoveryStrategy::DegradedMode,
            Some(SelfCorrectionAction::EnterMode {
                mode: "DegradedMode".into(),
            }),
        )
    } else if lower.contains("safe_mode") || lower.contains("safe mode") {
        (
            RecoveryStrategy::DegradedMode,
            Some(SelfCorrectionAction::EnterMode {
                mode: "SafeMode".into(),
            }),
        )
    } else if lower.contains("reconnect") {
        (
            RecoveryStrategy::ProviderReconnect,
            Some(SelfCorrectionAction::ReconnectProvider {
                provider: "default".into(),
            }),
        )
    } else if lower.contains("pause") {
        (
            RecoveryStrategy::MissionPause,
            Some(SelfCorrectionAction::PauseMission),
        )
    } else {
        (
            RecoveryStrategy::Custom(text.into()),
            Some(SelfCorrectionAction::Custom {
                action: text.into(),
            }),
        )
    };
    let risk = if lower.contains("unsafe")
        || lower.contains("restart fleet")
        || lower.contains("open gate")
    {
        "High"
    } else if lower.contains("halt") || lower.contains("emergency") {
        "Critical"
    } else {
        "Low"
    };
    let requires_approval =
        risk == "High" || risk == "Critical" || lower.contains("resume mission");
    PlannedRecoveryAction {
        description: text.into(),
        strategy,
        correction,
        risk: risk.into(),
        requires_approval,
        order,
    }
}

fn default_actions_for_classification(
    classification: FailureClassification,
    issue: &str,
) -> Vec<PlannedRecoveryAction> {
    // Description:
    //     Default actions for classification.
    //
    // Inputs:
    //     classification: FailureClassification
    //         Caller-supplied classification.
    //     issue: &str
    //         Caller-supplied issue.
    //
    // Outputs:
    //     result: Vec<PlannedRecoveryAction>
    //         Return value from `default_actions_for_classification`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::default_actions_for_classification(classification, issue);

    let defaults: &[&str] = match classification {
        FailureClassification::SensorFailure if issue.to_lowercase().contains("gps") => &[
            "switch_to visual_odometry",
            "reduce_speed 0.5 m/s",
            "enter degraded_mode",
        ],
        FailureClassification::SensorFailure => &["recalibrate sensor", "enter degraded_mode"],
        FailureClassification::ActuatorFailure => &["halt motion", "enter safe_mode"],
        FailureClassification::ConnectivityFailure => {
            &["restart connectivity", "enter degraded_mode"]
        }
        FailureClassification::ProviderFailure => &["reconnect provider", "use fallback provider"],
        FailureClassification::PackageFailure => &["reload package"],
        FailureClassification::MissionFailure => &["pause mission"],
        FailureClassification::HealthDegradation => {
            &["enter degraded_mode", "reduce_speed 0.3 m/s"]
        }
        FailureClassification::FleetFailure => &["reassign mission", "promote backup coordinator"],
        FailureClassification::SwarmFailure => &["redistribute tasks"],
        FailureClassification::SafetyFailure => &["enter safe_mode", "activate kill switch"],
        FailureClassification::Unknown => &["enter safe_mode"],
    };
    defaults
        .iter()
        .enumerate()
        .map(|(i, text)| parse_action_text(text, (i + 1) as u32))
        .collect()
}

fn infer_target_mode(actions: &[PlannedRecoveryAction]) -> Option<OperationalMode> {
    // Description:
    //     Infer target mode.
    //
    // Inputs:
    //     actions: &[PlannedRecoveryAction]
    //         Caller-supplied actions.
    //
    // Outputs:
    //     result: Option<OperationalMode>
    //         Return value from `infer_target_mode`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::infer_target_mode(actions);

    for action in actions {
        if let Some(SelfCorrectionAction::EnterMode { mode }) = &action.correction {
            return Some(match mode.to_lowercase().as_str() {
                "degradedmode" | "degraded_mode" | "degraded" => OperationalMode::DegradedMode,
                "safemode" | "safe_mode" | "safe" => OperationalMode::SafeMode,
                "emergencymode" | "emergency_mode" | "emergency" => OperationalMode::EmergencyMode,
                "recoverymode" | "recovery_mode" | "recovery" => OperationalMode::RecoveryMode,
                _ => OperationalMode::NormalMode,
            });
        }
    }
    None
}

fn assess_plan_risk(actions: &[PlannedRecoveryAction]) -> String {
    // Description:
    //     Assess plan risk.
    //
    // Inputs:
    //     actions: &[PlannedRecoveryAction]
    //         Caller-supplied actions.
    //
    // Outputs:
    //     result: String
    //         Return value from `assess_plan_risk`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::assess_plan_risk(actions);

    if actions
        .iter()
        .any(|a| a.risk.eq_ignore_ascii_case("critical"))
    {
        "Critical".into()
    } else if actions.iter().any(|a| a.risk.eq_ignore_ascii_case("high")) {
        "High".into()
    } else if actions
        .iter()
        .any(|a| a.risk.eq_ignore_ascii_case("medium"))
    {
        "Medium".into()
    } else {
        "Low".into()
    }
}

fn sanitize_name(s: &str) -> String {
    // Description:
    //     Sanitize name.
    //
    // Inputs:
    //     s: &str
    //         Caller-supplied s.
    //
    // Outputs:
    //     result: String
    //         Return value from `sanitize_name`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::sanitize_name(s);

    s.replace(['.', ' '], "_")
}

/// Validate mode transitions for recovery.
pub fn validate_mode_transitions(program: &Program) -> Vec<String> {
    // Description:
    //     Validate mode transitions.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //
    // Outputs:
    //     result: Vec<String>
    //         Return value from `validate_mode_transitions`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::validate_mode_transitions(progra);

    let modes = extract_operating_modes(program);
    let mut issues = validate_modes(program);
    let has_recovery = modes.iter().any(|m| m.kind == ModeKind::Recovery);
    if !modes.is_empty() && !has_recovery {
        issues.push("No recovery mode declared".into());
    }
    issues
}

/// Parse self-correction action from text.
pub fn parse_self_correction(text: &str) -> SelfCorrectionAction {
    // Description:
    //     Parse self correction.
    //
    // Inputs:
    //     ex: &str
    //         Caller-supplied ex.
    //
    // Outputs:
    //     result: SelfCorrectionAction
    //         Return value from `parse_self_correction`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::parse_self_correction(ex);

    parse_action_text(text, 0)
        .correction
        .unwrap_or(SelfCorrectionAction::Custom {
            action: text.into(),
        })
}

/// Map operational modes from program declarations.
pub fn operational_modes_from_program(program: &Program) -> Vec<OperationalMode> {
    // Description:
    //     Operational modes from program.
    //
    // Inputs:
    //     progra: &Program
    //         Caller-supplied progra.
    //
    // Outputs:
    //     result: Vec<OperationalMode>
    //         Return value from `operational_modes_from_program`.
    //
    // Example:

    //     let result = spanda_assurance::recovery::operational_modes_from_program(progra);

    extract_operating_modes(program)
        .iter()
        .map(|m| match m.kind {
            ModeKind::Normal => OperationalMode::NormalMode,
            ModeKind::Degraded => OperationalMode::DegradedMode,
            ModeKind::Safe => OperationalMode::SafeMode,
            ModeKind::Emergency => OperationalMode::EmergencyMode,
            ModeKind::Recovery => OperationalMode::RecoveryMode,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use spanda_lexer::tokenize;
    use spanda_parser::parse;

    fn parse_source(source: &str) -> Program {
        // Description:
        //     Parse source.
        //
        // Inputs:
        //     source: &str
        //         Caller-supplied source.
        //
        // Outputs:
        //     result: Program
        //         Return value from `parse_source`.
        //
        // Example:

        //     let result = spanda_assurance::recovery::parse_source(source);

        parse(tokenize(source).unwrap()).unwrap()
    }

    const RECOVERY_ROVER: &str = r#"
hardware RoverV1 {
    sensors [GPS, Camera, Lidar];
    actuators [DifferentialDrive];
    connectivity [WiFi, LTE];
}

operating_mode NormalMode { normal; }
operating_mode DegradedMode { degraded; }
operating_mode SafeMode { safe; }
operating_mode RecoveryMode { recovery; }

recovery_policy RoverRecovery {
    on gps.failed {
        switch_to visual_odometry;
        reduce_speed 0.5 m/s;
        enter degraded_mode;
    }
}

robot Rover {
    sensor gps: GPS;
    sensor camera: Camera;
    sensor lidar: Lidar;
    actuator wheels: DifferentialDrive;
    safety { max_speed = 1.2 m/s; }
    behavior patrol() { wheels.drive(0.5 m/s); }
}
"#;

    #[test]
    fn classifies_gps_failure() {
        // Description:
        //     Classifies gps failure.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_assurance::recovery::classifies_gps_failure();

        assert_eq!(
            classify_failure("gps.failed"),
            FailureClassification::SensorFailure
        );
    }

    fn issue_to_recovery_issue_maps_gps_failure() {
        assert_eq!(
            issue_to_recovery_issue("GPSFailure").as_deref(),
            Some("gps.failed")
        );
        assert!(program_has_recovery_for_issue(
            &parse_source(RECOVERY_ROVER),
            "gps.failed"
        ));
    }

    #[test]
    fn extracts_recovery_policy() {
        // Description:
        //     Extracts recovery policy.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_assurance::recovery::extracts_recovery_policy();

        let program = parse_source(RECOVERY_ROVER);
        let policies = extract_recovery_policies(&program);
        assert!(!policies.is_empty());
        assert!(policies[0].triggers.iter().any(|(c, _)| c.contains("gps")));
    }

    #[test]
    fn planner_generates_gps_recovery_plan() {
        // Description:
        //     Planner generates gps recovery plan.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_assurance::recovery::planner_generates_gps_recovery_plan();

        let program = parse_source(RECOVERY_ROVER);
        let ctx = RecoveryContext {
            issue: "gps.failed".into(),
            diagnosis: Some("Satellite lock lost".into()),
            classification: Some(FailureClassification::SensorFailure),
            level: RecoveryLevel::Level2AutomaticLowRisk,
        };
        let plan = RecoveryPlanner::plan(&program, &ctx);
        assert_eq!(plan.diagnosis, "Satellite lock lost");
        assert!(!plan.actions.is_empty());
        assert_eq!(plan.risk, "Low");
    }

    #[test]
    fn validation_gates_run() {
        // Description:
        //     Validation gates run.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_assurance::recovery::validation_gates_run();

        let program = parse_source(RECOVERY_ROVER);
        let ctx = RecoveryContext {
            issue: "gps.failed".into(),
            diagnosis: None,
            classification: None,
            level: RecoveryLevel::Level2AutomaticLowRisk,
        };
        let plan = RecoveryPlanner::plan(&program, &ctx);
        let safe = validate_recovery_plan(&program, &plan);
        assert!(!safe.is_empty());
        assert!(safe.iter().all(|a| a.safety_validation.passed));
    }

    #[test]
    fn execute_recovery_produces_evidence() {
        // Description:
        //     Execute recovery produces evidence.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_assurance::recovery::execute_recovery_produces_evidence();

        let program = parse_source(RECOVERY_ROVER);
        let report = simulate_failure_recovery(&program, "gps", None);
        assert!(!report.results.is_empty());
        assert_eq!(report.results[0].evidence.safety_validation, "PASS");
    }

    #[test]
    fn knowledge_store_round_trip() {
        // Description:
        //     Knowledge store round trip.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_assurance::recovery::knowledge_store_round_trip();

        let dir = std::env::temp_dir().join("spanda_recovery_kb_test");
        let _ = std::fs::remove_dir_all(&dir);
        let path = dir.join("knowledge.json");
        let mut kb = RecoveryKnowledgeBase::default();
        kb.entries.push(RecoveryKnowledgeEntry {
            failure_pattern: "GPS".into(),
            recovery_pattern: "switch_to visual_odometry".into(),
            success_rate: 0.8,
            recommendation: "On GPS failure: switch_to visual_odometry".into(),
        });
        save_recovery_knowledge_store(&path, &kb).unwrap();
        let loaded = load_recovery_knowledge_store(&path);
        assert_eq!(loaded.entries.len(), 1);
        assert_eq!(loaded.entries[0].failure_pattern, "GPS");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn planner_prefers_persisted_knowledge() {
        // Description:
        //     Planner prefers persisted knowledge.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_assurance::recovery::planner_prefers_persisted_knowledge();

        let program = parse_source(
            "robot Rover { sensor gps: GPS; actuator w: DifferentialDrive; safety { max_speed = 1 m/s; } behavior b() {} }",
        );
        let store = super::default_knowledge_store_path();
        if let Some(parent) = store.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        save_recovery_knowledge_store(
            &store,
            &RecoveryKnowledgeBase {
                entries: vec![RecoveryKnowledgeEntry {
                    failure_pattern: "gps".into(),
                    recovery_pattern: "switch_to visual_odometry".into(),
                    success_rate: 0.95,
                    recommendation: "Use VO".into(),
                }],
            },
        )
        .unwrap();
        let ctx = RecoveryContext {
            issue: "gps.failed".into(),
            diagnosis: None,
            classification: None,
            level: RecoveryLevel::Level2AutomaticLowRisk,
        };
        let plan = RecoveryPlanner::plan(&program, &ctx);
        assert!(plan
            .actions
            .iter()
            .any(|a| a.description.contains("visual_odometry")));
        let _ = std::fs::remove_file(&store);
    }
}

/// Prepend device-pool failover actions when a configured redundant chain exists.
pub fn enrich_recovery_plan_with_failover(
    plan: &mut RecoveryPlan,
    registry: &spanda_config::DeviceRegistry,
    failed_device_id: &str,
) {
    for (offset, action) in spanda_config::recovery_failover_actions(registry, failed_device_id)
        .into_iter()
        .enumerate()
    {
        plan.actions
            .insert(offset, parse_action_text(&action, offset as u32 + 1));
    }
}
