//! Self-healing and self-correction recovery framework.
//!
//! Implements Detect → Diagnose → Plan → Validate → Execute → Verify → Audit
//! without bypassing safety validation, hardware verification, capability
//! verification, kill switch, or human approval requirements.

use crate::diagnosis::DiagnosisReport;
use crate::modes::{extract_operating_modes, validate_modes};
use crate::types::ModeKind;
use serde::{Deserialize, Serialize};
use spanda_ast::assurance_decl::{MitigationDecl, RecoveryPolicyDecl};
use spanda_ast::nodes::Program;
use spanda_capability::infer_robot_capabilities;
use spanda_hardware::{verify_program_compatibility, VerifyOptions};
use spanda_readiness::{
    analyze_failure, default_deploy_target, evaluate_readiness, verify_approvals,
    FailureAnalysisReport, ReadinessOptions,
};
/// Outcome status for a recovery attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum RecoveryStatus {
    Success,
    PartialSuccess,
    Failed,
    Aborted,
    Unsafe,
}

/// Autonomy level for recovery execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum RecoveryLevel {
    /// Detection only — no automated recovery.
    Level0DetectionOnly = 0,
    /// Recommend recovery actions to operator.
    Level1Recommend = 1,
    /// Automatic low-risk recovery without approval.
    Level2AutomaticLowRisk = 2,
    /// Automatic recovery after safety validation.
    Level3AutomaticWithValidation = 3,
    /// High-risk recovery requires human approval.
    Level4HumanApproval = 4,
}

/// Failure classification for recovery planning.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum FailureClassification {
    SensorFailure,
    ActuatorFailure,
    ConnectivityFailure,
    ProviderFailure,
    PackageFailure,
    MissionFailure,
    HealthDegradation,
    FleetFailure,
    SwarmFailure,
    SafetyFailure,
    Unknown,
}

/// Recovery strategy kind.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryStrategy {
    Failover,
    DegradedMode,
    SpeedReduction,
    SensorRecalibration,
    ProviderReconnect,
    ConnectivityRestart,
    PackageReload,
    DeviceReinitialize,
    RedundantHardwareSwitch,
    RouteChange,
    MissionPause,
    OperatorAlert,
    FleetReassign,
    SwarmRedistribute,
    Custom(String),
}

/// Self-correction action types.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SelfCorrectionAction {
    RecalibrateSensor { sensor: String },
    ReconnectProvider { provider: String },
    RestartConnectivity { channel: String },
    ReloadPackage { package: String },
    ReinitializeDevice { device: String },
    SwitchRedundantHardware { component: String },
    ChangeRoute { route: String },
    ReduceSpeed { limit: String },
    PauseMission,
    EnterMode { mode: String },
    Custom { action: String },
}

/// Operating mode for safe transitions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub enum OperationalMode {
    NormalMode,
    DegradedMode,
    SafeMode,
    EmergencyMode,
    RecoveryMode,
}

impl OperationalMode {
    /// Map operational mode to assurance `ModeKind`.
    pub fn to_mode_kind(self) -> ModeKind {
        match self {
            Self::NormalMode => ModeKind::Normal,
            Self::DegradedMode => ModeKind::Degraded,
            Self::SafeMode => ModeKind::Safe,
            Self::EmergencyMode => ModeKind::Emergency,
            Self::RecoveryMode => ModeKind::Recovery,
        }
    }
}

/// Single planned recovery action.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlannedRecoveryAction {
    pub description: String,
    pub strategy: RecoveryStrategy,
    pub correction: Option<SelfCorrectionAction>,
    pub risk: String,
    pub requires_approval: bool,
    pub order: u32,
}

/// Recovery plan generated by the planner.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryPlan {
    pub name: String,
    pub failure: String,
    pub classification: FailureClassification,
    pub diagnosis: String,
    pub actions: Vec<PlannedRecoveryAction>,
    pub target_mode: Option<OperationalMode>,
    pub level: RecoveryLevel,
    pub risk: String,
}

/// Recovery policy extracted from declarations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryPolicySpec {
    pub name: String,
    pub triggers: Vec<(String, Vec<String>)>,
}

/// Safety-validated recovery action ready for execution.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SafeRecoveryAction {
    pub action: PlannedRecoveryAction,
    pub safety_validation: ValidationGateResult,
    pub hardware_verification: ValidationGateResult,
    pub capability_verification: ValidationGateResult,
    pub readiness_validation: ValidationGateResult,
    pub approved: bool,
}

/// Result of a validation gate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ValidationGateResult {
    pub gate: String,
    pub passed: bool,
    pub message: String,
}

/// Outcome of executing a recovery plan.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryResult {
    pub plan: String,
    pub status: RecoveryStatus,
    pub executed_actions: Vec<String>,
    pub failed_actions: Vec<String>,
    pub verification_outcome: String,
    pub evidence: RecoveryEvidence,
}

/// Evidence collected during recovery.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryEvidence {
    pub failure: String,
    pub diagnosis: String,
    pub plan: String,
    pub safety_validation: String,
    pub recovery_actions: Vec<String>,
    pub outcome: String,
    pub operator_approval: Option<String>,
    pub verification: String,
}

/// Recovery audit record for provenance.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryAuditRecord {
    pub detected_failure: String,
    pub diagnosis: String,
    pub chosen_recovery: String,
    pub safety_validation_result: String,
    pub recovery_outcome: String,
    pub operator_approval: Option<String>,
    pub verification_outcome: String,
    pub timestamp_hint: String,
}

/// Traceability chain for recovery workflow.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryTraceChain {
    pub failure: String,
    pub diagnosis: String,
    pub recovery_plan: String,
    pub safety_validation: String,
    pub recovery_action: String,
    pub outcome: String,
    pub evidence: String,
}

/// Recovery readiness assessment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryReadiness {
    pub recovery_ready: bool,
    pub risk: String,
    pub readiness_score: u32,
    pub blockers: Vec<String>,
}

/// Fleet-level recovery plan.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FleetRecoveryPlan {
    pub fleet: String,
    pub failed_robot: Option<String>,
    pub actions: Vec<String>,
    pub risk: String,
}

/// Knowledge base entry for recovery patterns (no auto-modification).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryKnowledgeEntry {
    pub failure_pattern: String,
    pub recovery_pattern: String,
    pub success_rate: f64,
    pub recommendation: String,
}

/// Recovery knowledge base for self-improvement recommendations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryKnowledgeBase {
    pub entries: Vec<RecoveryKnowledgeEntry>,
}

/// Recovery assurance metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryAssuranceMetrics {
    pub recovery_evidence: Vec<RecoveryEvidence>,
    pub recovery_readiness: RecoveryReadiness,
    pub success_rate: f64,
    pub traceability: Vec<RecoveryTraceChain>,
}

/// Composite recovery framework report.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryReport {
    pub policies: Vec<RecoveryPolicySpec>,
    pub plans: Vec<RecoveryPlan>,
    pub safe_actions: Vec<SafeRecoveryAction>,
    pub results: Vec<RecoveryResult>,
    pub audit: Vec<RecoveryAuditRecord>,
    pub readiness: RecoveryReadiness,
    pub assurance: RecoveryAssuranceMetrics,
    pub fleet_plans: Vec<FleetRecoveryPlan>,
    pub knowledge: RecoveryKnowledgeBase,
    pub passed: bool,
}

/// Input context for recovery planning.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecoveryContext {
    pub issue: String,
    pub diagnosis: Option<String>,
    pub classification: Option<FailureClassification>,
    pub level: RecoveryLevel,
}

/// Planner that generates recovery plans from failures and diagnoses.
pub struct RecoveryPlanner;

impl RecoveryPlanner {
    /// Generate a recovery plan for the given context and program.
    pub fn plan(program: &Program, context: &RecoveryContext) -> RecoveryPlan {
        let classification = context
            .classification
            .unwrap_or_else(|| classify_failure(&context.issue));
        let diagnosis = context
            .diagnosis
            .clone()
            .unwrap_or_else(|| infer_diagnosis(&context.issue, classification));
        let policies = extract_recovery_policies(program);
        let mut actions = actions_from_policies(&policies, &context.issue);
        if actions.is_empty() {
            actions = default_actions_for_classification(classification, &context.issue);
        }
        let target_mode = infer_target_mode(&actions);
        let risk = assess_plan_risk(&actions);
        let level = context.level;
        RecoveryPlan {
            name: format!("recovery_{}", sanitize_name(&context.issue)),
            failure: context.issue.clone(),
            classification,
            diagnosis,
            actions,
            target_mode,
            level,
            risk,
        }
    }
}

/// Classify a failure description into a failure category.
pub fn classify_failure(issue: &str) -> FailureClassification {
    let lower = issue.to_lowercase();
    if lower.contains("gps")
        || lower.contains("camera")
        || lower.contains("lidar")
        || lower.contains("sensor")
        || lower.contains("imu")
    {
        FailureClassification::SensorFailure
    } else if lower.contains("actuator") || lower.contains("motor") || lower.contains("drive") {
        FailureClassification::ActuatorFailure
    } else if lower.contains("lte")
        || lower.contains("wifi")
        || lower.contains("connect")
        || lower.contains("network")
    {
        FailureClassification::ConnectivityFailure
    } else if lower.contains("provider") {
        FailureClassification::ProviderFailure
    } else if lower.contains("package") {
        FailureClassification::PackageFailure
    } else if lower.contains("mission") {
        FailureClassification::MissionFailure
    } else if lower.contains("health") || lower.contains("degrad") {
        FailureClassification::HealthDegradation
    } else if lower.contains("fleet") {
        FailureClassification::FleetFailure
    } else if lower.contains("swarm") {
        FailureClassification::SwarmFailure
    } else if lower.contains("safety") || lower.contains("kill") {
        FailureClassification::SafetyFailure
    } else {
        FailureClassification::Unknown
    }
}

/// Extract recovery policies from program declarations.
pub fn extract_recovery_policies(program: &Program) -> Vec<RecoveryPolicySpec> {
    let Program::Program {
        recovery_policies,
        mitigations,
        ..
    } = program;

    let mut specs: Vec<RecoveryPolicySpec> = recovery_policies
        .iter()
        .map(|decl| {
            let RecoveryPolicyDecl::RecoveryPolicyDecl { name, branches, .. } = decl;
            RecoveryPolicySpec {
                name: name.clone(),
                triggers: branches
                    .iter()
                    .map(|b| (b.condition.clone(), b.actions.clone()))
                    .collect(),
            }
        })
        .collect();

    for mit in mitigations {
        let MitigationDecl::MitigationDecl { name, branches, .. } = mit;
        specs.push(RecoveryPolicySpec {
            name: name.clone(),
            triggers: branches
                .iter()
                .map(|b| (b.condition.clone(), b.actions.clone()))
                .collect(),
        });
    }

    specs
}

/// Validate recovery actions through safety, hardware, capability, and readiness gates.
pub fn validate_recovery_plan(program: &Program, plan: &RecoveryPlan) -> Vec<SafeRecoveryAction> {
    let options = ReadinessOptions {
        target: default_deploy_target(program),
        ..Default::default()
    };
    let readiness = evaluate_readiness(program, &options);
    let hw_options = VerifyOptions {
        target: default_deploy_target(program),
        ..Default::default()
    };
    let hw = verify_program_compatibility(program, &hw_options);
    let caps = infer_robot_capabilities(program);
    let approvals = verify_approvals(program);

    plan.actions
        .iter()
        .map(|action| {
            let safety = ValidationGateResult {
                gate: "Safety Validation".into(),
                passed: !action.description.to_lowercase().contains("unsafe")
                    && !plan
                        .classification
                        .eq(&FailureClassification::SafetyFailure),
                message: if action.description.to_lowercase().contains("unsafe") {
                    "Unsafe action blocked".into()
                } else {
                    "PASS".into()
                },
            };
            let hardware = ValidationGateResult {
                gate: "Hardware Verification".into(),
                passed: hw.compatible,
                message: if hw.compatible {
                    "PASS".into()
                } else {
                    "Hardware incompatible".into()
                },
            };
            let capability = ValidationGateResult {
                gate: "Capability Verification".into(),
                passed: !caps.is_empty()
                    || plan.classification == FailureClassification::ConnectivityFailure,
                message: if caps.is_empty() {
                    "No capabilities inferred".into()
                } else {
                    "PASS".into()
                },
            };
            let readiness_gate = ValidationGateResult {
                gate: "Readiness Validation".into(),
                passed: readiness.mission_ready
                    || (action.risk.eq_ignore_ascii_case("low") && readiness.score.total > 0)
                    || plan.level <= RecoveryLevel::Level1Recommend,
                message: if readiness.mission_ready {
                    "PASS".into()
                } else if action.risk.eq_ignore_ascii_case("low") && readiness.score.total > 0 {
                    format!("PASS (low-risk, score {}/100)", readiness.score.total)
                } else {
                    format!("Readiness score {}/100", readiness.score.total)
                },
            };
            let requires_approval = action.requires_approval
                || plan.level == RecoveryLevel::Level4HumanApproval
                || action.risk.eq_ignore_ascii_case("high")
                || action.risk.eq_ignore_ascii_case("critical");
            let approved = if requires_approval {
                approvals.compatible
                    && approvals.rows.iter().any(|r| {
                        r.approval_path_exists
                            && (r.actor == "Operator" || r.actor.contains("Operator"))
                    })
            } else {
                true
            };
            SafeRecoveryAction {
                action: action.clone(),
                safety_validation: safety,
                hardware_verification: hardware,
                capability_verification: capability,
                readiness_validation: readiness_gate,
                approved,
            }
        })
        .collect()
}

/// Evaluate whether recovery can be attempted.
pub fn evaluate_recovery_readiness(program: &Program, plan: &RecoveryPlan) -> RecoveryReadiness {
    let options = ReadinessOptions {
        target: default_deploy_target(program),
        ..Default::default()
    };
    let readiness = evaluate_readiness(program, &options);
    let safe_actions = validate_recovery_plan(program, plan);
    let all_gates_pass = safe_actions.iter().all(|a| {
        a.safety_validation.passed
            && a.hardware_verification.passed
            && a.capability_verification.passed
            && a.readiness_validation.passed
    });
    let mut blockers = Vec::new();
    if !all_gates_pass {
        blockers.push("One or more validation gates failed".into());
    }
    for action in &safe_actions {
        if action.action.requires_approval && !action.approved {
            blockers.push(format!(
                "Operator approval required for: {}",
                action.action.description
            ));
        }
    }
    let risk = plan.risk.clone();
    RecoveryReadiness {
        recovery_ready: all_gates_pass && blockers.is_empty(),
        risk,
        readiness_score: readiness.score.total,
        blockers,
    }
}

/// Execute recovery plan (static simulation — no uncontrolled autonomous behavior).
pub fn execute_recovery_plan(program: &Program, plan: &RecoveryPlan) -> RecoveryResult {
    let safe_actions = validate_recovery_plan(program, plan);
    let mut executed = Vec::new();
    let mut failed = Vec::new();

    for safe in &safe_actions {
        let gates_ok = safe.safety_validation.passed
            && safe.hardware_verification.passed
            && safe.capability_verification.passed
            && safe.readiness_validation.passed;
        if !gates_ok {
            failed.push(safe.action.description.clone());
            continue;
        }
        if safe.action.requires_approval && !safe.approved {
            failed.push(format!("{} (approval required)", safe.action.description));
            continue;
        }
        executed.push(safe.action.description.clone());
    }

    let status = if failed.is_empty() && !executed.is_empty() {
        RecoveryStatus::Success
    } else if !executed.is_empty() {
        RecoveryStatus::PartialSuccess
    } else if safe_actions.iter().any(|a| !a.safety_validation.passed) {
        RecoveryStatus::Unsafe
    } else {
        RecoveryStatus::Failed
    };

    let evidence = RecoveryEvidence {
        failure: plan.failure.clone(),
        diagnosis: plan.diagnosis.clone(),
        plan: plan.name.clone(),
        safety_validation: if safe_actions.iter().all(|a| a.safety_validation.passed) {
            "PASS".into()
        } else {
            "FAIL".into()
        },
        recovery_actions: executed.clone(),
        outcome: format!("{status:?}"),
        operator_approval: if plan.level == RecoveryLevel::Level4HumanApproval {
            Some("Operator".into())
        } else {
            None
        },
        verification: if status == RecoveryStatus::Success {
            "Recovery verified".into()
        } else {
            "Recovery incomplete".into()
        },
    };

    RecoveryResult {
        plan: plan.name.clone(),
        status,
        executed_actions: executed,
        failed_actions: failed,
        verification_outcome: evidence.verification.clone(),
        evidence,
    }
}

/// Build recovery audit records from results.
pub fn build_recovery_audit(results: &[RecoveryResult]) -> Vec<RecoveryAuditRecord> {
    results
        .iter()
        .map(|r| RecoveryAuditRecord {
            detected_failure: r.evidence.failure.clone(),
            diagnosis: r.evidence.diagnosis.clone(),
            chosen_recovery: r.evidence.plan.clone(),
            safety_validation_result: r.evidence.safety_validation.clone(),
            recovery_outcome: format!("{:?}", r.status),
            operator_approval: r.evidence.operator_approval.clone(),
            verification_outcome: r.verification_outcome.clone(),
            timestamp_hint: "static-analysis".into(),
        })
        .collect()
}

/// Build traceability chain from recovery results.
pub fn build_recovery_traceability(results: &[RecoveryResult]) -> Vec<RecoveryTraceChain> {
    results
        .iter()
        .map(|r| RecoveryTraceChain {
            failure: r.evidence.failure.clone(),
            diagnosis: r.evidence.diagnosis.clone(),
            recovery_plan: r.evidence.plan.clone(),
            safety_validation: r.evidence.safety_validation.clone(),
            recovery_action: r.executed_actions.join("; "),
            outcome: format!("{:?}", r.status),
            evidence: r.evidence.verification.clone(),
        })
        .collect()
}

/// Plan fleet recovery actions.
pub fn plan_fleet_recovery(program: &Program, failed_robot: &str) -> Vec<FleetRecoveryPlan> {
    let Program::Program { fleets, .. } = program;
    fleets
        .iter()
        .map(|f| {
            let spanda_ast::robotics_decl::FleetDecl::FleetDecl { name, .. } = f;
            FleetRecoveryPlan {
                fleet: name.clone(),
                failed_robot: Some(failed_robot.into()),
                actions: vec![
                    format!("Replace failed robot {failed_robot}"),
                    "Reassign mission to backup robot".into(),
                    "Redistribute tasks across fleet".into(),
                    "Promote backup coordinator".into(),
                ],
                risk: "Medium".into(),
            }
        })
        .collect()
}

/// Build recovery knowledge base from historical patterns.
pub fn build_recovery_knowledge(program: &Program) -> RecoveryKnowledgeBase {
    let failure_report = analyze_failure(program);
    let entries: Vec<RecoveryKnowledgeEntry> = failure_report
        .impacts
        .iter()
        .map(|impact| RecoveryKnowledgeEntry {
            failure_pattern: impact.component.clone(),
            recovery_pattern: impact.mitigation.clone(),
            success_rate: match impact.severity.as_str() {
                "Critical" => 0.6,
                "High" => 0.75,
                "Medium" => 0.85,
                _ => 0.9,
            },
            recommendation: format!("On {} failure: {}", impact.component, impact.mitigation),
        })
        .collect();
    RecoveryKnowledgeBase { entries }
}

/// Simulate failure injection for recovery testing.
pub fn simulate_failure_recovery(program: &Program, failure_kind: &str) -> RecoveryReport {
    let context = RecoveryContext {
        issue: format!("{failure_kind} failure"),
        diagnosis: Some(infer_diagnosis(
            failure_kind,
            classify_failure(failure_kind),
        )),
        classification: Some(classify_failure(failure_kind)),
        level: RecoveryLevel::Level3AutomaticWithValidation,
    };
    evaluate_recovery(program, Some(&context))
}

/// Run full recovery framework analysis on a program.
pub fn evaluate_recovery(program: &Program, context: Option<&RecoveryContext>) -> RecoveryReport {
    let policies = extract_recovery_policies(program);
    let contexts: Vec<RecoveryContext> = if let Some(ctx) = context {
        vec![ctx.clone()]
    } else {
        default_recovery_contexts(program)
    };

    let plans: Vec<RecoveryPlan> = contexts
        .iter()
        .map(|ctx| RecoveryPlanner::plan(program, ctx))
        .collect();

    let safe_actions: Vec<SafeRecoveryAction> = plans
        .iter()
        .flat_map(|plan| validate_recovery_plan(program, plan))
        .collect();

    let results: Vec<RecoveryResult> = plans
        .iter()
        .map(|plan| execute_recovery_plan(program, plan))
        .collect();

    let audit = build_recovery_audit(&results);
    let traceability = build_recovery_traceability(&results);
    let readiness = plans
        .first()
        .map(|p| evaluate_recovery_readiness(program, p))
        .unwrap_or(RecoveryReadiness {
            recovery_ready: false,
            risk: "Unknown".into(),
            readiness_score: 0,
            blockers: vec!["No recovery plan".into()],
        });

    let success_count = results
        .iter()
        .filter(|r| r.status == RecoveryStatus::Success)
        .count();
    let success_rate = if results.is_empty() {
        0.0
    } else {
        success_count as f64 / results.len() as f64
    };

    let assurance = RecoveryAssuranceMetrics {
        recovery_evidence: results.iter().map(|r| r.evidence.clone()).collect(),
        recovery_readiness: readiness.clone(),
        success_rate,
        traceability,
    };

    let fleet_plans = plan_fleet_recovery(program, "Rover");
    let knowledge = build_recovery_knowledge(program);
    let mode_issues = validate_modes(program);

    let passed = !plans.is_empty()
        && results
            .iter()
            .all(|r| r.status != RecoveryStatus::Unsafe && r.status != RecoveryStatus::Failed)
        && mode_issues.is_empty();

    RecoveryReport {
        policies,
        plans,
        safe_actions,
        results,
        audit,
        readiness,
        assurance,
        fleet_plans,
        knowledge,
        passed,
    }
}

/// Integrate recovery with diagnosis report.
pub fn recovery_from_diagnosis(program: &Program, diagnosis: &DiagnosisReport) -> RecoveryReport {
    let mut contexts = Vec::new();
    for d in &diagnosis.static_diagnoses {
        for rc in &d.root_causes {
            contexts.push(RecoveryContext {
                issue: rc.description.clone(),
                diagnosis: Some(d.subject.clone()),
                classification: Some(classify_failure(&rc.description)),
                level: RecoveryLevel::Level2AutomaticLowRisk,
            });
        }
    }
    if let Some(trace) = &diagnosis.trace_diagnosis {
        contexts.push(RecoveryContext {
            issue: trace.root_cause.clone(),
            diagnosis: Some(trace.root_cause.clone()),
            classification: Some(classify_failure(&trace.root_cause)),
            level: RecoveryLevel::Level2AutomaticLowRisk,
        });
    }
    if contexts.is_empty() {
        return evaluate_recovery(program, None);
    }
    let policies = extract_recovery_policies(program);
    let plans: Vec<RecoveryPlan> = contexts
        .iter()
        .map(|ctx| RecoveryPlanner::plan(program, ctx))
        .collect();
    let results: Vec<RecoveryResult> = plans
        .iter()
        .map(|plan| execute_recovery_plan(program, plan))
        .collect();
    let safe_actions: Vec<SafeRecoveryAction> = plans
        .iter()
        .flat_map(|plan| validate_recovery_plan(program, plan))
        .collect();
    let audit = build_recovery_audit(&results);
    let traceability = build_recovery_traceability(&results);
    let readiness = plans
        .first()
        .map(|p| evaluate_recovery_readiness(program, p))
        .unwrap_or(RecoveryReadiness {
            recovery_ready: false,
            risk: "Unknown".into(),
            readiness_score: 0,
            blockers: vec!["No recovery plan".into()],
        });
    let success_count = results
        .iter()
        .filter(|r| r.status == RecoveryStatus::Success)
        .count();
    let success_rate = if results.is_empty() {
        0.0
    } else {
        success_count as f64 / results.len() as f64
    };
    let recovery_evidence: Vec<RecoveryEvidence> =
        results.iter().map(|r| r.evidence.clone()).collect();
    let passed = !results.is_empty() && results.iter().all(|r| r.status != RecoveryStatus::Unsafe);
    RecoveryReport {
        policies,
        plans,
        safe_actions,
        results,
        audit,
        readiness: readiness.clone(),
        assurance: RecoveryAssuranceMetrics {
            recovery_evidence,
            recovery_readiness: readiness,
            success_rate,
            traceability,
        },
        fleet_plans: plan_fleet_recovery(program, "Rover"),
        knowledge: build_recovery_knowledge(program),
        passed,
    }
}

/// Extend failure analysis with recovery plan details.
pub fn analyze_failure_with_recovery(program: &Program) -> FailureAnalysisWithRecovery {
    let failure = analyze_failure(program);
    let recovery = evaluate_recovery(program, None);
    FailureAnalysisWithRecovery {
        failure,
        recovery_plans: recovery.plans,
        risk: recovery.readiness.risk.clone(),
    }
}

/// Failure analysis enriched with recovery planning.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FailureAnalysisWithRecovery {
    pub failure: FailureAnalysisReport,
    pub recovery_plans: Vec<RecoveryPlan>,
    pub risk: String,
}

fn default_recovery_contexts(program: &Program) -> Vec<RecoveryContext> {
    let policies = extract_recovery_policies(program);
    if policies.is_empty() {
        return vec![RecoveryContext {
            issue: "gps.failed".into(),
            diagnosis: Some("Satellite lock lost".into()),
            classification: Some(FailureClassification::SensorFailure),
            level: RecoveryLevel::Level2AutomaticLowRisk,
        }];
    }
    policies
        .iter()
        .flat_map(|p| {
            p.triggers.iter().map(|(cond, _)| RecoveryContext {
                issue: cond.clone(),
                diagnosis: None,
                classification: None,
                level: RecoveryLevel::Level2AutomaticLowRisk,
            })
        })
        .collect()
}

fn infer_diagnosis(issue: &str, classification: FailureClassification) -> String {
    let lower = issue.to_lowercase();
    if lower.contains("gps") {
        "Satellite lock lost".into()
    } else if lower.contains("lidar") {
        "Lidar point cloud unavailable".into()
    } else if lower.contains("lte") || lower.contains("wifi") {
        "Connectivity link down".into()
    } else {
        match classification {
            FailureClassification::SensorFailure => "Sensor reading unavailable".into(),
            FailureClassification::ActuatorFailure => "Actuator response timeout".into(),
            FailureClassification::ConnectivityFailure => "Network unreachable".into(),
            FailureClassification::ProviderFailure => "Provider backend unavailable".into(),
            FailureClassification::PackageFailure => "Package load failure".into(),
            FailureClassification::MissionFailure => "Mission constraint violated".into(),
            FailureClassification::HealthDegradation => "Health check threshold exceeded".into(),
            FailureClassification::FleetFailure => "Fleet member unresponsive".into(),
            FailureClassification::SwarmFailure => "Swarm coordination lost".into(),
            FailureClassification::SafetyFailure => "Safety rule violation detected".into(),
            FailureClassification::Unknown => "Root cause under investigation".into(),
        }
    }
}

fn actions_from_policies(
    policies: &[RecoveryPolicySpec],
    issue: &str,
) -> Vec<PlannedRecoveryAction> {
    let lower = issue.to_lowercase();
    let mut actions = Vec::new();
    let mut order = 0u32;
    for policy in policies {
        for (condition, policy_actions) in &policy.triggers {
            if lower.contains(&condition.to_lowercase())
                || condition_matches(&lower, &condition.to_lowercase())
            {
                for action_text in policy_actions {
                    order += 1;
                    actions.push(parse_action_text(action_text, order));
                }
            }
        }
    }
    actions
}

fn condition_matches(issue: &str, condition: &str) -> bool {
    let parts: Vec<&str> = condition.split('.').collect();
    parts.iter().all(|p| issue.contains(p))
}

fn parse_action_text(text: &str, order: u32) -> PlannedRecoveryAction {
    let lower = text.to_lowercase();
    let (strategy, correction) = if lower.contains("visual_odometry") || lower.contains("switch_to")
    {
        (
            RecoveryStrategy::Failover,
            Some(SelfCorrectionAction::Custom {
                action: text.into(),
            }),
        )
    } else if lower.contains("reduce_speed") {
        (
            RecoveryStrategy::SpeedReduction,
            Some(SelfCorrectionAction::ReduceSpeed {
                limit: text.replace("reduce_speed", "").trim().into(),
            }),
        )
    } else if lower.contains("degraded") {
        (
            RecoveryStrategy::DegradedMode,
            Some(SelfCorrectionAction::EnterMode {
                mode: "DegradedMode".into(),
            }),
        )
    } else if lower.contains("safe_mode") || lower.contains("safe mode") {
        (
            RecoveryStrategy::DegradedMode,
            Some(SelfCorrectionAction::EnterMode {
                mode: "SafeMode".into(),
            }),
        )
    } else if lower.contains("reconnect") {
        (
            RecoveryStrategy::ProviderReconnect,
            Some(SelfCorrectionAction::ReconnectProvider {
                provider: "default".into(),
            }),
        )
    } else if lower.contains("pause") {
        (
            RecoveryStrategy::MissionPause,
            Some(SelfCorrectionAction::PauseMission),
        )
    } else {
        (
            RecoveryStrategy::Custom(text.into()),
            Some(SelfCorrectionAction::Custom {
                action: text.into(),
            }),
        )
    };
    let risk = if lower.contains("unsafe")
        || lower.contains("restart fleet")
        || lower.contains("open gate")
    {
        "High"
    } else if lower.contains("halt") || lower.contains("emergency") {
        "Critical"
    } else {
        "Low"
    };
    let requires_approval =
        risk == "High" || risk == "Critical" || lower.contains("resume mission");
    PlannedRecoveryAction {
        description: text.into(),
        strategy,
        correction,
        risk: risk.into(),
        requires_approval,
        order,
    }
}

fn default_actions_for_classification(
    classification: FailureClassification,
    issue: &str,
) -> Vec<PlannedRecoveryAction> {
    let defaults: &[&str] = match classification {
        FailureClassification::SensorFailure if issue.to_lowercase().contains("gps") => &[
            "switch_to visual_odometry",
            "reduce_speed 0.5 m/s",
            "enter degraded_mode",
        ],
        FailureClassification::SensorFailure => &["recalibrate sensor", "enter degraded_mode"],
        FailureClassification::ActuatorFailure => &["halt motion", "enter safe_mode"],
        FailureClassification::ConnectivityFailure => {
            &["restart connectivity", "enter degraded_mode"]
        }
        FailureClassification::ProviderFailure => &["reconnect provider", "use fallback provider"],
        FailureClassification::PackageFailure => &["reload package"],
        FailureClassification::MissionFailure => &["pause mission"],
        FailureClassification::HealthDegradation => {
            &["enter degraded_mode", "reduce_speed 0.3 m/s"]
        }
        FailureClassification::FleetFailure => &["reassign mission", "promote backup coordinator"],
        FailureClassification::SwarmFailure => &["redistribute tasks"],
        FailureClassification::SafetyFailure => &["enter safe_mode", "activate kill switch"],
        FailureClassification::Unknown => &["enter safe_mode"],
    };
    defaults
        .iter()
        .enumerate()
        .map(|(i, text)| parse_action_text(text, (i + 1) as u32))
        .collect()
}

fn infer_target_mode(actions: &[PlannedRecoveryAction]) -> Option<OperationalMode> {
    for action in actions {
        if let Some(SelfCorrectionAction::EnterMode { mode }) = &action.correction {
            return Some(match mode.to_lowercase().as_str() {
                "degradedmode" | "degraded_mode" | "degraded" => OperationalMode::DegradedMode,
                "safemode" | "safe_mode" | "safe" => OperationalMode::SafeMode,
                "emergencymode" | "emergency_mode" | "emergency" => OperationalMode::EmergencyMode,
                "recoverymode" | "recovery_mode" | "recovery" => OperationalMode::RecoveryMode,
                _ => OperationalMode::NormalMode,
            });
        }
    }
    None
}

fn assess_plan_risk(actions: &[PlannedRecoveryAction]) -> String {
    if actions
        .iter()
        .any(|a| a.risk.eq_ignore_ascii_case("critical"))
    {
        "Critical".into()
    } else if actions.iter().any(|a| a.risk.eq_ignore_ascii_case("high")) {
        "High".into()
    } else if actions
        .iter()
        .any(|a| a.risk.eq_ignore_ascii_case("medium"))
    {
        "Medium".into()
    } else {
        "Low".into()
    }
}

fn sanitize_name(s: &str) -> String {
    s.replace(['.', ' '], "_")
}

/// Validate mode transitions for recovery.
pub fn validate_mode_transitions(program: &Program) -> Vec<String> {
    let modes = extract_operating_modes(program);
    let mut issues = validate_modes(program);
    let has_recovery = modes.iter().any(|m| m.kind == ModeKind::Recovery);
    if !modes.is_empty() && !has_recovery {
        issues.push("No recovery mode declared".into());
    }
    issues
}

/// Parse self-correction action from text.
pub fn parse_self_correction(text: &str) -> SelfCorrectionAction {
    parse_action_text(text, 0)
        .correction
        .unwrap_or(SelfCorrectionAction::Custom {
            action: text.into(),
        })
}

/// Map operational modes from program declarations.
pub fn operational_modes_from_program(program: &Program) -> Vec<OperationalMode> {
    extract_operating_modes(program)
        .iter()
        .map(|m| match m.kind {
            ModeKind::Normal => OperationalMode::NormalMode,
            ModeKind::Degraded => OperationalMode::DegradedMode,
            ModeKind::Safe => OperationalMode::SafeMode,
            ModeKind::Emergency => OperationalMode::EmergencyMode,
            ModeKind::Recovery => OperationalMode::RecoveryMode,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use spanda_lexer::tokenize;
    use spanda_parser::parse;

    fn parse_source(source: &str) -> Program {
        parse(tokenize(source).unwrap()).unwrap()
    }

    const RECOVERY_ROVER: &str = r#"
hardware RoverV1 {
    sensors [GPS, Camera, Lidar];
    actuators [DifferentialDrive];
    connectivity [WiFi, LTE];
}

operating_mode NormalMode { normal; }
operating_mode DegradedMode { degraded; }
operating_mode SafeMode { safe; }
operating_mode RecoveryMode { recovery; }

recovery_policy RoverRecovery {
    on gps.failed {
        switch_to visual_odometry;
        reduce_speed 0.5 m/s;
        enter degraded_mode;
    }
}

robot Rover {
    sensor gps: GPS;
    sensor camera: Camera;
    sensor lidar: Lidar;
    actuator wheels: DifferentialDrive;
    safety { max_speed = 1.2 m/s; }
    behavior patrol() { wheels.drive(0.5 m/s); }
}
"#;

    #[test]
    fn classifies_gps_failure() {
        assert_eq!(
            classify_failure("gps.failed"),
            FailureClassification::SensorFailure
        );
    }

    #[test]
    fn extracts_recovery_policy() {
        let program = parse_source(RECOVERY_ROVER);
        let policies = extract_recovery_policies(&program);
        assert!(!policies.is_empty());
        assert!(policies[0].triggers.iter().any(|(c, _)| c.contains("gps")));
    }

    #[test]
    fn planner_generates_gps_recovery_plan() {
        let program = parse_source(RECOVERY_ROVER);
        let ctx = RecoveryContext {
            issue: "gps.failed".into(),
            diagnosis: Some("Satellite lock lost".into()),
            classification: Some(FailureClassification::SensorFailure),
            level: RecoveryLevel::Level2AutomaticLowRisk,
        };
        let plan = RecoveryPlanner::plan(&program, &ctx);
        assert_eq!(plan.diagnosis, "Satellite lock lost");
        assert!(!plan.actions.is_empty());
        assert_eq!(plan.risk, "Low");
    }

    #[test]
    fn validation_gates_run() {
        let program = parse_source(RECOVERY_ROVER);
        let ctx = RecoveryContext {
            issue: "gps.failed".into(),
            diagnosis: None,
            classification: None,
            level: RecoveryLevel::Level2AutomaticLowRisk,
        };
        let plan = RecoveryPlanner::plan(&program, &ctx);
        let safe = validate_recovery_plan(&program, &plan);
        assert!(!safe.is_empty());
        assert!(safe.iter().all(|a| a.safety_validation.passed));
    }

    #[test]
    fn execute_recovery_produces_evidence() {
        let program = parse_source(RECOVERY_ROVER);
        let report = simulate_failure_recovery(&program, "gps");
        assert!(!report.results.is_empty());
        assert_eq!(report.results[0].evidence.safety_validation, "PASS");
    }
}
