//! Spanda language reference generator (JavaDoc / man-page style).
//!
//! Emits markdown from the compiler's source of truth: std namespaces, builtins,
//! type methods, object properties, keywords, and CLI commands.

use crate::builtin_methods::BUILTIN_METHODS;
use spanda_lexer::reserved_keywords;
use spanda_lib_registry::list_libraries;
use spanda_typecheck::type_system::std_namespaces;
use spanda_typecheck::{
    format_type_name, MethodSig, BUILTIN_FUNCTIONS, OBJECT_PROPERTIES, ROBOT_METHODS,
    SCAN_PROPERTIES,
};
use std::collections::BTreeMap;

/// Generate the full Spanda language reference as Markdown.
pub fn generate_language_reference() -> String {
    // Description:
    //     Generate language reference.
    //
    // Inputs:
    //     None.
    //
    // Outputs:
    //     result: String
    //         Return value from `generate_language_reference`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::generate_language_reference();

    let mut out = String::new();
    render_header(&mut out);
    render_toc(&mut out);
    render_keywords(&mut out);
    render_triggers(&mut out);
    render_std_library(&mut out);
    render_global_functions(&mut out);
    render_robot_methods(&mut out);
    render_type_methods(&mut out);
    render_object_properties(&mut out);
    render_scan_properties(&mut out);
    render_hardware_libraries(&mut out);
    render_cli_reference(&mut out);
    out
}

fn render_header(out: &mut String) {
    // Description:
    //     Render header.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_header(o);

    out.push_str("# Spanda Language Reference\n\n");
    out.push_str(
        "Complete reference for the Spanda language (`.sd`): reserved words, triggers, \
         `std.*` packages, global functions, built-in methods, and the `spanda` CLI.\n\n",
    );
    out.push_str(
        "Structured like **JavaDoc** (hierarchical packages and types) and **man pages** \
         (NAME / SYNOPSIS / DESCRIPTION / OPTIONS for CLI commands).\n\n",
    );
    out.push_str(
        "> Generated by `spanda reference` / `scripts/generate_spanda_reference.py`. \
         Signatures come from the type checker (`spanda-core`).\n\n",
    );
    out.push_str(
        "See also: [spanda-language.md](./spanda-language.md) (tutorial-style guide), \
         [standard-library.md](./standard-library.md) (stdlib overview), \
         [spanda-type-system.md](./spanda-type-system.md) (type rules).\n\n",
    );
}

fn render_toc(out: &mut String) {
    // Description:
    //     Render toc.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_toc(o);

    out.push_str("## Contents\n\n");
    out.push_str("- [Keywords](#keywords)\n");
    out.push_str("- [Triggers](#triggers)\n");
    out.push_str("- [Standard library (`std.*`)](#standard-library-std)\n");
    out.push_str("- [Global functions](#global-functions)\n");
    out.push_str("- [Robot methods](#robot-methods)\n");
    out.push_str("- [Type methods](#type-methods)\n");
    out.push_str("- [Object properties](#object-properties)\n");
    out.push_str("- [Scan properties](#scan-properties)\n");
    out.push_str("- [Hardware sensor libraries](#hardware-sensor-libraries)\n");
    out.push_str("- [CLI reference (man pages)](#cli-reference-man-pages)\n\n");
}

fn render_keywords(out: &mut String) {
    // Description:
    //     Render keywords.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_keywords(o);

    out.push_str("## Keywords\n\n");
    out.push_str(
        "Reserved words recognized by the Spanda lexer. Identifiers cannot reuse these names.\n\n",
    );

    let groups: [(&str, &[&str]); 8] = [
        (
            "Modules and visibility",
            &["module", "import", "export", "public", "private", "use"],
        ),
        (
            "Types and generics",
            &[
                "struct", "enum", "trait", "impl", "for", "dyn", "fn", "async", "await", "return",
            ],
        ),
        (
            "Robot graph",
            &[
                "robot", "behavior", "sensor", "actuator", "ai_model", "agent", "safety", "twin",
                "topic", "service", "action", "message", "node", "device", "bus",
            ],
        ),
        (
            "Triggers and tasks",
            &[
                "on",
                "every",
                "when",
                "task",
                "spawn",
                "select",
                "parallel",
                "priority",
                "entered",
                "exited",
                "event",
                "subscribe",
                "publish",
                "receive",
            ],
        ),
        (
            "Control flow",
            &[
                "let", "if", "else", "match", "loop", "while", "and", "or", "not", "true", "false",
            ],
        ),
        (
            "Safety and verification",
            &[
                "verify",
                "observe",
                "emergency_stop",
                "reset_emergency_stop",
                "stop_if",
                "requires",
                "ensures",
                "invariant",
                "can",
                "warning",
            ],
        ),
        (
            "Reliability and realtime",
            &[
                "pipeline",
                "watchdog",
                "recover",
                "retry",
                "fallback",
                "fault",
                "mission",
                "deadline",
                "timing",
                "min_period",
                "duration",
                "jitter",
                "isolated",
                "backoff",
                "times",
                "mode",
            ],
        ),
        (
            "Hardware and deploy",
            &[
                "hardware",
                "deploy",
                "hal",
                "soc",
                "requires_hardware",
                "requires_network",
                "simulate_compatibility",
                "budget",
                "cpu",
                "storage",
                "gpu",
                "battery",
                "capacity",
                "sensors",
                "actuators",
                "network",
                "bandwidth",
                "latency",
            ],
        ),
    ];

    let reserved: std::collections::HashSet<&str> = reserved_keywords().into_iter().collect();
    let mut listed = std::collections::HashSet::new();

    for (title, words) in groups {
        out.push_str(&format!("### {title}\n\n"));
        for word in words {
            if reserved.contains(word) {
                out.push_str(&format!("- `{word}`\n"));
                listed.insert(*word);
            }
        }
        out.push('\n');
    }

    out.push_str("### Other reserved words\n\n");
    for word in reserved_keywords() {
        if !listed.contains(word) {
            out.push_str(&format!("- `{word}`\n"));
        }
    }
    out.push('\n');
}

fn render_triggers(out: &mut String) {
    // Description:
    //     Render triggers.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_triggers(o);

    out.push_str("## Triggers\n\n");
    out.push_str(
        "Unified reactive handlers on robots and agents. See [triggers.md](./triggers.md).\n\n",
    );
    out.push_str("| Form | Syntax | Fires when |\n");
    out.push_str("|------|--------|------------|\n");
    out.push_str("| Event | `on event_name { ... }` | Named event is emitted |\n");
    out.push_str("| Message | `on message topic_name { ... }` | Message received on topic |\n");
    out.push_str("| Timer | `every 100 ms { ... }` | Periodic wall-clock interval |\n");
    out.push_str("| Condition | `when condition { ... }` | Boolean expression becomes true |\n");
    out.push_str("| State | `on entered StateName { ... }` | State machine enters state |\n");
    out.push_str("| State | `on exited StateName { ... }` | State machine exits state |\n");
    out.push_str("| Safety | `on safety event_name { ... }` | Safety subsystem event |\n");
    out.push_str("| Hardware | `on hardware event_name { ... }` | HAL / hardware event |\n");
    out.push_str("| AI | `on ai event_name { ... }` | AI runtime event |\n");
    out.push_str("| Twin | `on twin event_name { ... }` | Digital twin event |\n");
    out.push_str("| Log match | `on log matches /pattern/ { ... }` | Log line matches regex |\n");
    out.push_str(
        "| Message match | `on message field matches /pattern/ { ... }` | Topic field matches regex |\n\n",
    );
}

fn namespace_summary(ns: &str) -> &'static str {
    // Description:
    //     Namespace summary.
    //
    // Inputs:
    //     ns: &str
    //         Caller-supplied ns.
    //
    // Outputs:
    //     result: &'static str
    //         Return value from `namespace_summary`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::namespace_summary(ns);

    match ns {
        "std.core" => "Foundation types: results, options, errors.",
        "std.time" => "Time, duration, timestamps, and intervals.",
        "std.units" => "Physical units: distance, velocity, mass, temperature, and more.",
        "std.spatial" => "Geometry: poses, transforms, paths, trajectories.",
        "std.math" => "Scalar math types.",
        "std.collections" => "Containers: arrays, maps, sets, queues.",
        "std.result" => "Error-handling types.",
        "std.io" => "File and stream abstractions.",
        "std.log" => "Structured logging.",
        "std.ai" => "AI models, prompts, completions, reasoning traces.",
        "std.robotics" => "Robot graph: motion, agents, goals, safe actions.",
        "std.sensors" => "Sensor payload types (LiDAR, camera, IMU, …).",
        "std.actuators" => "Actuator types: motors, servos, grippers.",
        "std.safety" => "Risk, hazards, constraints, emergency stop.",
        "std.communication" => "Topics, services, actions, events, bus.",
        "std.hardware" => "Deploy targets and compatibility reports.",
        "std.sim" => "Simulation worlds, scenarios, replay buffers.",
        "std.twin" => "Digital twin state and telemetry.",
        "std.hri" => "Human–robot interaction: commands, intent, approval.",
        "std.security" => "Identity, permissions, signatures, trust.",
        "std.audit" => "Audit logs, provenance, mission records.",
        "std.crypto" => "Hashing and signature primitives.",
        "std.network" => "Transport, QoS, endpoints, discovery.",
        _ => "Standard library namespace.",
    }
}

fn render_std_library(out: &mut String) {
    // Description:
    //     Render std library.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_std_library(o);

    out.push_str("## Standard library (`std.*`)\n\n");
    out.push_str(
        "Import with `import std.robotics;` (or any namespace below). Types resolve with or \
         without the `std.<module>.` prefix.\n\n",
    );

    let mut namespaces: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (ns, types) in std_namespaces() {
        let entry = namespaces.entry(ns).or_default();
        for ty in types.iter().copied() {
            if !entry.contains(&ty) {
                entry.push(ty);
            }
        }
    }

    let type_methods = BUILTIN_METHODS();
    for (ns, types) in &namespaces {
        let anchor = ns.replace('.', "-");
        out.push_str(&format!("### `{ns}` {{#{anchor}}}\n\n"));
        out.push_str(namespace_summary(ns));
        out.push_str("\n\n");
        out.push_str("**Types**\n\n");
        for ty in types {
            if let Some(m) = type_methods.get(*ty) {
                out.push_str(&format!(
                    "- [`{ty}`](#type-{ty}) — {method_count} method(s)\n",
                    method_count = m.len()
                ));
            } else {
                out.push_str(&format!("- `{ty}`\n"));
            }
        }
        out.push('\n');
    }
}

fn format_named_params(named: &BTreeMap<String, String>) -> String {
    // Description:
    //     Format named params.
    //
    // Inputs:
    //     named: &BTreeMap<String, String>
    //         Caller-supplied named.
    //
    // Outputs:
    //     result: String
    //         Return value from `format_named_params`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::format_named_params(named);

    named
        .iter()
        .map(|(k, v)| format!("{k}: {v}"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn format_fn_sig(name: &str, named: &BTreeMap<String, String>, returns: &str) -> String {
    // Description:
    //     Format fn sig.
    //
    // Inputs:
    //     name: &str
    //         Caller-supplied name.
    //     named: &BTreeMap<String, String>
    //         Caller-supplied named.
    //     returns: &str
    //         Caller-supplied returns.
    //
    // Outputs:
    //     result: String
    //         Return value from `format_fn_sig`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::format_fn_sig(name, named, returns);

    let params = format_named_params(named);
    if params.is_empty() {
        format!("fn {name}() -> {returns}")
    } else {
        format!("fn {name}({params}) -> {returns}")
    }
}

fn format_method_sig(
    receiver: &str,
    name: &str,
    positional: &[String],
    named: &BTreeMap<String, String>,
    returns: &str,
) -> String {
    // Description:
    //     Format method sig.
    //
    // Inputs:
    //     receiver: &str
    //         Caller-supplied receiver.
    //     name: &str
    //         Caller-supplied name.
    //     positional: &[String]
    //         Caller-supplied positional.
    //     named: &BTreeMap<String, String>
    //         Caller-supplied named.
    //     returns: &str
    //         Caller-supplied returns.
    //
    // Outputs:
    //     result: String
    //         Return value from `format_method_sig`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::format_method_sig(receiver, name, positional, named, returns);

    let mut parts = positional.to_vec();
    for (k, v) in named {
        parts.push(format!("{k}: {v}"));
    }
    let params = parts.join(", ");
    format!("{receiver}.{name}({params}) -> {returns}")
}

fn collect_method_sig(method: &MethodSig) -> (Vec<String>, BTreeMap<String, String>, String) {
    // Description:
    //     Collect method sig.
    //
    // Inputs:
    //     ethod: &MethodSig
    //         Caller-supplied ethod.
    //
    // Outputs:
    //     result: (Vec<String>, BTreeMap<String, String>, String)
    //         Return value from `collect_method_sig`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::collect_method_sig(ethod);

    let positional: Vec<String> = method.params().iter().map(format_type_name).collect();
    let named: BTreeMap<String, String> = method
        .named_params()
        .iter()
        .map(|(k, v)| (k.clone(), format_type_name(v)))
        .collect();
    (positional, named, format_type_name(method.returns()))
}

fn fn_description(name: &str) -> &'static str {
    // Description:
    //     Fn description.
    //
    // Inputs:
    //     name: &str
    //         Caller-supplied name.
    //
    // Outputs:
    //     result: &'static str
    //         Return value from `fn_description`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::fn_description(name);

    match name {
        "pose" => "Construct a `Pose` from coordinates (optional `z`).",
        "velocity" => "Construct a `Velocity` from linear and angular components.",
        "trajectory" => "Interpolate a path between two poses.",
        "transform" => "Transform a pose between coordinate frames.",
        "goal" => "Create an agent goal from text.",
        "recall" => "Recall a value from agent memory by key.",
        "channel" => "Create an async channel for task communication.",
        "send" => "Send a value on a channel.",
        "recv" => "Receive a value from a channel.",
        "send_agent" => "Send a message to another agent.",
        "recv_agent" => "Receive a message from another agent.",
        "peer_send" => "Publish to a peer robot over the fleet bus.",
        "serialize" => "Serialize a value to string (format parameter).",
        "deserialize" => "Deserialize a value from string (format parameter).",
        "assert" => "Assert a condition at runtime (test / verify blocks).",
        _ => "Built-in global function.",
    }
}

fn method_description(type_name: &str, method: &str) -> &'static str {
    // Description:
    //     Method description.
    //
    // Inputs:
    //     ype_name: &str
    //         Caller-supplied ype name.
    //     ethod: &str
    //         Caller-supplied ethod.
    //
    // Outputs:
    //     result: &'static str
    //         Return value from `method_description`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::method_description(ype_name, ethod);

    match (type_name, method) {
        ("Robot", "pose") => "Current robot pose.",
        ("Robot", "velocity") => "Current robot velocity.",
        ("Robot", "in_zone") => "True when the robot is inside a named zone.",
        ("Robot", "identity") => "Robot identity for signing and audit.",
        ("DifferentialDrive", "drive") => "Drive with linear and angular velocity.",
        ("DifferentialDrive", "stop") => "Stop all motion.",
        ("DifferentialDrive", "follow") => "Follow a trajectory path.",
        ("DifferentialDrive", "execute") => "Execute a safety-validated action.",
        ("Lidar", "read") | ("Camera", "read") | ("IMU", "read") => "Read latest sensor data.",
        ("LLM", "reason") => "Run LLM reasoning over sensor input and goal.",
        ("LLM", "summarize") => "Summarize sensor input.",
        ("Safety", "validate") => "Validate an action proposal; returns a safe action.",
        ("Twin", "mirror") => "Mirror a field from the digital twin.",
        ("Twin", "replay") => "Replay twin state at an index.",
        _ => "Built-in method.",
    }
}

fn render_global_functions(out: &mut String) {
    // Description:
    //     Render global functions.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_global_functions(o);

    out.push_str("## Global functions\n\n");
    out.push_str("Top-level functions available in every Spanda program.\n\n");

    let builtins = BUILTIN_FUNCTIONS();
    let mut names: Vec<_> = builtins.keys().copied().collect();
    names.sort_unstable();

    for name in names {
        let sig = builtins.get(name).expect("builtin fn");
        let mut named = BTreeMap::new();
        for (k, v) in sig.named_params() {
            named.insert(k.clone(), format_type_name(v));
        }
        let signature = format_fn_sig(name, &named, &format_type_name(sig.returns()));
        out.push_str(&format!("### `{name}` {{#fn-{name}}}\n\n"));
        out.push_str("```spanda\n");
        out.push_str(&signature);
        out.push_str("\n```\n\n");
        out.push_str(fn_description(name));
        out.push_str("\n\n");
    }
}

fn render_robot_methods(out: &mut String) {
    // Description:
    //     Render robot methods.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_robot_methods(o);

    out.push_str("## Robot methods\n\n");
    out.push_str("Methods on the implicit `robot` receiver inside `behavior` blocks.\n\n");

    let robot_methods = ROBOT_METHODS();
    let mut names: Vec<_> = robot_methods.keys().copied().collect();
    names.sort_unstable();

    for name in names {
        let sig = robot_methods.get(name).expect("robot method");
        let (positional, named, returns) = collect_method_sig(sig);
        let signature = format_method_sig("robot", name, &positional, &named, &returns);
        out.push_str(&format!("### `robot.{name}` {{#robot-{name}}}\n\n"));
        out.push_str("```spanda\n");
        out.push_str(&signature);
        out.push_str("\n```\n\n");
        out.push_str(method_description("Robot", name));
        out.push_str("\n\n");
    }
}

fn render_type_methods(out: &mut String) {
    // Description:
    //     Render type methods.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_type_methods(o);

    out.push_str("## Type methods\n\n");
    out.push_str(
        "Built-in methods on sensor, actuator, AI, safety, and twin types. \
         Actuator/sensor instances use the type declared in the robot graph.\n\n",
    );

    let methods = BUILTIN_METHODS();
    let mut type_names: Vec<_> = methods.keys().cloned().collect();
    type_names.sort_unstable();

    for type_name in type_names {
        let Some(type_methods) = methods.get(&type_name) else {
            continue;
        };
        out.push_str(&format!("### `{type_name}` {{#type-{type_name}}}\n\n"));

        let mut method_names: Vec<_> = type_methods.keys().cloned().collect();
        method_names.sort_unstable();

        for method_name in method_names {
            let sig = type_methods.get(&method_name).expect("method");
            let (positional, named, returns) = collect_method_sig(sig);
            let signature = format_method_sig(
                &type_name.to_lowercase(),
                &method_name,
                &positional,
                &named,
                &returns,
            );
            out.push_str(&format!(
                "#### `{method_name}` {{#type-{type_name}-{method_name}}}\n\n"
            ));
            out.push_str("```spanda\n");
            out.push_str(&signature);
            out.push_str("\n```\n\n");
            out.push_str(method_description(&type_name, &method_name));
            out.push_str("\n\n");
        }
    }
}

fn render_object_properties(out: &mut String) {
    // Description:
    //     Render object properties.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_object_properties(o);

    out.push_str("## Object properties\n\n");
    out.push_str("Fields on structured runtime values returned by sensors and AI.\n\n");

    let props = OBJECT_PROPERTIES();
    let mut type_names: Vec<_> = props.keys().cloned().collect();
    type_names.sort_unstable();

    for type_name in type_names {
        let Some(fields) = props.get(&type_name) else {
            continue;
        };
        out.push_str(&format!("### `{type_name}`\n\n"));
        out.push_str("| Field | Type |\n|-------|------|\n");
        let mut field_names: Vec<_> = fields.keys().cloned().collect();
        field_names.sort_unstable();
        for field in field_names {
            let ty = fields.get(&field).expect("field type");
            out.push_str(&format!("| `{field}` | `{}` |\n", format_type_name(ty)));
        }
        out.push('\n');
    }
}

fn render_scan_properties(out: &mut String) {
    // Description:
    //     Render scan properties.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_scan_properties(o);

    out.push_str("## Scan properties\n\n");
    out.push_str("Fields on LiDAR `Scan` values.\n\n");
    out.push_str("| Field | Type |\n|-------|------|\n");
    for (field, ty) in SCAN_PROPERTIES() {
        out.push_str(&format!("| `{field}` | `{}` |\n", format_type_name(&ty)));
    }
    out.push('\n');
}

fn render_hardware_libraries(out: &mut String) {
    // Description:
    //     Render hardware libraries.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_hardware_libraries(o);

    out.push_str("## Hardware sensor libraries\n\n");
    out.push_str(
        "Vendor sensor drivers registered in the runtime. Each sensor type exposes \
         `read()` and `calibrate()` unless noted otherwise.\n\n",
    );

    let mut by_vendor: BTreeMap<String, Vec<_>> = BTreeMap::new();
    for lib in list_libraries() {
        by_vendor.entry(lib.vendor.clone()).or_default().push(lib);
    }

    for (vendor, libs) in by_vendor {
        out.push_str(&format!("### {vendor}\n\n"));
        for lib in libs {
            out.push_str(&format!(
                "#### `{id}` — {name} v{version}\n\n",
                id = lib.id,
                name = lib.name,
                version = lib.version
            ));
            out.push_str(&lib.description);
            out.push_str("\n\n");
            if !lib.sensors.is_empty() {
                out.push_str("| Sensor type | Model | Interfaces |\n");
                out.push_str("|-------------|-------|------------|\n");
                let mut sensors: Vec<_> = lib.sensors.values().collect();
                sensors.sort_by(|a, b| a.sensor_type.cmp(&b.sensor_type));
                for sensor in sensors {
                    let ifaces: Vec<_> = sensor.interfaces.iter().map(|i| i.as_str()).collect();
                    out.push_str(&format!(
                        "| `{}` | {} | {} |\n",
                        sensor.sensor_type,
                        sensor.model,
                        ifaces.join(", ")
                    ));
                }
                out.push('\n');
            }
        }
    }
}

struct CliCommand {
    name: &'static str,
    section: u8,
    synopsis: &'static str,
    description: &'static str,
    options: &'static str,
    examples: &'static str,
    exit_status: &'static str,
    files: &'static str,
    see_also: &'static str,
}

/// Registered CLI command names (for man-page lint and tests).
pub const CLI_COMMAND_NAMES: &[&str] = &[
    "spanda",
    "spanda-check",
    "spanda-verify",
    "spanda-run",
    "spanda-sim",
    "spanda-replay",
    "spanda-test",
    "spanda-readiness",
    "spanda-assure",
    "spanda-diagnose",
    "spanda-heal",
    "spanda-continuity",
    "spanda-fleet",
    "spanda-package",
    "spanda-trace",
    "spanda-security",
    "spanda-fmt",
    "spanda-lint",
    "spanda-doc",
    "spanda-man",
    "spanda-reference",
    "spanda-codegen",
    "spanda-debug",
];

const CLI_COMMANDS: &[CliCommand] = &[
    CliCommand {
        name: "spanda-check",
        section: 1,
        synopsis: "spanda check [--json] [<file.sd> | --project]",
        description: "Type-check and parse a Spanda program or project.",
        options: "`--json` — machine-readable diagnostics\n`--readiness-json` — readiness + recovery + continuity policy hints\n`--project` — check all modules in the current project",
        examples: "spanda check examples/rover.sd\nspanda check --project",
        exit_status: "0 on success; 1 on parse, type, or lint errors.",
        files: "`spanda.toml` — project manifest when using `--project`",
        see_also: "spanda-verify(1), spanda-run(1), spanda-continuity(1)",
    },
    CliCommand {
        name: "spanda-verify",
        section: 1,
        synopsis: "spanda verify [--json] [--target <profile>] [--all-targets] [--simulate] <file.sd>",
        description: "Verify hardware compatibility and safety constraints for a deploy target.",
        options: "`--target` — hardware profile name\n`--all-targets` — compatibility matrix\n`--simulate` — include simulator checks\n`--json` — JSON report",
        examples: "spanda verify robot.sd --target RoverV1\nspanda verify robot.sd --all-targets --simulate",
        exit_status: "0 when compatible; 1 on verification failures or errors.",
        files: "Hardware profile definitions in the program or `hardware/` package paths.",
        see_also: "spanda-check(1), spanda-run(1)",
    },
    CliCommand {
        name: "spanda-run",
        section: 1,
        synopsis: "spanda run [--json] [--verbose] [--trace-*] [--record] <file.sd>",
        description: "Execute a Spanda program on the interpreter backend.",
        options: "`--trace-scheduler`, `--trace-tasks`, `--trace-triggers`, `--trace-events` — scheduler telemetry\n`--trace-realtime`, `--metrics-json` — realtime metrics\n`--record` — write mission trace",
        examples: "spanda run examples/rover.sd\nspanda run robot.sd --trace-realtime --metrics-json",
        exit_status: "0 on successful execution; 1 on runtime or compile errors.",
        files: "Mission traces when using `--record` (default: `mission.trace`).",
        see_also: "spanda-sim(1), spanda-replay(1)",
    },
    CliCommand {
        name: "spanda-sim",
        section: 1,
        synopsis: "spanda sim [--json] [--replay] [--wall-clock] [--record] [--trace-*] <file.sd>",
        description: "Run a program in the built-in simulator with optional trace recording.",
        options: "`--replay` — replay mode\n`--wall-clock` — real-time pacing\n`--record` — mission trace output",
        examples: "spanda sim examples/rover.sd --record\nspanda sim robot.sd --wall-clock",
        exit_status: "0 on successful simulation; 1 on errors.",
        files: "Mission traces when using `--record`.",
        see_also: "spanda-run(1), spanda-replay(1)",
    },
    CliCommand {
        name: "spanda-replay",
        section: 1,
        synopsis: "spanda replay <mission.trace> [--from T+mm:ss] [--deterministic] [--playback]",
        description: "Replay or deterministically verify a recorded mission trace.",
        options: "`--from` — start offset\n`--deterministic` — verify reproducibility\n`--playback` — frame-by-frame playback",
        examples: "spanda replay mission.trace --deterministic\nspanda replay mission.trace --playback --from T+00:30",
        exit_status: "0 when replay succeeds or deterministic check passes; 1 otherwise.",
        files: "Input mission trace file (`.trace`).",
        see_also: "spanda-sim(1), spanda-run(1)",
    },
    CliCommand {
        name: "spanda-test",
        section: 1,
        synopsis: "spanda test [--project <dir>]",
        description: "Run in-language `test` blocks and package test suites for a Spanda project.",
        options: "`--project` — project root (default: current directory)",
        examples: "spanda test\nspanda test --project examples/rover",
        exit_status: "0 when all tests pass; 1 on failures.",
        files: "`spanda.toml`, `spanda.lock`, project `.sd` sources.",
        see_also: "spanda-check(1), spanda-package(1)",
    },
    CliCommand {
        name: "spanda-readiness",
        section: 1,
        synopsis: "spanda readiness [--json] [--readiness-json] <file.sd>",
        description: "Evaluate operational readiness: health, safety, fleet, and deployment gates.",
        options: "`--json` / `--readiness-json` — structured readiness report",
        examples: "spanda readiness robot.sd --readiness-json",
        exit_status: "0 when ready; 1 when blocking issues are found.",
        files: "Readiness reports may reference `spanda.toml` safety metadata.",
        see_also: "spanda-verify(1), spanda-assure(1)",
    },
    CliCommand {
        name: "spanda-assure",
        section: 1,
        synopsis: "spanda assure [--json] <file.sd>",
        description: "Run assurance workflows: anomaly coverage, prognostics, and assurance cases.",
        options: "`--json` — machine-readable assurance report",
        examples: "spanda assure robot.sd --json",
        exit_status: "0 when assurance checks pass; 1 on gaps or violations.",
        files: "Assurance metadata in program declarations.",
        see_also: "spanda-readiness(1), spanda-diagnose(1)",
    },
    CliCommand {
        name: "spanda-diagnose",
        section: 1,
        synopsis: "spanda diagnose [--json] <file.sd> [<mission.trace>]",
        description: "Diagnose failures from static analysis and optional mission traces.",
        options: "`--json` — structured diagnosis report",
        examples: "spanda diagnose robot.sd\nspanda diagnose robot.sd mission.trace",
        exit_status: "0 when diagnosis completes; 1 on errors.",
        files: "Optional mission trace input.",
        see_also: "spanda-assure(1), spanda-heal(1)",
    },
    CliCommand {
        name: "spanda-heal",
        section: 1,
        synopsis: "spanda heal [--json] <file.sd>",
        description: "Execute self-healing and recovery policies declared in the program.",
        options: "`--json` — recovery report",
        examples: "spanda heal robot.sd --json",
        exit_status: "0 when recovery succeeds; 1 on unrecoverable faults.",
        files: "Recovery policies in `.sd` source.",
        see_also: "spanda-diagnose(1), spanda-recovery(1)",
    },
    CliCommand {
        name: "spanda-continuity",
        section: 1,
        synopsis: "spanda continuity|takeover|delegate|succession <file.sd> [options]",
        description: "Mission continuity, takeover, delegation, and succession planning.",
        options: "`--failed <name>` — failed robot or entity\n`--progress <pct>` — mission progress percent\n`--trigger <kind>` — continuity trigger (e.g. `robot_failed`)\n`--successor` / `--to <name>` — designated successor for takeover/delegate\n`--scope fleet|swarm|robot` — succession scope\n`--json` / `--markdown` / `--html` — report format",
        examples: "spanda continuity examples/showcase/continuity/warehouse.sd --failed ScannerAlpha --progress 72\nspanda takeover examples/showcase/takeover/patrol.sd --failed RoverA\nspanda delegate examples/showcase/delegation/survey.sd --failed SurveyBot --to RelayBot\nspanda succession examples/showcase/fleet_succession/delivery.sd --scope fleet\nspanda demo continuity",
        exit_status: "0 when planning succeeds; 1 on validation or safety gate failures.",
        files: "`continuity_policy` and `mission_plan` declarations in `.sd` source.",
        see_also: "spanda-recovery(1), spanda-fleet(1), [mission-continuity.md](../mission-continuity.md)",
    },
    CliCommand {
        name: "spanda-fleet",
        section: 1,
        synopsis: "spanda fleet run [--json] [--trace-*] <file.sd>",
        description: "Run a multi-robot fleet program with peer communication.",
        options: "Same trace flags as `spanda run`.",
        examples: "spanda fleet run examples/communication/multi_robot_fleet.sd",
        exit_status: "0 on successful fleet run; 1 on errors.",
        files: "Fleet mesh state when using remote agents.",
        see_also: "spanda-run(1)",
    },
    CliCommand {
        name: "spanda-package",
        section: 1,
        synopsis: "spanda <init|build|test|add|remove|install|publish|registry> [options]",
        description: "Manage Spanda packages: manifests, dependencies, builds, and registry operations.",
        options: "See `spanda init`, `build`, `test`, `add`, `remove`, `install`, `publish`, `registry search`, `registry info`.",
        examples: "spanda init my-robot\nspanda add std.robotics\nspanda publish",
        exit_status: "0 on success; 1 on manifest, lockfile, or registry errors.",
        files: "`spanda.toml`, `spanda.lock`, `packages/` registry mirror.",
        see_also: "spanda-check(1), spanda-test(1)",
    },
    CliCommand {
        name: "spanda-trace",
        section: 1,
        synopsis: "spanda trace [--json] [--out <file>] <file.sd>",
        description: "Record scheduler, task, trigger, and event traces from a program run.",
        options: "`--out` — trace output path\n`--json` — structured trace summary",
        examples: "spanda trace robot.sd --out mission.trace",
        exit_status: "0 on success; 1 on runtime errors.",
        files: "Output trace file (`.trace`).",
        see_also: "spanda-replay(1), spanda-run(1)",
    },
    CliCommand {
        name: "spanda-security",
        section: 1,
        synopsis: "spanda security <check|audit> [--json] <file.sd>",
        description: "Validate security policies, identities, and audit configuration.",
        options: "`check` — static security validation\n`audit` — audit log review\n`--json` — machine-readable report",
        examples: "spanda security check robot.sd --json\nspanda security audit robot.sd",
        exit_status: "0 when policies pass; 1 on violations.",
        files: "Security metadata in program and `spanda.toml` when present.",
        see_also: "spanda-verify(1), spanda-readiness(1)",
    },
    CliCommand {
        name: "spanda-fmt",
        section: 1,
        synopsis: "spanda fmt [--json] <file.sd>",
        description: "Format Spanda source to canonical style.",
        options: "`--json` — report whether the file changed",
        examples: "spanda fmt examples/rover.sd",
        exit_status: "0 on success; 1 on parse errors.",
        files: "In-place `.sd` source file.",
        see_also: "spanda-check(1)",
    },
    CliCommand {
        name: "spanda-lint",
        section: 1,
        synopsis: "spanda lint [--json] <file.sd>",
        description: "Run linter rules beyond parse/type checking.",
        options: "`--json` — structured lint report",
        examples: "spanda lint robot.sd",
        exit_status: "0 when no lint issues; 1 when issues are found.",
        files: "Input `.sd` source file.",
        see_also: "spanda-check(1)",
    },
    CliCommand {
        name: "spanda-doc",
        section: 1,
        synopsis: "spanda doc [--json] [--html] [--out <file>] <file.sd|dir/>",
        description: "Generate JavaDoc-style API docs for `.sd` modules (markdown or HTML).",
        options: "`--out` — write output file or directory\n`--html` — emit HTML instead of markdown\n`--json` — wrap output in JSON",
        examples: "spanda doc module.sd --out module-api.md\nspanda doc --html examples/",
        exit_status: "0 on success; 1 on lex/parse errors.",
        files: "Output docs under `--out` or stdout.",
        see_also: "spanda-reference(1), spanda-man(1)",
    },
    CliCommand {
        name: "spanda-man",
        section: 1,
        synopsis: "spanda man [<command>] [--roff]",
        description: "Display man-page style documentation for Spanda CLI commands.",
        options: "`--roff` — emit roff for Unix `man` viewers\nNo argument — list available pages",
        examples: "spanda man\nspanda man verify\nspanda man run --roff",
        exit_status: "0 on success; 1 when the command page is not found.",
        files: "Man pages are generated from compiler metadata into `docs/man/`.",
        see_also: "spanda-reference(1), spanda-doc(1)",
    },
    CliCommand {
        name: "spanda-reference",
        section: 1,
        synopsis: "spanda reference [--json] [--out <file.md>] [--man-dir <dir>]",
        description: "Emit the full Spanda language reference and optional man pages.",
        options: "`--out` — write reference markdown\n`--man-dir` — write man pages\n`--json` — wrap markdown in JSON",
        examples: "spanda reference --out docs/spanda-reference.md --man-dir docs/man",
        exit_status: "0 on success.",
        files: "`docs/spanda-reference.md`, `docs/man/` when generating.",
        see_also: "spanda-doc(1), spanda-man(1)",
    },
    CliCommand {
        name: "spanda-codegen",
        section: 1,
        synopsis: "spanda codegen [--target native|wasm|esp32] [--out <file>] <file.sd>",
        description: "Generate deployable artifacts from a Spanda program.",
        options: "`--target` — output format",
        examples: "spanda codegen --target wasm robot.sd --out robot.wasm",
        exit_status: "0 on success; 1 on codegen errors.",
        files: "Generated artifact at `--out`.",
        see_also: "spanda-deploy(1), spanda-compile-native(1)",
    },
    CliCommand {
        name: "spanda-debug",
        section: 1,
        synopsis: "spanda debug [--break <line>] <file.sd>",
        description: "Start an interactive debug session.",
        options: "`--break` — initial breakpoint line",
        examples: "spanda debug robot.sd --break 42",
        exit_status: "0 on clean exit; 1 on errors.",
        files: "Debug session uses source `.sd` file.",
        see_also: "spanda-run(1)",
    },
];

fn render_cli_reference(out: &mut String) {
    // Description:
    //     Render cli reference.
    //
    // Inputs:
    //     o: &mut String
    //         Caller-supplied o.
    //
    // Outputs:
    //     None.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_cli_reference(o);

    out.push_str("## CLI reference (man pages)\n\n");
    out.push_str(
        "Manual-page style reference for the `spanda` command-line tool. \
         Individual pages also live under [man/](./man/).\n\n",
    );

    out.push_str("### spanda(1)\n\n");
    out.push_str("**NAME**\n\n");
    out.push_str("`spanda` — Spanda autonomous systems platform toolchain\n\n");
    out.push_str("**SYNOPSIS**\n\n");
    out.push_str("```\nspanda <command> [options] [arguments]\n```\n\n");
    out.push_str("**DESCRIPTION**\n\n");
    out.push_str(
        "The Spanda CLI drives the autonomous systems platform: check, verify, simulate, replay, fleet, and document `.sd` programs.\n\n",
    );
    out.push_str("**COMMANDS**\n\n");
    for cmd in CLI_COMMANDS {
        let short = cmd.name.strip_prefix("spanda-").unwrap_or(cmd.name);
        out.push_str(&format!("- [`{short}`](./man/{}.md)\n", cmd.name));
    }
    out.push_str("\nPackage commands: `init`, `build`, `test`, `add`, `remove`, `install`, `publish`, `registry search`, `registry info`. See [packages.md](./packages.md).\n\n");

    for cmd in CLI_COMMANDS {
        out.push_str(&render_single_man(cmd));
    }
}

fn render_single_man(cmd: &CliCommand) -> String {
    // Description:
    //     Render single man.
    //
    // Inputs:
    //     cmd: &CliCommand
    //         Caller-supplied cmd.
    //
    // Outputs:
    //     result: String
    //         Return value from `render_single_man`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::render_single_man(cmd);

    let short = cmd.name.strip_prefix("spanda-").unwrap_or(cmd.name);
    let anchor = short;
    let mut out = String::new();
    out.push_str(&format!(
        "### {}({}) {{#cli-{}}}\n\n",
        cmd.name, cmd.section, anchor
    ));
    out.push_str("**NAME**\n\n");
    out.push_str(&format!(
        "`{short}` — {}\n\n",
        cmd.description.lines().next().unwrap_or(cmd.description)
    ));
    out.push_str("**SYNOPSIS**\n\n");
    out.push_str("```\n");
    out.push_str(cmd.synopsis);
    out.push_str("\n```\n\n");
    out.push_str("**DESCRIPTION**\n\n");
    out.push_str(cmd.description);
    out.push_str("\n\n");
    out.push_str("**OPTIONS**\n\n");
    out.push_str(cmd.options);
    out.push_str("\n\n");
    out.push_str("**EXAMPLES**\n\n");
    out.push_str("```bash\n");
    out.push_str(cmd.examples);
    out.push_str("\n```\n\n");
    out.push_str("**EXIT STATUS**\n\n");
    out.push_str(cmd.exit_status);
    out.push_str("\n\n");
    out.push_str("**FILES**\n\n");
    out.push_str(cmd.files);
    out.push_str("\n\n");
    out.push_str("**SEE ALSO**\n\n");
    out.push_str(cmd.see_also);
    out.push_str("\n\n");
    out
}

/// Generate standalone man-page markdown files for CLI commands.
pub fn generate_cli_man_pages() -> Vec<(String, String)> {
    // Description:
    //     Generate cli man pages.
    //
    // Inputs:
    //     None.
    //
    // Outputs:
    //     result: Vec<(String, String)>
    //         Return value from `generate_cli_man_pages`.
    //
    // Example:

    //     let result = spanda_docs::language_reference::generate_cli_man_pages();

    let mut pages = Vec::new();

    let mut overview = String::new();
    overview.push_str("# spanda(1)\n\n");
    overview.push_str("## NAME\n\n");
    overview.push_str("spanda — Spanda autonomous systems platform toolchain\n\n");
    overview.push_str("## SYNOPSIS\n\n");
    overview.push_str("```\nspanda <command> [options] [arguments]\n```\n\n");
    overview.push_str("## DESCRIPTION\n\n");
    overview.push_str(
        "The Spanda CLI drives the autonomous systems platform: check, verify, simulate, replay, fleet, and document `.sd` programs.\n\n",
    );
    overview.push_str("## COMMANDS\n\n");
    for cmd in CLI_COMMANDS {
        let short = cmd.name.strip_prefix("spanda-").unwrap_or(cmd.name);
        overview.push_str(&format!("- **{short}** — {}\n", cmd.description));
    }
    overview.push_str("\nPackage commands: `init`, `build`, `test`, `add`, `remove`, `install`, `publish`, `registry search`, `registry info`.\n\n");
    overview.push_str("## SEE ALSO\n\n");
    overview.push_str("[spanda-reference.md](../spanda-reference.md), [getting-started.md](../getting-started.md)\n");
    pages.push(("spanda.md".into(), overview));

    for cmd in CLI_COMMANDS {
        let short = cmd.name.strip_prefix("spanda-").unwrap_or(cmd.name);
        let mut body = String::new();
        body.push_str(&format!("# {}(1)\n\n", cmd.name));
        body.push_str("## NAME\n\n");
        body.push_str(&format!("{short} — {}\n\n", cmd.description));
        body.push_str("## SYNOPSIS\n\n");
        body.push_str("```\n");
        body.push_str(cmd.synopsis);
        body.push_str("\n```\n\n");
        body.push_str("## DESCRIPTION\n\n");
        body.push_str(cmd.description);
        body.push_str("\n\n");
        body.push_str("## OPTIONS\n\n");
        body.push_str(cmd.options);
        body.push_str("\n\n");
        body.push_str("## EXAMPLES\n\n");
        body.push_str("```bash\n");
        body.push_str(cmd.examples);
        body.push_str("\n```\n\n");
        body.push_str("## EXIT STATUS\n\n");
        body.push_str(cmd.exit_status);
        body.push_str("\n\n");
        body.push_str("## FILES\n\n");
        body.push_str(cmd.files);
        body.push_str("\n\n");
        body.push_str("## SEE ALSO\n\n");
        body.push_str(cmd.see_also);
        body.push_str(
            ", [spanda(1)](./spanda.md), [spanda-reference.md](../spanda-reference.md)\n",
        );
        pages.push((format!("{}.md", cmd.name), body));
    }

    pages
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn language_reference_contains_core_sections() {
        // Description:
        //     Language reference contains core sections.
        //
        // Inputs:
        //     None.
        //
        // Outputs:
        //     None.
        //
        // Example:

        //     let result = spanda_docs::language_reference::language_reference_contains_core_sections();

        let md = generate_language_reference();
        assert!(md.contains("# Spanda Language Reference"));
        assert!(md.contains("## Keywords"));
        assert!(md.contains("## Global functions"));
        assert!(md.contains("fn pose("));
        assert!(md.contains("### `std.robotics`"));
        assert!(md.contains("## CLI reference"));
        assert!(md.contains("spanda-check"));
    }
}
