use crate::ast::*;
use crate::error::SpandaError;
use crate::foundations::{ExternFnDecl, ModuleFnDecl};
use crate::sir::SirProgram;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CodegenTarget {
    Native,
    Wasm,
    Esp32,
}

pub fn generate(source: &str, target: CodegenTarget) -> Result<String, SpandaError> {
    let tokens = crate::lexer::tokenize(source)?;
    let program = crate::parser::parse(tokens)?;
    crate::types::check(&program)?;
    let sir = crate::sir::lower_program(&program);
    Ok(render_from_sir(&sir, &program, target))
}

fn render_from_sir(sir: &SirProgram, program: &Program, target: CodegenTarget) -> String {
    match target {
        CodegenTarget::Native => render_native_sir(sir, program),
        CodegenTarget::Wasm => render_wasm_sir(sir),
        CodegenTarget::Esp32 => render_esp32(program),
    }
}

fn render_native_sir(sir: &SirProgram, program: &Program) -> String {
    let mut out = String::from("// Generated by spanda codegen --target native (SIR v1)\n");
    out.push_str("#include <stdint.h>\n\n");
    if let Some(name) = &sir.module_name {
        out.push_str(&format!("// module {name}\n"));
    }
    for import in &sir.imports {
        out.push_str(&format!("// import {import}\n"));
    }
    for ext in &sir.externs {
        out.push_str(&format!(
            "// extern {} fn {}(...) -> {}\n",
            ext.bridge.as_str(),
            ext.name,
            ext.return_type
        ));
    }
    for func in &sir.functions {
        out.push_str(&format!(
            "int32_t {}(/* {} params */);\n",
            func.name,
            func.params.len()
        ));
    }
    for robot in &sir.robot_names {
        out.push_str(&format!("void spanda_robot_{robot}_init(void);\n"));
        let behaviors: Vec<_> = sir
            .behavior_names
            .iter()
            .filter(|_| true)
            .cloned()
            .collect();
        if !behaviors.is_empty() {
            out.push_str(&format!(
                "// robot {robot} behaviors: {}\n",
                behaviors.join(", ")
            ));
        }
    }
    let Program::Program {
        extern_functions, ..
    } = program;
    for ext in extern_functions {
        out.push_str(&render_extern_c(ext));
    }
    out.push_str("\nint32_t spanda_main(void) {\n  return 0;\n}\n");
    out
}

fn render_wasm_sir(sir: &SirProgram) -> String {
    let mut out = String::from(";; Generated by spanda codegen --target wasm (SIR v1)\n");
    out.push_str("(module\n");
    if let Some(name) = &sir.module_name {
        out.push_str(&format!("  ;; module {name}\n"));
    }
    for ext in &sir.externs {
        out.push_str(&format!(
            "  (import \"env\" \"{}\" (func ${}))\n",
            ext.name, ext.name
        ));
    }
    for func in &sir.functions {
        out.push_str(&format!(
            "  (func ${} (export \"{}\") (result i32) i32.const 0)\n",
            func.name, func.name
        ));
    }
    out.push_str("  (func (export \"spanda_main\") (result i32) i32.const 0)\n");
    out.push_str(")\n");
    out
}

fn render_esp32(program: &Program) -> String {
    let Program::Program {
        module_name,
        robots,
        ..
    } = program;

    let mut out = String::from("// Generated by spanda codegen --target esp32\n");
    out.push_str("#include <Arduino.h>\n\n");
    if let Some(name) = module_name {
        out.push_str(&format!("// module {name}\n"));
    }
    out.push_str("void setup() {\n  Serial.begin(115200);\n}\n\n");
    out.push_str("void loop() {\n");
    for robot in robots {
        let RobotDecl::RobotDecl { name, .. } = robot;
        out.push_str(&format!("  // robot {name}\n"));
    }
    out.push_str("  delay(100);\n}\n");
    out
}

fn render_extern_c(ext: &ExternFnDecl) -> String {
    let ret = c_type(&ext.return_type);
    let params = ext
        .params
        .iter()
        .map(|p| format!("{} {}", c_type(&p.type_ann), p.name))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "extern {} {}({});\n",
        ret,
        ext.name,
        if params.is_empty() {
            "void".into()
        } else {
            params
        }
    )
}

#[allow(dead_code)]
fn render_fn_decl_c(func: &ModuleFnDecl) -> String {
    let ret = c_type(&func.return_type);
    let params = func
        .params
        .iter()
        .map(|p| format!("{} {}", c_type(&p.type_ann), p.name))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{} {}({});\n",
        ret,
        func.name,
        if params.is_empty() {
            "void".into()
        } else {
            params
        }
    )
}

fn c_type(ty: &SpandaType) -> &'static str {
    match ty {
        SpandaType::Int => "int32_t",
        SpandaType::Float => "double",
        SpandaType::Bool => "bool",
        SpandaType::String => "const char*",
        SpandaType::Bytes => "const uint8_t*",
        SpandaType::Void => "void",
        _ => "int32_t",
    }
}

pub fn wasm_deploy_manifest(source: &str) -> Result<String, SpandaError> {
    let tokens = crate::lexer::tokenize(source)?;
    let program = crate::parser::parse(tokens)?;
    let Program::Program {
        module_name,
        functions,
        robots,
        ..
    } = &program;
    let manifest = serde_json::json!({
        "target": "wasm",
        "module": module_name,
        "exports": functions.iter().map(|f| &f.name).collect::<Vec<_>>(),
        "robots": robots.iter().map(|r| r.name()).collect::<Vec<_>>(),
        "toolchain": "wasm-pack",
        "entry": "spanda_main",
    });
    Ok(serde_json::to_string_pretty(&manifest).unwrap_or_else(|_| "{}".into()))
}
