//! Emit LLVM IR from Spanda IR (SIR).
//!
//! Milestone 2: module/extern/robot signatures, behavior bodies lowered to
//! `libspanda_rt` calls where SIR supports them.

mod compile;

use spanda_core::foundations::BridgeKind;
use spanda_core::sir::{
    SirBehavior, SirExtern, SirFunction, SirProgram, SirStmt, SirVisibility,
};
use std::collections::BTreeSet;

pub use compile::{compile_native, CompileNativeOptions, CompileNativeResult};

pub fn emit_module_ir(sir: &SirProgram) -> String {
    let mut out = String::from("; Generated by spanda llvm-ir (SIR → LLVM Milestone 2)\n");
    out.push_str(&format!("target triple = \"{}\"\n\n", target_triple()));
    out.push_str("declare void @spanda_rt_drive(i8*, double, double)\n");
    out.push_str("declare void @spanda_rt_stop(i8*)\n");
    out.push_str("declare void @spanda_rt_emergency_stop()\n");
    out.push_str("declare void @spanda_rt_log_i32(i8*, i32)\n");
    out.push_str("declare void @spanda_rt_publish(i8*, i8*)\n");
    out.push_str("declare void @spanda_rt_loop_delay_ms(i64)\n\n");

    let strings = collect_string_literals(sir);
    for (idx, text) in strings.iter().enumerate() {
        out.push_str(&string_global_def(idx, text));
    }
    if !strings.is_empty() {
        out.push('\n');
    }

    let mut globals = String::new();
    collect_actuator_globals(sir, &mut globals);
    out.push_str(&globals);

    if let Some(name) = &sir.module_name {
        out.push_str(&format!("; module {name}\n"));
    }
    for import in &sir.imports {
        out.push_str(&format!("; import {import}\n"));
    }
    if !sir.behavior_names.is_empty() {
        out.push_str(&format!("; behaviors: {}\n", sir.behavior_names.join(", ")));
    }
    for robot in &sir.robots {
        for behavior in &robot.behaviors {
            out.push_str(&format!(
                "; robot {} behavior {} ({} stmts)\n",
                robot.name, behavior.name, behavior.stmt_count
            ));
            out.push_str(&emit_behavior_fn(robot.name.as_str(), behavior, &strings));
        }
        for task in &robot.task_names {
            out.push_str(&format!(
                "define void @spanda_robot_{}_task_{}() {{\n  ret void\n}}\n\n",
                robot.name, task
            ));
        }
    }
    out.push('\n');

    for ext in &sir.externs {
        out.push_str(&emit_extern_decl(ext));
    }
    for func in &sir.functions {
        if matches!(func.visibility, SirVisibility::Private) {
            continue;
        }
        out.push_str(&emit_function(func, &strings));
    }
    for robot in &sir.robot_names {
        out.push_str(&format!(
            "define void @spanda_robot_{robot}_init() {{\n  ret void\n}}\n\n"
        ));
    }
    if !has_export_main(sir) {
        out.push_str(&emit_native_main(sir));
    }
    out
}

fn has_export_main(sir: &SirProgram) -> bool {
    sir.functions.iter().any(|f| {
        f.name == "main"
            && matches!(f.visibility, SirVisibility::Export | SirVisibility::Public)
    })
}

fn emit_native_main(sir: &SirProgram) -> String {
    if let Some(robot) = sir.robots.first() {
        if let Some(behavior) = robot.behaviors.first() {
            return format!(
                "define i32 @main() {{\n  call void @spanda_robot_{}_{}()\n  ret i32 0\n}}\n",
                robot.name, behavior.name
            );
        }
    }
    "define i32 @main() {\n  ret i32 0\n}\n".into()
}

fn collect_string_literals(sir: &SirProgram) -> Vec<String> {
    let mut set = BTreeSet::new();
    set.insert(String::new());
    for func in &sir.functions {
        collect_stmt_strings(&func.body, &mut set);
    }
    for robot in &sir.robots {
        for behavior in &robot.behaviors {
            collect_stmt_strings(&behavior.body, &mut set);
        }
    }
    set.into_iter().collect()
}

fn collect_stmt_strings(stmts: &[SirStmt], set: &mut BTreeSet<String>) {
    for stmt in stmts {
        match stmt {
            SirStmt::Publish { topic, payload } => {
                set.insert(topic.clone());
                if let Some(payload) = payload {
                    set.insert(payload.clone());
                }
            }
            SirStmt::LoopEvery { body, .. } => collect_stmt_strings(body, set),
            _ => {}
        }
    }
}

fn target_triple() -> &'static str {
    if cfg!(target_os = "macos") {
        if cfg!(target_arch = "aarch64") {
            "arm64-apple-macosx"
        } else {
            "x86_64-apple-macosx"
        }
    } else if cfg!(target_os = "linux") {
        if cfg!(target_arch = "aarch64") {
            "aarch64-unknown-linux-gnu"
        } else {
            "x86_64-unknown-linux-gnu"
        }
    } else {
        "x86_64-pc-windows-msvc"
    }
}

fn string_global_name(idx: usize) -> String {
    format!("@spanda_str_{idx}")
}

fn string_global_ptr_for(text: &str, strings: &[String]) -> String {
    let idx = strings
        .iter()
        .position(|s| s == text)
        .unwrap_or_else(|| panic!("missing string literal `{text}`"));
    format!(
        "getelementptr inbounds ([{len} x i8], [{len} x i8]* {name}, i64 0, i64 0)",
        len = text.len() + 1,
        name = string_global_name(idx)
    )
}

fn string_global_def(idx: usize, text: &str) -> String {
    let len = text.len() + 1;
    format!(
        "{name} = private unnamed_addr constant [{len} x i8] c\"{text}\\00\"\n",
        name = string_global_name(idx),
        len = len,
        text = escape_llvm_string(text)
    )
}

fn collect_actuator_globals(sir: &SirProgram, out: &mut String) {
    let mut names = Vec::new();
    for robot in &sir.robots {
        for behavior in &robot.behaviors {
            collect_actuator_names(&behavior.body, &mut names);
        }
    }
    if names.is_empty() {
        return;
    }
    for name in &names {
        out.push_str(&actuator_global_def(name));
    }
    out.push('\n');
}

fn collect_actuator_names(stmts: &[SirStmt], names: &mut Vec<String>) {
    for stmt in stmts {
        match stmt {
            SirStmt::ActuatorDrive { actuator, .. } | SirStmt::ActuatorStop { actuator } => {
                if !names.contains(actuator) {
                    names.push(actuator.clone());
                }
            }
            SirStmt::LoopEvery { body, .. } => collect_actuator_names(body, names),
            _ => {}
        }
    }
}

fn actuator_global_name(actuator: &str) -> String {
    format!("@spanda_actuator_{actuator}")
}

fn actuator_global_def(actuator: &str) -> String {
    let len = actuator.len() + 1;
    format!(
        "{name} = private unnamed_addr constant [{len} x i8] c\"{actuator}\\00\"\n",
        name = actuator_global_name(actuator),
        len = len,
        actuator = escape_llvm_string(actuator)
    )
}

fn actuator_global_ptr(actuator: &str) -> String {
    format!(
        "getelementptr inbounds ([{len} x i8], [{len} x i8]* {name}, i64 0, i64 0)",
        len = actuator.len() + 1,
        name = actuator_global_name(actuator)
    )
}

fn escape_llvm_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '\\' => "\\5C".chars().collect::<Vec<_>>(),
            '"' => "\\22".chars().collect::<Vec<_>>(),
            '\n' => "\\0A".chars().collect::<Vec<_>>(),
            _ => vec![c],
        })
        .collect()
}

fn emit_behavior_fn(robot: &str, behavior: &SirBehavior, strings: &[String]) -> String {
    let mut loop_id = 0usize;
    let mut body = emit_stmts(&behavior.body, "void", strings, &mut loop_id);
    if !body.contains("ret void") {
        body.push_str("  ret void\n");
    }
    format!(
        "define void @spanda_robot_{robot}_{}() {{\n{body}}}\n\n",
        behavior.name
    )
}

fn emit_stmts(
    stmts: &[SirStmt],
    return_kind: &str,
    strings: &[String],
    loop_id: &mut usize,
) -> String {
    let mut out = String::new();
    for stmt in stmts {
        out.push_str(&emit_stmt(stmt, return_kind, strings, loop_id));
    }
    out
}

fn emit_stmt(
    stmt: &SirStmt,
    return_kind: &str,
    strings: &[String],
    loop_id: &mut usize,
) -> String {
    match stmt {
        SirStmt::ActuatorDrive {
            actuator,
            linear,
            angular,
        } => format!(
            "  call void @spanda_rt_drive(i8* {}, double {linear}, double {angular})\n",
            actuator_global_ptr(actuator)
        ),
        SirStmt::ActuatorStop { actuator } => format!(
            "  call void @spanda_rt_stop(i8* {})\n",
            actuator_global_ptr(actuator)
        ),
        SirStmt::EmergencyStop => "  call void @spanda_rt_emergency_stop()\n".into(),
        SirStmt::ReturnInt { value } if return_kind == "i32" => {
            format!("  ret i32 {value}\n")
        }
        SirStmt::ReturnFloat { value } if return_kind == "double" => {
            format!("  ret double {value}\n")
        }
        SirStmt::ReturnVoid if return_kind == "void" => "  ret void\n".into(),
        SirStmt::LetInt { name, value } => format!("  ; let {name} = {value}\n"),
        SirStmt::Publish { topic, payload } => {
            let topic_ptr = string_global_ptr_for(topic, strings);
            let payload_ptr = payload
                .as_ref()
                .map(|p| string_global_ptr_for(p, strings))
                .unwrap_or_else(|| string_global_ptr_for("", strings));
            format!("  call void @spanda_rt_publish(i8* {topic_ptr}, i8* {payload_ptr})\n")
        }
        SirStmt::LoopEvery { interval_ms, body } => {
            let id = *loop_id;
            *loop_id += 1;
            let header = format!("loop{id}");
            let block = emit_stmts(body, return_kind, strings, loop_id);
            format!(
                "  br label %{header}\n\
                 {header}:\n\
                 {block}\
                   call void @spanda_rt_loop_delay_ms(i64 {ms})\n\
                   br label %{header}\n",
                header = header,
                block = block,
                ms = interval_ms.round() as i64
            )
        }
        SirStmt::Unsupported { label } => format!("  ; unsupported stmt: {label}\n"),
        _ => "  ; skipped stmt\n".into(),
    }
}

fn llvm_type(type_name: &str) -> &'static str {
    match type_name {
        "Int" | "Float" | "Path" | "Scan" => "i32",
        "Bool" => "i1",
        "String" | "Char" | "Bytes" => "i8*",
        "Void" | "void" => "void",
        _ if type_name.starts_with("number(") => "double",
        _ => "i32",
    }
}

fn emit_extern_decl(ext: &SirExtern) -> String {
    let ret = llvm_type(&ext.return_type);
    let params: Vec<String> = ext
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    let bridge = match ext.bridge {
        BridgeKind::Python => "python",
        BridgeKind::Cpp => "cpp",
        BridgeKind::Native => "native",
    };
    let sig = if ret == "void" {
        format!("declare void @{}({})", ext.name, params.join(", "))
    } else {
        format!("declare {} @{}({})", ret, ext.name, params.join(", "))
    };
    format!("; extern {bridge} {}\n{sig}\n\n", ext.name)
}

fn emit_function(func: &SirFunction, strings: &[String]) -> String {
    let ret = llvm_type(&func.return_type);
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    let mut loop_id = 0usize;
    let body = emit_stmts(&func.body, ret, strings, &mut loop_id);
    let fallback = if ret == "void" {
        "  ret void\n".to_string()
    } else if ret == "double" {
        "  ret double 0.0\n".to_string()
    } else {
        "  ret i32 0\n".to_string()
    };
    let body = if body.contains("ret ") {
        body
    } else {
        format!("{body}{fallback}")
    };
    format!(
        "define {} @{}({}) {{\n{body}}}\n\n",
        ret,
        func.name,
        params.join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use spanda_core::{lexer, lower_to_sir, parser, types};

    #[test]
    fn emits_llvm_ir_for_module_functions() {
        let source = r#"
module demo;

export fn main() -> Int { return 1; }

extern python fn py_add(a: Int, b: Int) -> Int;

robot R {
  actuator wheels: DifferentialDrive;
  behavior run() { wheels.stop(); }
}
"#;
        let program = parser::parse(lexer::tokenize(source).unwrap()).unwrap();
        types::check(&program).unwrap();
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("define i32 @main("));
        assert!(ir.contains("ret i32 1"));
        assert!(ir.contains("declare i32 @py_add("));
        assert!(ir.contains("declare void @spanda_rt_stop("));
        assert!(ir.contains("call void @spanda_rt_stop("));
        assert!(ir.contains("define i32 @main("));
        assert!(ir.contains("ret i32 1"));
        assert!(ir.contains("@spanda_robot_R_init"));
        assert!(!ir.contains("call void @spanda_robot_R_run()"));
    }

    #[test]
    fn emits_drive_rt_call_for_behavior() {
        let source = r#"
robot R {
  actuator wheels: DifferentialDrive;
  behavior run() { wheels.drive(linear: 0.3 m/s, angular: 0.0 rad/s); }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("call void @spanda_rt_drive("));
        assert!(ir.contains("double 0.3"));
    }

    #[test]
    fn emits_loop_and_publish_calls() {
        let source = r#"
robot R {
  topic status: String publish on "/status";
  actuator wheels: DifferentialDrive;
  behavior run() {
    publish status with "ok";
    loop every 50ms { wheels.stop(); }
  }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("call void @spanda_rt_publish("));
        assert!(ir.contains("call void @spanda_rt_loop_delay_ms(i64 50)"));
        assert!(ir.contains("loop0:"));
    }
}
