//! Emit LLVM IR from Spanda IR (SIR).
//!
//! Milestone 2: module/extern/robot signatures, behavior bodies lowered to
//! `libspanda_rt` calls where SIR supports them.

use spanda_core::foundations::BridgeKind;
use spanda_core::sir::{
    SirBehavior, SirExtern, SirFunction, SirProgram, SirStmt, SirVisibility,
};

pub fn emit_module_ir(sir: &SirProgram) -> String {
    let mut out = String::from("; Generated by spanda llvm-ir (SIR → LLVM Milestone 2)\n");
    out.push_str("target triple = \"x86_64-unknown-linux-gnu\"\n\n");
    out.push_str("declare void @spanda_rt_drive(i8*, double, double)\n");
    out.push_str("declare void @spanda_rt_stop(i8*)\n");
    out.push_str("declare void @spanda_rt_emergency_stop()\n");
    out.push_str("declare void @spanda_rt_log_i32(i8*, i32)\n\n");

    let mut globals = String::new();
    collect_actuator_globals(sir, &mut globals);
    out.push_str(&globals);

    if let Some(name) = &sir.module_name {
        out.push_str(&format!("; module {name}\n"));
    }
    for import in &sir.imports {
        out.push_str(&format!("; import {import}\n"));
    }
    if !sir.behavior_names.is_empty() {
        out.push_str(&format!("; behaviors: {}\n", sir.behavior_names.join(", ")));
    }
    for robot in &sir.robots {
        for behavior in &robot.behaviors {
            out.push_str(&format!(
                "; robot {} behavior {} ({} stmts)\n",
                robot.name, behavior.name, behavior.stmt_count
            ));
            out.push_str(&emit_behavior_fn(robot.name.as_str(), behavior));
        }
        for task in &robot.task_names {
            out.push_str(&format!(
                "define void @spanda_robot_{}_task_{}() {{\n  ret void\n}}\n\n",
                robot.name, task
            ));
        }
    }
    out.push('\n');

    for ext in &sir.externs {
        out.push_str(&emit_extern_decl(ext));
    }
    for func in &sir.functions {
        if matches!(func.visibility, SirVisibility::Private) {
            continue;
        }
        out.push_str(&emit_function(func));
    }
    for robot in &sir.robot_names {
        out.push_str(&format!(
            "define void @spanda_robot_{robot}_init() {{\n  ret void\n}}\n\n"
        ));
    }
    out.push_str("define i32 @spanda_main() {\n  ret i32 0\n}\n");
    out
}

fn collect_actuator_globals(sir: &SirProgram, out: &mut String) {
    let mut names = Vec::new();
    for robot in &sir.robots {
        for behavior in &robot.behaviors {
            for stmt in &behavior.body {
                if let Some(name) = actuator_name(stmt) {
                    if !names.contains(&name) {
                        names.push(name);
                    }
                }
            }
        }
    }
    if names.is_empty() {
        return;
    }
    for name in &names {
        out.push_str(&actuator_global_def(name));
    }
    out.push('\n');
}

fn actuator_name(stmt: &SirStmt) -> Option<String> {
    match stmt {
        SirStmt::ActuatorDrive { actuator, .. } | SirStmt::ActuatorStop { actuator } => {
            Some(actuator.clone())
        }
        _ => None,
    }
}

fn actuator_global_name(actuator: &str) -> String {
    format!("@spanda_actuator_{actuator}")
}

fn actuator_global_def(actuator: &str) -> String {
    let len = actuator.len() + 1;
    format!(
        "{name} = private unnamed_addr constant [{len} x i8] c\"{actuator}\\00\"\n",
        name = actuator_global_name(actuator),
        len = len,
        actuator = escape_llvm_string(actuator)
    )
}

fn actuator_global_ptr(actuator: &str) -> String {
    format!(
        "getelementptr inbounds ([{len} x i8], [{len} x i8]* {name}, i64 0, i64 0)",
        len = actuator.len() + 1,
        name = actuator_global_name(actuator)
    )
}

fn escape_llvm_string(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '\\' => "\\5C".chars().collect::<Vec<_>>(),
            '"' => "\\22".chars().collect::<Vec<_>>(),
            '\n' => "\\0A".chars().collect::<Vec<_>>(),
            _ => vec![c],
        })
        .collect()
}

fn emit_behavior_fn(robot: &str, behavior: &SirBehavior) -> String {
    let mut body = emit_stmts(&behavior.body, "void");
    if !body.ends_with("ret void\n") {
        body.push_str("  ret void\n");
    }
    format!(
        "define void @spanda_robot_{robot}_{}() {{\n{body}}}\n\n",
        behavior.name
    )
}

fn emit_stmts(stmts: &[SirStmt], return_kind: &str) -> String {
    let mut out = String::new();
    for stmt in stmts {
        match stmt {
            SirStmt::ActuatorDrive {
                actuator,
                linear,
                angular,
            } => {
                out.push_str(&format!(
                    "  call void @spanda_rt_drive(i8* {}, double {linear}, double {angular})\n",
                    actuator_global_ptr(actuator)
                ));
            }
            SirStmt::ActuatorStop { actuator } => {
                out.push_str(&format!(
                    "  call void @spanda_rt_stop(i8* {})\n",
                    actuator_global_ptr(actuator)
                ));
            }
            SirStmt::EmergencyStop => {
                out.push_str("  call void @spanda_rt_emergency_stop()\n");
            }
            SirStmt::ReturnInt { value } if return_kind == "i32" => {
                out.push_str(&format!("  ret i32 {value}\n"));
            }
            SirStmt::ReturnFloat { value } if return_kind == "double" => {
                out.push_str(&format!("  ret double {value}\n"));
            }
            SirStmt::ReturnVoid if return_kind == "void" => {
                out.push_str("  ret void\n");
            }
            SirStmt::LetInt { name, value } => {
                out.push_str(&format!("  ; let {name} = {value}\n"));
            }
            SirStmt::Unsupported { label } => {
                out.push_str(&format!("  ; unsupported stmt: {label}\n"));
            }
            _ => {
                out.push_str("  ; skipped stmt\n");
            }
        }
    }
    out
}

fn llvm_type(type_name: &str) -> &'static str {
    match type_name {
        "Int" | "Float" | "Path" | "Scan" => "i32",
        "Bool" => "i1",
        "String" | "Char" | "Bytes" => "i8*",
        "Void" | "void" => "void",
        _ if type_name.starts_with("number(") => "double",
        _ => "i32",
    }
}

fn emit_extern_decl(ext: &SirExtern) -> String {
    let ret = llvm_type(&ext.return_type);
    let params: Vec<String> = ext
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    let bridge = match ext.bridge {
        BridgeKind::Python => "python",
        BridgeKind::Cpp => "cpp",
        BridgeKind::Native => "native",
    };
    let sig = if ret == "void" {
        format!("declare void @{}({})", ext.name, params.join(", "))
    } else {
        format!("declare {} @{}({})", ret, ext.name, params.join(", "))
    };
    format!("; extern {bridge} {}\n{sig}\n\n", ext.name)
}

fn emit_function(func: &SirFunction) -> String {
    let ret = llvm_type(&func.return_type);
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    let body = emit_stmts(&func.body, ret);
    let fallback = if ret == "void" {
        "  ret void\n".to_string()
    } else if ret == "double" {
        "  ret double 0.0\n".to_string()
    } else {
        "  ret i32 0\n".to_string()
    };
    let body = if body.contains("ret ") {
        body
    } else {
        format!("{body}{fallback}")
    };
    format!(
        "define {} @{}({}) {{\n{body}}}\n\n",
        ret,
        func.name,
        params.join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use spanda_core::{lexer, lower_to_sir, parser, types};

    #[test]
    fn emits_llvm_ir_for_module_functions() {
        let source = r#"
module demo;

export fn main() -> Int { return 1; }

extern python fn py_add(a: Int, b: Int) -> Int;

robot R {
  actuator wheels: DifferentialDrive;
  behavior run() { wheels.stop(); }
}
"#;
        let program = parser::parse(lexer::tokenize(source).unwrap()).unwrap();
        types::check(&program).unwrap();
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("define i32 @main("));
        assert!(ir.contains("ret i32 1"));
        assert!(ir.contains("declare i32 @py_add("));
        assert!(ir.contains("declare void @spanda_rt_stop("));
        assert!(ir.contains("call void @spanda_rt_stop("));
        assert!(ir.contains("@spanda_robot_R_init"));
        assert!(ir.contains("@spanda_robot_R_run"));
        assert!(ir.contains("@spanda_main"));
    }

    #[test]
    fn emits_drive_rt_call_for_behavior() {
        let source = r#"
robot R {
  actuator wheels: DifferentialDrive;
  behavior run() { wheels.drive(linear: 0.3 m/s, angular: 0.0 rad/s); }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("call void @spanda_rt_drive("));
        assert!(ir.contains("double 0.3"));
    }
}
