//! Emit LLVM IR from Spanda IR (SIR).
//!
//! Milestone 2: module/extern/robot signatures, behavior bodies lowered to
//! `libspanda_rt` calls where SIR supports them.

mod compile;

use spanda_core::foundations::BridgeKind;
use spanda_core::sir::{
    SirBehavior, SirCompareOp, SirExtern, SirFunction, SirMatchArm, SirProgram, SirStmt,
    SirVisibility,
};
use std::collections::{BTreeSet, HashSet};

pub use compile::{compile_native, CompileNativeOptions, CompileNativeResult};

pub fn emit_module_ir(sir: &SirProgram) -> String {
    // Emit module ir.
    //
    // Parameters:
    // - `sir` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_module_ir(sir);

    // Produce emit module ir with options as the result.
    emit_module_ir_with_options(sir, None, None)
}

pub fn emit_module_ir_with_triple(sir: &SirProgram, target_triple: Option<&str>) -> String {
    // Emit module ir with triple.
    //
    // Parameters:
    // - `sir` — input value
    // - `target_triple` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_module_ir_with_triple(sir, target_triple);

    // Produce emit module ir with options as the result.
    emit_module_ir_with_options(sir, target_triple, None)
}

pub fn emit_module_ir_with_options(
    sir: &SirProgram,
    target_triple: Option<&str>,
    hal_profile: Option<&str>,
) -> String {
    // Emit module ir with options.
    //
    // Parameters:
    // - `sir` — input value
    // - `target_triple` — input value
    // - `hal_profile` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_module_ir_with_options(sir, target_triple, hal_profile);

    // Compute hal for the following logic.
    let hal = hal_emit_config(hal_profile);
    let triple = target_triple
        .map(String::from)
        .or_else(|| hal.default_triple.clone())
        .unwrap_or_else(|| default_target_triple_for_host().to_string());
    let mut out = String::from("; Generated by spanda llvm-ir (SIR → LLVM Milestone 2)\n");

    // Emit output when hal profile provides a profile.
    if let Some(profile) = hal_profile {
        out.push_str(&format!("; hal-profile = \"{profile}\"\n"));

        // Take this path when hal.embedded.
        if hal.embedded {
            out.push_str("; SPANDA_HAL_EMBEDDED=1\n");
        }

        // Take this path when hal.esp32.
        if hal.esp32 {
            out.push_str("; SPANDA_HAL_ESP32=1\n");
        }
    }
    out.push_str(&format!("target triple = \"{triple}\"\n\n"));
    out.push_str("declare void @spanda_rt_drive(i8*, double, double)\n");
    out.push_str("declare void @spanda_rt_stop(i8*)\n");
    out.push_str("declare void @spanda_rt_emergency_stop()\n");
    out.push_str("declare void @spanda_rt_log_i32(i8*, i32)\n");
    out.push_str("declare void @spanda_rt_publish(i8*, i8*)\n");
    out.push_str("declare void @spanda_rt_subscribe(i8*)\n");
    out.push_str("declare void @spanda_rt_loop_delay_ms(i64)\n");
    out.push_str("declare double @spanda_rt_scan_nearest(i8*)\n");
    out.push_str("declare void @spanda_rt_store_bool(i8*, i8)\n");
    out.push_str("declare void @spanda_rt_store_string(i8*, i8*)\n");
    out.push_str("declare i8 @spanda_rt_eval_condition(i8*)\n\n");
    let strings = collect_string_literals(sir);

    // Iterate over enumerate with destructured elements.
    for (idx, text) in strings.iter().enumerate() {
        out.push_str(&string_global_def(idx, text));
    }

    // Skip further work when !strings is empty.
    if !strings.is_empty() {
        out.push('\n');
    }
    let mut globals = String::new();
    collect_actuator_globals(sir, &mut globals);
    out.push_str(&globals);

    // Emit output when module name provides a name.
    if let Some(name) = &sir.module_name {
        out.push_str(&format!("; module {name}\n"));
    }

    // Emit codegen metadata for each import.
    for import in &sir.imports {
        out.push_str(&format!("; import {import}\n"));
    }

    // Skip further work when behavior names is empty.
    if !sir.behavior_names.is_empty() {
        out.push_str(&format!("; behaviors: {}\n", sir.behavior_names.join(", ")));
    }

    // Handle each robot declared in the program.
    for robot in &sir.robots {
        // Process each behavior.
        for behavior in &robot.behaviors {
            out.push_str(&format!(
                "; robot {} behavior {} ({} stmts)\n",
                robot.name, behavior.name, behavior.stmt_count
            ));
            out.push_str(&emit_behavior_fn(
                robot.name.as_str(),
                behavior,
                &strings,
                &hal,
            ));
        }

        // Process each task name.
        for task in &robot.task_names {
            out.push_str(&format!(
                "define void @spanda_robot_{}_task_{}() {{\n  ret void\n}}\n\n",
                robot.name, task
            ));
        }
    }
    out.push('\n');

    // Declare each extern function in the generated output.
    for ext in &sir.externs {
        out.push_str(&emit_extern_decl(ext));
    }

    // Generate code for each module function.
    for func in &sir.functions {
        // Keep entries that match the expected pattern.
        if matches!(func.visibility, SirVisibility::Private) {
            continue;
        }
        out.push_str(&emit_function(func, &strings));
    }

    // Handle each robot declared in the program.
    for robot in &sir.robot_names {
        out.push_str(&format!(
            "define void @spanda_robot_{robot}_init() {{\n  ret void\n}}\n\n"
        ));
    }

    // Take the branch when has export main is false.
    if !has_export_main(sir) {
        out.push_str(&emit_native_main(sir));
    }
    out
}

#[derive(Clone, Default)]
struct HalEmitConfig {
    embedded: bool,
    esp32: bool,
    skip_network: bool,
    default_triple: Option<String>,
}

fn hal_emit_config(profile: Option<&str>) -> HalEmitConfig {
    // Hal emit config.
    //
    // Parameters:
    // - `profile` — input value
    //
    // Returns:
    // HalEmitConfig.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::hal_emit_config(profile);

    // Match on unwrap or and handle each case.
    match profile.unwrap_or("") {
        "embedded-arm" => HalEmitConfig {
            embedded: true,
            esp32: false,
            skip_network: false,
            default_triple: Some("aarch64-unknown-linux-gnu".into()),
        },
        "esp32" => HalEmitConfig {
            embedded: true,
            esp32: true,
            skip_network: true,
            default_triple: Some("xtensa-esp32-elf".into()),
        },
        "desktop" => HalEmitConfig {
            embedded: false,
            esp32: false,
            skip_network: false,
            default_triple: None,
        },
        _ => HalEmitConfig::default(),
    }
}

fn has_export_main(sir: &SirProgram) -> bool {
    //
    // Parameters:
    // - `sir` — input value
    //
    // Returns:
    // true or false.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::has_export_main(sir);

    // Iterate over functions.
    sir.functions.iter().any(|f| {
        f.name == "main" && matches!(f.visibility, SirVisibility::Export | SirVisibility::Public)
    })
}

fn emit_native_main(sir: &SirProgram) -> String {
    // Emit native main.
    //
    // Parameters:
    // - `sir` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_native_main(sir);

    // use robot when first is present.

    // Emit output when first provides a robot.
    if let Some(robot) = sir.robots.first() {
        // Emit output when first provides a behavior.
        if let Some(behavior) = robot.behaviors.first() {
            return format!(
                "define i32 @main() {{\n  call void @spanda_robot_{}_{}()\n  ret i32 0\n}}\n",
                robot.name, behavior.name
            );
        }
    }
    "define i32 @main() {\n  ret i32 0\n}\n".into()
}

fn collect_string_literals(sir: &SirProgram) -> Vec<String> {
    // Collect string literals.
    //
    // Parameters:
    // - `sir` — input value
    //
    // Returns:
    // Vec<String>.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::collect_string_literals(sir);

    // Create mutable set for accumulating results.
    let mut set = BTreeSet::new();
    set.insert(String::new());

    // Generate code for each module function.
    for func in &sir.functions {
        collect_stmt_strings(&func.body, &mut set);
    }

    // Handle each robot declared in the program.
    for robot in &sir.robots {
        // Process each behavior.
        for behavior in &robot.behaviors {
            collect_stmt_strings(&behavior.body, &mut set);
        }
    }
    set.into_iter().collect()
}

fn collect_stmt_strings(stmts: &[SirStmt], set: &mut BTreeSet<String>) {
    // Collect stmt strings.
    //
    // Parameters:
    // - `stmts` — input value
    // - `set` — input value
    //
    // Returns:
    // Nothing.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::collect_stmt_strings(stmts, set);

    // Execute each statement in sequence.
    for stmt in stmts {
        // Match on stmt and handle each case.
        match stmt {
            SirStmt::Publish { topic, payload } => {
                set.insert(topic.clone());

                // Emit output when payload provides a payload.
                if let Some(payload) = payload {
                    set.insert(payload.clone());
                }
            }
            SirStmt::Subscribe { target } => {
                set.insert(target.clone());
            }
            SirStmt::LetBool { name, .. } | SirStmt::LetDouble { name, .. } => {
                set.insert(name.clone());
            }
            SirStmt::LetString { name, value, .. } => {
                set.insert(name.clone());
                set.insert(value.clone());
            }
            SirStmt::IfBool {
                then_body,
                else_body,
                ..
            } => {
                collect_stmt_strings(then_body, set);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_stmt_strings(else_body, set);
                }
            }
            SirStmt::IfVar {
                condition,
                then_body,
                else_body,
                ..
            } => {
                set.insert(condition.clone());
                collect_stmt_strings(then_body, set);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_stmt_strings(else_body, set);
                }
            }
            SirStmt::IfCompareBool {
                variable,
                then_body,
                else_body,
                ..
            }
            | SirStmt::IfNotVar {
                variable,
                then_body,
                else_body,
                ..
            } => {
                set.insert(variable.clone());
                collect_stmt_strings(then_body, set);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_stmt_strings(else_body, set);
                }
            }
            SirStmt::IfCompareDouble {
                left,
                then_body,
                else_body,
                ..
            } => {
                set.insert(left.clone());
                collect_stmt_strings(then_body, set);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_stmt_strings(else_body, set);
                }
            }
            SirStmt::IfScanDistanceCompare {
                scan_var,
                then_body,
                else_body,
                ..
            } => {
                set.insert(scan_var.clone());
                collect_stmt_strings(then_body, set);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_stmt_strings(else_body, set);
                }
            }
            SirStmt::IfRuntime {
                condition,
                then_body,
                else_body,
                ..
            } => {
                set.insert(condition.clone());
                collect_stmt_strings(then_body, set);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_stmt_strings(else_body, set);
                }
            }
            SirStmt::MatchEnumUnit { arms, .. } => {
                // Process each arm.
                for arm in arms {
                    collect_stmt_strings(&arm.body, set);
                }
            }
            SirStmt::LoopEvery { body, .. } => collect_stmt_strings(body, set),
            _ => {}
        }
    }
}

pub fn default_target_triple_for_host() -> &'static str {
    // Default target triple for host.
    //
    // Parameters:
    // None.
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::default_target_triple_for_host();

    // take this path when cfg!(target os = "macos").
    if cfg!(target_os = "macos") {
        // Take this path when cfg!(target arch = "aarch64").
        if cfg!(target_arch = "aarch64") {
            "arm64-apple-macosx"
        } else {
            "x86_64-apple-macosx"
        }
    } else if cfg!(target_os = "linux") {
        // Take this path when cfg!(target arch = "aarch64").
        if cfg!(target_arch = "aarch64") {
            "aarch64-unknown-linux-gnu"
        } else {
            "x86_64-unknown-linux-gnu"
        }
    } else {
        "x86_64-pc-windows-msvc"
    }
}

fn string_global_name(idx: usize) -> String {
    // String global name.
    //
    // Parameters:
    // - `idx` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::string_global_name(idx);

    // Produce format! as the result.
    format!("@spanda_str_{idx}")
}

fn string_global_ptr_for(text: &str, strings: &[String]) -> String {
    // String global ptr for.
    //
    // Parameters:
    // - `text` — input value
    // - `strings` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::string_global_ptr_for(text, strings);

    // Compute idx for the following logic.
    let idx = strings
        .iter()
        .position(|s| s == text)
        .unwrap_or_else(|| panic!("missing string literal `{text}`"));
    format!(
        "getelementptr inbounds ([{len} x i8], [{len} x i8]* {name}, i64 0, i64 0)",
        len = text.len() + 1,
        name = string_global_name(idx)
    )
}

fn string_global_def(idx: usize, text: &str) -> String {
    // String global def.
    //
    // Parameters:
    // - `idx` — input value
    // - `text` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::string_global_def(idx, text);

    // Compute len for the following logic.
    let len = text.len() + 1;
    format!(
        "{name} = private unnamed_addr constant [{len} x i8] c\"{text}\\00\"\n",
        name = string_global_name(idx),
        len = len,
        text = escape_llvm_string(text)
    )
}

fn collect_actuator_globals(sir: &SirProgram, out: &mut String) {
    // Collect actuator globals.
    //
    // Parameters:
    // - `sir` — input value
    // - `out` — input value
    //
    // Returns:
    // Nothing.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::collect_actuator_globals(sir, out);

    // Create mutable names for accumulating results.
    let mut names = Vec::new();

    // Handle each robot declared in the program.
    for robot in &sir.robots {
        // Process each behavior.
        for behavior in &robot.behaviors {
            collect_actuator_names(&behavior.body, &mut names);
        }
    }

    // Skip further work when names is empty.
    if names.is_empty() {
        return;
    }

    // Iterate over each name in names.
    for name in &names {
        out.push_str(&actuator_global_def(name));
    }
    out.push('\n');
}

fn collect_actuator_names(stmts: &[SirStmt], names: &mut Vec<String>) {
    // Collect actuator names.
    //
    // Parameters:
    // - `stmts` — input value
    // - `names` — input value
    //
    // Returns:
    // Nothing.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::collect_actuator_names(stmts, names);

    // Execute each statement in sequence.
    for stmt in stmts {
        // Match on stmt and handle each case.
        match stmt {
            SirStmt::ActuatorDrive { actuator, .. } | SirStmt::ActuatorStop { actuator } => {
                // Check membership before continuing.
                if !names.contains(actuator) {
                    names.push(actuator.clone());
                }
            }
            SirStmt::IfBool {
                then_body,
                else_body,
                ..
            } => {
                collect_actuator_names(then_body, names);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_actuator_names(else_body, names);
                }
            }
            SirStmt::IfVar {
                then_body,
                else_body,
                ..
            } => {
                collect_actuator_names(then_body, names);

                // Emit output when else body provides a else body.
                if let Some(else_body) = else_body {
                    collect_actuator_names(else_body, names);
                }
            }
            SirStmt::MatchEnumUnit { arms, .. } => {
                // Process each arm.
                for arm in arms {
                    collect_actuator_names(&arm.body, names);
                }
            }
            SirStmt::LoopEvery { body, .. } => collect_actuator_names(body, names),
            _ => {}
        }
    }
}

fn actuator_global_name(actuator: &str) -> String {
    // Actuator global name.
    //
    // Parameters:
    // - `actuator` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::actuator_global_name(actuator);

    // Produce format! as the result.
    format!("@spanda_actuator_{actuator}")
}

fn actuator_global_def(actuator: &str) -> String {
    // Actuator global def.
    //
    // Parameters:
    // - `actuator` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::actuator_global_def(actuator);

    // Compute len for the following logic.
    let len = actuator.len() + 1;
    format!(
        "{name} = private unnamed_addr constant [{len} x i8] c\"{actuator}\\00\"\n",
        name = actuator_global_name(actuator),
        len = len,
        actuator = escape_llvm_string(actuator)
    )
}

fn actuator_global_ptr(actuator: &str) -> String {
    // Actuator global ptr.
    //
    // Parameters:
    // - `actuator` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::actuator_global_ptr(actuator);

    // Produce format! as the result.
    format!(
        "getelementptr inbounds ([{len} x i8], [{len} x i8]* {name}, i64 0, i64 0)",
        len = actuator.len() + 1,
        name = actuator_global_name(actuator)
    )
}

fn escape_llvm_string(s: &str) -> String {
    // Escape llvm string.
    //
    // Parameters:
    // - `s` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::escape_llvm_string(s);

    // Produce chars as the result.
    s.chars()
        .flat_map(|c| match c {
            '\\' => "\\5C".chars().collect::<Vec<_>>(),
            '"' => "\\22".chars().collect::<Vec<_>>(),
            '\n' => "\\0A".chars().collect::<Vec<_>>(),
            _ => vec![c],
        })
        .collect()
}

fn emit_behavior_fn(
    robot: &str,
    behavior: &SirBehavior,
    strings: &[String],
    hal: &HalEmitConfig,
) -> String {
    // Emit behavior fn.
    //
    // Parameters:
    // - `robot` — input value
    // - `behavior` — input value
    // - `strings` — input value
    // - `hal` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_behavior_fn(robot, behavior, strings, hal);

    // Create mutable loop id for accumulating results.
    let mut loop_id = 0usize;
    let mut branch_id = 0usize;
    let mut locals = EmitLocals::default();
    let mut body = emit_stmts(
        &behavior.body,
        "void",
        strings,
        &mut loop_id,
        &mut branch_id,
        &mut locals,
        hal,
    );

    // Check membership before continuing.
    if !body.contains("ret void") {
        body.push_str("  ret void\n");
    }
    format!(
        "define void @spanda_robot_{robot}_{}() {{\n{body}}}\n\n",
        behavior.name
    )
}

#[derive(Default)]
struct EmitLocals {
    bool_slots: HashSet<String>,
    enum_slots: HashSet<String>,
    double_slots: HashSet<String>,
}

fn double_slot(name: &str) -> String {
    // Double slot.
    //
    // Parameters:
    // - `name` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::double_slot(name);

    // Produce format! as the result.
    format!("spanda_double_{name}")
}

fn compare_op_fcmp(op: SirCompareOp) -> &'static str {
    // Compare op fcmp.
    //
    // Parameters:
    // - `op` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::compare_op_fcmp(op);

    // Match on op and handle each case.
    match op {
        SirCompareOp::Lt => "olt",
        SirCompareOp::Lte => "ole",
        SirCompareOp::Gt => "ogt",
        SirCompareOp::Gte => "oge",
        SirCompareOp::Eq => "oeq",
        SirCompareOp::Neq => "one",
    }
}

fn bool_slot(name: &str) -> String {
    // Bool slot.
    //
    // Parameters:
    // - `name` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::bool_slot(name);

    // Produce format! as the result.
    format!("spanda_bool_{name}")
}

fn enum_slot(name: &str) -> String {
    // Enum slot.
    //
    // Parameters:
    // - `name` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::enum_slot(name);

    // Produce format! as the result.
    format!("spanda_enum_{name}")
}

fn enum_payload_slot(name: &str, index: usize) -> String {
    // Enum payload slot.
    //
    // Parameters:
    // - `name` — input value
    // - `index` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::enum_payload_slot(name, index);

    // Produce format! as the result.
    format!("spanda_enum_{name}_p{index}")
}

fn emit_match_enum_arm_bindings(scrutinee: &str, arm: &SirMatchArm) -> String {
    // Emit match enum arm bindings.
    //
    // Parameters:
    // - `scrutinee` — input value
    // - `arm` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_match_enum_arm_bindings(scrutinee, arm);

    // Start the generated output buffer.
    let mut out = String::new();

    // Iterate over enumerate with destructured elements.
    for (index, binding) in arm.bindings.iter().enumerate() {
        let src = enum_payload_slot(scrutinee, index);
        out.push_str(&format!(
            "  %bind_load_{binding} = load double, double* %{src}\n\
               store double %bind_load_{binding}, double* %spanda_bind_{binding}\n"
        ));
    }
    out
}

fn emit_stmts(
    stmts: &[SirStmt],
    return_kind: &str,
    strings: &[String],
    loop_id: &mut usize,
    branch_id: &mut usize,
    locals: &mut EmitLocals,
    hal: &HalEmitConfig,
) -> String {
    // Emit stmts.
    //
    // Parameters:
    // - `stmts` — input value
    // - `return_kind` — input value
    // - `strings` — input value
    // - `loop_id` — input value
    // - `branch_id` — input value
    // - `locals` — input value
    // - `hal` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_stmts(stmts, return_kind, strings, loop_id, branch_id, locals, hal);

    // Start the generated output buffer.
    let mut out = String::new();

    // Execute each statement in sequence.
    for stmt in stmts {
        out.push_str(&emit_stmt(
            stmt,
            return_kind,
            strings,
            loop_id,
            branch_id,
            locals,
            hal,
        ));
    }
    out
}

fn emit_stmt(
    stmt: &SirStmt,
    return_kind: &str,
    strings: &[String],
    loop_id: &mut usize,
    branch_id: &mut usize,
    locals: &mut EmitLocals,
    hal: &HalEmitConfig,
) -> String {
    // Emit stmt.
    //
    // Parameters:
    // - `stmt` — input value
    // - `return_kind` — input value
    // - `strings` — input value
    // - `loop_id` — input value
    // - `branch_id` — input value
    // - `locals` — input value
    // - `hal` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_stmt(stmt, return_kind, strings, loop_id, branch_id, locals, hal);

    // Match on stmt and handle each case.
    match stmt {
        SirStmt::ActuatorDrive {
            actuator,
            linear,
            angular,
        } => format!(
            "  call void @spanda_rt_drive(i8* {}, double {linear}, double {angular})\n",
            actuator_global_ptr(actuator)
        ),
        SirStmt::ActuatorStop { actuator } => format!(
            "  call void @spanda_rt_stop(i8* {})\n",
            actuator_global_ptr(actuator)
        ),
        SirStmt::EmergencyStop => "  call void @spanda_rt_emergency_stop()\n".into(),
        SirStmt::ReturnInt { value } if return_kind == "i32" => {
            format!("  ret i32 {value}\n")
        }
        SirStmt::ReturnFloat { value } if return_kind == "double" => {
            format!("  ret double {value}\n")
        }
        SirStmt::ReturnVoid if return_kind == "void" => "  ret void\n".into(),
        SirStmt::LetInt { name, value } => format!("  ; let {name} = {value}\n"),
        SirStmt::LetBool { name, value } => {
            let slot = bool_slot(name);
            let name_ptr = string_global_ptr_for(name, strings);
            let mut out = String::new();

            // Take this path when locals.bool slots.insert(name.clone()).
            if locals.bool_slots.insert(name.clone()) {
                out.push_str(&format!("  %{slot} = alloca i1\n"));
            }
            let bit = if *value { 1 } else { 0 };
            out.push_str(&format!("  store i1 {bit}, i1* %{slot}\n"));
            out.push_str(&format!(
                "  call void @spanda_rt_store_bool(i8* {name_ptr}, i8 {bit})\n"
            ));
            out
        }
        SirStmt::LetDouble { name, value } => {
            let slot = double_slot(name);
            let name_ptr = string_global_ptr_for(name, strings);
            let mut out = String::new();

            // Take this path when locals.double slots.insert(name.clone()).
            if locals.double_slots.insert(name.clone()) {
                out.push_str(&format!("  %{slot} = alloca double\n"));
            }
            out.push_str(&format!("  store double {value}, double* %{slot}\n"));
            out.push_str(&format!(
                "  call void @spanda_rt_store_double(i8* {name_ptr}, double {value})\n"
            ));
            out
        }
        SirStmt::LetString { name, value } => {
            let name_ptr = string_global_ptr_for(name, strings);
            let value_ptr = string_global_ptr_for(value, strings);
            format!("  call void @spanda_rt_store_string(i8* {name_ptr}, i8* {value_ptr})\n")
        }
        SirStmt::LetEnumUnit { name, tag, .. } => {
            let slot = enum_slot(name);
            let mut out = String::new();

            // Take this path when locals.enum slots.insert(name.clone()).
            if locals.enum_slots.insert(name.clone()) {
                out.push_str(&format!("  %{slot} = alloca i32\n"));
            }
            out.push_str(&format!("  store i32 {tag}, i32* %{slot}\n"));
            out
        }
        SirStmt::LetEnumPayload {
            name,
            tag,
            payloads,
            ..
        } => {
            let slot = enum_slot(name);
            let mut out = String::new();

            // Take this path when locals.enum slots.insert(name.clone()).
            if locals.enum_slots.insert(name.clone()) {
                out.push_str(&format!("  %{slot} = alloca i32\n"));
            }
            out.push_str(&format!("  store i32 {tag}, i32* %{slot}\n"));

            // Iterate over enumerate with destructured elements.
            for (index, value) in payloads.iter().enumerate() {
                let payload_slot = enum_payload_slot(name, index);
                out.push_str(&format!("  %{payload_slot} = alloca double\n"));
                out.push_str(&format!(
                    "  store double {value}, double* %{payload_slot}\n"
                ));
            }
            out
        }
        SirStmt::Publish { topic, payload } => {
            let topic_ptr = string_global_ptr_for(topic, strings);
            let payload_ptr = payload
                .as_ref()
                .map(|p| string_global_ptr_for(p, strings))
                .unwrap_or_else(|| string_global_ptr_for("", strings));
            format!("  call void @spanda_rt_publish(i8* {topic_ptr}, i8* {payload_ptr})\n")
        }
        SirStmt::Subscribe { target } => {
            // Take this path when hal.skip network.
            if hal.skip_network {
                format!("  ; hal-profile: subscribe {target} omitted on esp32\n")
            } else {
                let topic_ptr = string_global_ptr_for(target, strings);
                format!("  call void @spanda_rt_subscribe(i8* {topic_ptr})\n")
            }
        }
        SirStmt::IfBool {
            condition,
            then_body,
            else_body,
        } => {
            // Take this path when *condition.
            if *condition {
                emit_stmts(
                    then_body,
                    return_kind,
                    strings,
                    loop_id,
                    branch_id,
                    locals,
                    hal,
                )
            } else if let Some(else_body) = else_body {
                emit_stmts(
                    else_body,
                    return_kind,
                    strings,
                    loop_id,
                    branch_id,
                    locals,
                    hal,
                )
            } else {
                String::new()
            }
        }
        SirStmt::IfVar {
            condition,
            then_body,
            else_body,
        } => {
            let id = *branch_id;
            *branch_id += 1;
            let slot = bool_slot(condition);
            let then_label = format!("if_then{id}");
            let else_label = format!("if_else{id}");
            let merge_label = format!("if_merge{id}");
            let then_ir = emit_stmts(
                then_body,
                return_kind,
                strings,
                loop_id,
                branch_id,
                locals,
                hal,
            );
            let else_ir = else_body
                .as_ref()
                .map(|body| emit_stmts(body, return_kind, strings, loop_id, branch_id, locals, hal))
                .unwrap_or_default();
            format!(
                "  %if_cond{id} = load i1, i1* %{slot}\n\
                   br i1 %if_cond{id}, label %{then_label}, label %{else_label}\n\
                 {then_label}:\n\
                 {then_ir}\
                   br label %{merge_label}\n\
                 {else_label}:\n\
                 {else_ir}\
                   br label %{merge_label}\n\
                 {merge_label}:\n"
            )
        }
        SirStmt::IfCompareBool {
            variable,
            equals,
            then_body,
            else_body,
        } => {
            let id = *branch_id;
            *branch_id += 1;
            let slot = bool_slot(variable);
            let then_label = format!("if_then{id}");
            let else_label = format!("if_else{id}");
            let merge_label = format!("if_merge{id}");
            let then_ir = emit_stmts(
                then_body,
                return_kind,
                strings,
                loop_id,
                branch_id,
                locals,
                hal,
            );
            let else_ir = else_body
                .as_ref()
                .map(|body| emit_stmts(body, return_kind, strings, loop_id, branch_id, locals, hal))
                .unwrap_or_default();
            format!(
                "  %if_cmp{id} = load i1, i1* %{slot}\n\
                   %if_ok{id} = icmp eq i1 %if_cmp{id}, {}\n\
                   br i1 %if_ok{id}, label %{then_label}, label %{else_label}\n\
                 {then_label}:\n\
                 {then_ir}\
                   br label %{merge_label}\n\
                 {else_label}:\n\
                 {else_ir}\
                   br label %{merge_label}\n\
                 {merge_label}:\n",
                // Take this path when *equals { 1 } else { 0 },.
                if *equals { 1 } else { 0 },
                then_label = then_label,
                else_label = else_label,
                merge_label = merge_label,
                then_ir = then_ir,
                else_ir = else_ir,
            )
        }
        SirStmt::IfNotVar {
            variable,
            then_body,
            else_body,
        } => {
            let id = *branch_id;
            *branch_id += 1;
            let slot = bool_slot(variable);
            let then_label = format!("if_then{id}");
            let else_label = format!("if_else{id}");
            let merge_label = format!("if_merge{id}");
            let then_ir = emit_stmts(
                then_body,
                return_kind,
                strings,
                loop_id,
                branch_id,
                locals,
                hal,
            );
            let else_ir = else_body
                .as_ref()
                .map(|body| emit_stmts(body, return_kind, strings, loop_id, branch_id, locals, hal))
                .unwrap_or_default();
            format!(
                "  %if_cmp{id} = load i1, i1* %{slot}\n\
                   %if_ok{id} = icmp eq i1 %if_cmp{id}, 0\n\
                   br i1 %if_ok{id}, label %{then_label}, label %{else_label}\n\
                 {then_label}:\n\
                 {then_ir}\
                   br label %{merge_label}\n\
                 {else_label}:\n\
                 {else_ir}\
                   br label %{merge_label}\n\
                 {merge_label}:\n",
                slot = slot,
                then_label = then_label,
                else_label = else_label,
                merge_label = merge_label,
                then_ir = then_ir,
                else_ir = else_ir,
            )
        }
        SirStmt::IfCompareDouble {
            left,
            op,
            right,
            then_body,
            else_body,
        } => {
            let id = *branch_id;
            *branch_id += 1;
            let slot = double_slot(left);
            let pred = compare_op_fcmp(*op);
            let then_label = format!("if_then{id}");
            let else_label = format!("if_else{id}");
            let merge_label = format!("if_merge{id}");
            let then_ir = emit_stmts(
                then_body,
                return_kind,
                strings,
                loop_id,
                branch_id,
                locals,
                hal,
            );
            let else_ir = else_body
                .as_ref()
                .map(|body| emit_stmts(body, return_kind, strings, loop_id, branch_id, locals, hal))
                .unwrap_or_default();
            format!(
                "  %if_dbl{id} = load double, double* %{slot}\n\
                   %if_ok{id} = fcmp {pred} double %if_dbl{id}, {right}\n\
                   br i1 %if_ok{id}, label %{then_label}, label %{else_label}\n\
                 {then_label}:\n\
                 {then_ir}\
                   br label %{merge_label}\n\
                 {else_label}:\n\
                 {else_ir}\
                   br label %{merge_label}\n\
                 {merge_label}:\n",
                slot = slot,
                pred = pred,
                right = right,
                then_label = then_label,
                else_label = else_label,
                merge_label = merge_label,
                then_ir = then_ir,
                else_ir = else_ir,
            )
        }
        SirStmt::IfScanDistanceCompare {
            scan_var,
            op,
            threshold,
            then_body,
            else_body,
        } => {
            let id = *branch_id;
            *branch_id += 1;
            let scan_ptr = string_global_ptr_for(scan_var, strings);
            let pred = compare_op_fcmp(*op);
            let then_label = format!("if_then{id}");
            let else_label = format!("if_else{id}");
            let merge_label = format!("if_merge{id}");
            let then_ir = emit_stmts(
                then_body,
                return_kind,
                strings,
                loop_id,
                branch_id,
                locals,
                hal,
            );
            let else_ir = else_body
                .as_ref()
                .map(|body| emit_stmts(body, return_kind, strings, loop_id, branch_id, locals, hal))
                .unwrap_or_default();
            format!(
                "  %scan_dist{id} = call double @spanda_rt_scan_nearest(i8* {scan_ptr})\n\
                   %if_ok{id} = fcmp {pred} double %scan_dist{id}, {threshold}\n\
                   br i1 %if_ok{id}, label %{then_label}, label %{else_label}\n\
                 {then_label}:\n\
                 {then_ir}\
                   br label %{merge_label}\n\
                 {else_label}:\n\
                 {else_ir}\
                   br label %{merge_label}\n\
                 {merge_label}:\n",
                scan_ptr = scan_ptr,
                pred = pred,
                threshold = threshold,
                then_label = then_label,
                else_label = else_label,
                merge_label = merge_label,
                then_ir = then_ir,
                else_ir = else_ir,
            )
        }
        SirStmt::IfRuntime {
            condition,
            then_body,
            else_body,
        } => {
            let id = *branch_id;
            *branch_id += 1;
            let cond_ptr = string_global_ptr_for(condition, strings);
            let then_label = format!("if_then{id}");
            let else_label = format!("if_else{id}");
            let merge_label = format!("if_merge{id}");
            let then_ir = emit_stmts(
                then_body,
                return_kind,
                strings,
                loop_id,
                branch_id,
                locals,
                hal,
            );
            let else_ir = else_body
                .as_ref()
                .map(|body| emit_stmts(body, return_kind, strings, loop_id, branch_id, locals, hal))
                .unwrap_or_default();
            format!(
                "  %rt_cond{id} = call i8 @spanda_rt_eval_condition(i8* {cond_ptr})\n\
                   %if_ok{id} = icmp ne i8 %rt_cond{id}, 0\n\
                   br i1 %if_ok{id}, label %{then_label}, label %{else_label}\n\
                 {then_label}:\n\
                 {then_ir}\
                   br label %{merge_label}\n\
                 {else_label}:\n\
                 {else_ir}\
                   br label %{merge_label}\n\
                 {merge_label}:\n",
                cond_ptr = cond_ptr,
                then_label = then_label,
                else_label = else_label,
                merge_label = merge_label,
                then_ir = then_ir,
                else_ir = else_ir,
            )
        }
        SirStmt::MatchEnumUnit {
            scrutinee, arms, ..
        } => {
            let id = *branch_id;
            *branch_id += 1;
            let slot = enum_slot(scrutinee);
            let end_label = format!("match_end{id}");
            let default_label = format!("match_default{id}");
            let mut switch_cases = String::new();
            let mut arm_blocks = String::new();

            // Iterate over enumerate with destructured elements.
            for (idx, arm) in arms.iter().enumerate() {
                let arm_label = format!("match_arm{id}_{idx}");
                switch_cases.push_str(&format!("    i32 {}, label %{arm_label}\n", arm.tag));
                arm_blocks.push_str(&format!("{arm_label}:\n"));

                // Process each binding.
                for binding in &arm.bindings {
                    arm_blocks.push_str(&format!("  %spanda_bind_{binding} = alloca double\n"));
                }
                arm_blocks.push_str(&emit_match_enum_arm_bindings(scrutinee, arm));
                arm_blocks.push_str(&emit_stmts(
                    &arm.body,
                    return_kind,
                    strings,
                    loop_id,
                    branch_id,
                    locals,
                    hal,
                ));
                arm_blocks.push_str(&format!("  br label %{end_label}\n"));
            }
            format!(
                "  %match_tag{id} = load i32, i32* %{slot}\n\
                   switch i32 %match_tag{id}, label %{default_label} [\n\
                 {switch_cases}\
                   ]\n\
                 {arm_blocks}\
                 {default_label}:\n\
                   br label %{end_label}\n\
                 {end_label}:\n"
            )
        }
        SirStmt::LoopEvery { interval_ms, body } => {
            let id = *loop_id;
            *loop_id += 1;
            let header = format!("loop{id}");
            let block = emit_stmts(body, return_kind, strings, loop_id, branch_id, locals, hal);
            let ms = if hal.esp32 {
                (interval_ms * 10.0).round() as i64
            } else {
                interval_ms.round() as i64
            };
            format!(
                "  br label %{header}\n\
                 {header}:\n\
                 {block}\
                   call void @spanda_rt_loop_delay_ms(i64 {ms})\n\
                   br label %{header}\n",
                header = header,
                block = block,
                ms = ms
            )
        }
        SirStmt::Unsupported { label } => format!("  ; unsupported stmt: {label}\n"),
        _ => "  ; skipped stmt\n".into(),
    }
}

fn llvm_type(type_name: &str) -> &'static str {
    // Llvm type.
    //
    // Parameters:
    // - `type_name` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::llvm_type(type_name);

    // Match on type name and handle each case.
    match type_name {
        "Int" | "Float" | "Path" | "Scan" => "i32",
        "Bool" => "i1",
        "String" | "Char" | "Bytes" => "i8*",
        "Void" | "void" => "void",
        _ if type_name.starts_with("number(") => "double",
        _ => "i32",
    }
}

fn emit_extern_decl(ext: &SirExtern) -> String {
    // Emit extern decl.
    //
    // Parameters:
    // - `ext` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_extern_decl(ext);

    // Compute ret for the following logic.
    let ret = llvm_type(&ext.return_type);
    let params: Vec<String> = ext
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    let bridge = match ext.bridge {
        BridgeKind::Python => "python",
        BridgeKind::Cpp => "cpp",
        BridgeKind::Native => "native",
    };
    let sig = if ret == "void" {
        format!("declare void @{}({})", ext.name, params.join(", "))
    } else {
        format!("declare {} @{}({})", ret, ext.name, params.join(", "))
    };
    format!("; extern {bridge} {}\n{sig}\n\n", ext.name)
}

fn emit_function(func: &SirFunction, strings: &[String]) -> String {
    // Emit function.
    //
    // Parameters:
    // - `func` — input value
    // - `strings` — input value
    //
    // Returns:
    // Text result.
    //
    // Options:
    // None.
    //
    // Example:
    // let result = spanda_llvm::emit_function(func, strings);

    // Compute ret for the following logic.
    let ret = llvm_type(&func.return_type);
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| format!("{} %{}", llvm_type(&p.type_name), p.name))
        .collect();
    let mut loop_id = 0usize;
    let mut branch_id = 0usize;
    let mut locals = EmitLocals::default();
    let hal = HalEmitConfig::default();
    let body = emit_stmts(
        &func.body,
        ret,
        strings,
        &mut loop_id,
        &mut branch_id,
        &mut locals,
        &hal,
    );
    let fallback = if ret == "void" {
        "  ret void\n".to_string()
    } else if ret == "double" {
        "  ret double 0.0\n".to_string()
    } else {
        "  ret i32 0\n".to_string()
    };
    let body = if body.contains("ret ") {
        body
    } else {
        format!("{body}{fallback}")
    };
    format!(
        "define {} @{}({}) {{\n{body}}}\n\n",
        ret,
        func.name,
        params.join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use spanda_core::{lexer, lower_to_sir, parser, types};

    #[test]
    fn emits_llvm_ir_for_module_functions() {
        // Emits llvm ir for module functions.
        //
        // Parameters:
        // None.
        //
        // Returns:
        // Nothing.
        //
        // Options:
        // None.
        //
        // Example:
        // let result = spanda_llvm::emits_llvm_ir_for_module_functions();

        let source = r#"
module demo;

export fn main() -> Int { return 1; }

extern python fn py_add(a: Int, b: Int) -> Int;

robot R {
  actuator wheels: DifferentialDrive;
  behavior run() { wheels.stop(); }
}
"#;
        let program = parser::parse(lexer::tokenize(source).unwrap()).unwrap();
        types::check(&program).unwrap();
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("define i32 @main("));
        assert!(ir.contains("ret i32 1"));
        assert!(ir.contains("declare i32 @py_add("));
        assert!(ir.contains("declare void @spanda_rt_stop("));
        assert!(ir.contains("call void @spanda_rt_stop("));
        assert!(ir.contains("define i32 @main("));
        assert!(ir.contains("ret i32 1"));
        assert!(ir.contains("@spanda_robot_R_init"));
        assert!(!ir.contains("call void @spanda_robot_R_run()"));
    }

    #[test]
    fn emits_drive_rt_call_for_behavior() {
        // Emits drive rt call for behavior.
        //
        // Parameters:
        // None.
        //
        // Returns:
        // Nothing.
        //
        // Options:
        // None.
        //
        // Example:
        // let result = spanda_llvm::emits_drive_rt_call_for_behavior();

        let source = r#"
robot R {
  actuator wheels: DifferentialDrive;
  behavior run() { wheels.drive(linear: 0.3 m/s, angular: 0.0 rad/s); }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("call void @spanda_rt_drive("));
        assert!(ir.contains("double 0.3"));
    }

    #[test]
    fn emits_loop_and_publish_calls() {
        // Emits loop and publish calls.
        //
        // Parameters:
        // None.
        //
        // Returns:
        // Nothing.
        //
        // Options:
        // None.
        //
        // Example:
        // let result = spanda_llvm::emits_loop_and_publish_calls();

        let source = r#"
robot R {
  topic status: String publish on "/status";
  actuator wheels: DifferentialDrive;
  behavior run() {
    publish status with "ok";
    loop every 50ms { wheels.stop(); }
  }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("call void @spanda_rt_publish("));
        assert!(ir.contains("call void @spanda_rt_loop_delay_ms(i64 50)"));
        assert!(ir.contains("loop0:"));
    }

    #[test]
    fn emits_if_subscribe_and_custom_triple() {
        // Emits if subscribe and custom triple.
        //
        // Parameters:
        // None.
        //
        // Returns:
        // Nothing.
        //
        // Options:
        // None.
        //
        // Example:
        // let result = spanda_llvm::emits_if_subscribe_and_custom_triple();

        let source = r#"
robot R {
  topic cmd: String subscribe on "/cmd";
  actuator wheels: DifferentialDrive;
  behavior run() {
    subscribe cmd;
    if false { wheels.drive(linear: 1.0 m/s, angular: 0.0 rad/s); } else { wheels.stop(); }
  }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir_with_triple(&sir, Some("aarch64-unknown-linux-gnu"));
        assert!(ir.contains("target triple = \"aarch64-unknown-linux-gnu\""));
        assert!(ir.contains("call void @spanda_rt_subscribe("));
        assert!(ir.contains("call void @spanda_rt_stop("));
        assert!(!ir.contains("call void @spanda_rt_drive("));
    }

    #[test]
    fn emits_if_var_and_match_switch() {
        // Emits if var and match switch.
        //
        // Parameters:
        // None.
        //
        // Returns:
        // Nothing.
        //
        // Options:
        // None.
        //
        // Example:
        // let result = spanda_llvm::emits_if_var_and_match_switch();

        let source = r#"
enum RobotState { Idle, Navigating }
robot R {
  actuator wheels: DifferentialDrive;
  behavior run() {
    let enabled = false;
    let state = Navigating;
    if enabled { wheels.drive(linear: 1.0 m/s, angular: 0.0 rad/s); } else { wheels.stop(); }
    match state {
      Idle => wheels.stop();
      Navigating => wheels.drive(linear: 0.2 m/s, angular: 0.0 rad/s);
    };
  }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir(&sir);
        assert!(ir.contains("alloca i1"));
        assert!(ir.contains("alloca i32"));
        assert!(ir.contains("switch i32"));
        assert!(ir.contains("br i1"));
        assert!(ir.contains("call void @spanda_rt_drive("));
    }

    #[test]
    fn emits_enum_payload_if_compare_and_hal_profile_comment() {
        // Emits enum payload if compare and hal profile comment.
        //
        // Parameters:
        // None.
        //
        // Returns:
        // Nothing.
        //
        // Options:
        // None.
        //
        // Example:
        // let result = spanda_llvm::emits_enum_payload_if_compare_and_hal_profile_comment();

        let source = r#"
enum DriveCmd { Stop, Drive(Float, Float) }
robot R {
  actuator wheels: DifferentialDrive;
  behavior run() {
    let cmd = Drive(0.3, 0.0);
    let flag = true;
    if flag == true { wheels.stop(); }
    if not flag { wheels.drive(linear: 0.1 m/s, angular: 0.0 rad/s); }
    match cmd {
      Stop => wheels.stop();
      Drive(l, a) => wheels.drive(linear: 0.3 m/s, angular: 0.0 rad/s);
    };
  }
}
"#;
        let sir = lower_to_sir(source).unwrap();
        let ir = emit_module_ir_with_options(&sir, None, Some("embedded-arm"));
        assert!(ir.contains("; hal-profile = \"embedded-arm\""));
        assert!(ir.contains("store double 0.3"));
        assert!(ir.contains("icmp eq i1"));
        assert!(ir.contains("spanda_bind_l"));
        assert!(ir.contains("switch i32"));
    }
}
